### ISSUE TITLE
[BUG]: Can't pick up roses without grabber

### ISSUE THREAD

**Issue by MadHareGraphics** [typical-developers/oaklands-feedback#1011]
### Roblox Username

White_Rabbit143

### What version did this issue occur in?

1.67.45

### Describe the issue in detail.

both regular and black roses cannot be 'picked' without a grabber, but once they are picked you can use your hand to move them around, I checked other flowers and fruits, and nothing else seems effected, its just the 2 types of roses.

### Provide some images / videos of the issue in action.

![Screenshot 2024-09-27 093013](https://github.com/user-attachments/assets/91168dd2-e8f1-48a5-a3b0-3196d178f67e)
![Screenshot 2024-09-27 093936](https://github.com/user-attachments/assets/a379caf7-c7c9-4c6d-bf61-dd942f44dcaf)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
this was a weird one!
