### ISSUE TITLE
[BAN APPEAL]: {ReVaJeNe}

### ISSUE THREAD

**Issue by ReVaJeNe** [typical-developers/oaklands-feedback#1012]
### Roblox Username

@Brawlcoin23q3

### Ban Reason

Have I been banned for griefing? And you saw what these people did, they robbed, humiliated the players, wasted all their resources, all I did was close their base with the help of friends so that they would stop doing this, I think many people know these inhumans, here are their nicknames. HelmutOlafMauer and Truthahmensch Can u unban please I won't do this anymore, I didn't know that according to the rules you can get banned for this, I just wanted to help other players, they had previously rammed my resources and scattered them around the map

### Before Submitting

- [X] I understand that this is the *only* appeal that I will get.
- [X] I have been completely honest about why I was banned.

**Comment by 1Peekaboo1** [comment]
> you saw what these people did, they robbed, humiliated the players, wasted all their resources

Saw...what? All i saw was these people reporting you for griefing them.

i will be glad to handle this if you provide ANY kind of evidence in defense of your actions.

**Comment by ReVaJeNe** [comment]
Come on im Youtuber for Oaklands i want play in Oaklandss They stopped me from playing, after which we shut them down so that they would stop, they just banned us through you, it's not fair

**Comment by ReVaJeNe** [comment]
I dont have provide because im saving on my base and they stopped but they start bulling other players
And i closed they on theme base

**Comment by 1Peekaboo1** [comment]
Don't have proof? Too bad. I don't have any reason to trust your words. I've seen your actions, i've seen people reporting you for these actions. Can't defend yourself? Don't do such things in the fist place then. We have a reporting system for a reason. Encountered a rule breaker? Make a report, provide evidence. Don't play vigilante

**Comment by ReVaJeNe** [comment]
Bro, I don't understand why I got banned if I didn't even see your rules in my eyes, you ignore the violations of the players of these two, but ban us for punishing them.Keep an eye on them, they will 100% continue to do this. I see them not for the first time and the first time I saw them when they were bullying at 3, like throwing his things all over the map and we helped him and now you ban us for punishing them

**Comment by PureOxy** [comment]
> Bro, I don't understand why I got banned if I didn't even see your rules in my eyes, you ignore the violations of the players of these two, but ban us for punishing them.Keep an eye on them, they will 100% continue to do this. I see them not for the first time and the first time I saw them when they were bullying at 3, like throwing his things all over the map and we helped him and now you ban us for punishing them

you aint got any proof.

**Comment by 1Peekaboo1** [comment]
Your words mean nothing to me. I need EVIDENCE.

**Comment by ReVaJeNe** [comment]
Im russian youtuber my subscribers wait my new video but im has banned

**Comment by ReVaJeNe** [comment]
Where i can take Evidence if i banned
I make 2 acc and try found they?

**Comment by PureOxy** [comment]
> Your words mean nothing to me. I need EVIDENCE.

thats what im saying, proof means everything

> Where i can take Evidence if i banned I make 2 acc and try found they?

alt detection will ban you for ban evading.

**Comment by ReVaJeNe** [comment]
Похуй мне поищи давай

**Comment by ReVaJeNe** [comment]
У меня их 100 бань по очереди давай удачи

**Comment by 1Peekaboo1** [comment]
Can't provide evidence? YOUR PROBLEMS. I recieved a report, it contained evidence of you and your friends blocking off a literal noob with a sellner and a default property.

**Comment by 1Peekaboo1** [comment]
Дружище, ты щас за мат и с сервера полетишь

**Comment by PureOxy** [comment]
> У меня их 100 бань по очереди давай удачи

russian, lemme translate that
oh you want me to be scared huh?

**Comment by ReVaJeNe** [comment]
Ваша поддержка работает когда не нужно а когда нужна спит и ниче не делает

**Comment by PureOxy** [comment]
you did it, you have no proof that the others did "that" to you, the fault is on you then.

**Comment by ReVaJeNe** [comment]
Бан за гриф на 7 дней это бред если поддержка работает так то лучше я покину вашу игру и не буду делать контент и гайды для русскоязычных игроков наслаждайтесь жизни

**Comment by 1Peekaboo1** [comment]
Окей, по английски не понимаешь, напишу на русском. 
Я получил жалобу. В жалобе были скрины того, как вы заблочили вообще зеленого нуба с дефолтной базой. Я сделал то что требовалось.

Приходишь ты, начинаешь жаловаться в ответ. Ну хорошо. Пруфы в твою защиту где? Нету?
Какая жалость. МНЕ ЧЕ СДЕЛАТЬ? ПОВЕРИТЬ НА СЛОВО?
У нас имеется налаженная система тикетов. Создаешь тикет, кидаешь пруфы проишествия.
Вместо этого ты с твоими друзьями решили поиграть во мстителей. Глаз за глаз, такое дело, и мир ослепнет. Ты в ситуации правым не будешь абсолютно.

**Comment by ReVaJeNe** [comment]
Ваши тикеты абсолютно не работают и так считаю не только я

**Comment by 1Peekaboo1** [comment]
дружище, я сейчас проверил, ты НИ ОДНОГО тикета не создал.

**Comment by 1Peekaboo1** [comment]
так что откуда такие вести, что ничего не работает, если ты даже не пытался?

**Comment by ReVaJeNe** [comment]
Мои друзья пытались разрабы просто заблокировали их а тикетов там висело очень много и никто им не занимался

**Comment by 1Peekaboo1** [comment]
я лично каждый день тикеты проверяю. Да даже тут, если бы мне было плевать, я бы сейчас даже на этот пост не ответил.

**Comment by 1Peekaboo1** [comment]
окей, скажи их ники в дискорде, проверим тикеты

**Comment by PureOxy** [comment]
хахахахаха

**Comment by 1Peekaboo1** [comment]
или лучше скажи номер их тикетов, если возможно

**Comment by ReVaJeNe** [comment]
У меня нет их дс они говорили мне об этом в  роблоксе
 в дс могу сказать про одного flippyyt ну я не уверен что создавал тикеты но он мне говорил что поддержка и модерация не работает абсолютно после чего его заблокировал в дискорде хуфер и еще один разработчик

**Comment by ReVaJeNe** [comment]
Я вообще не ебу что за тикеты вы говорите как со стеной про ваши правила негде не написано откуда мне знать за что можно получить бан? они делали даже хуже ранее пару месяцов назад я прямо помню этого бедного человека которого просто за булили 2 этих слов нет чтоб не отлетить их назвать

**Comment by PureOxy** [comment]
i translated this all and put it into the server

**Comment by ReVaJeNe** [comment]
окей мне все равно отправляй куда хочешь хоть в личку хуферу

**Comment by ReVaJeNe** [comment]
Одной игры больше одной игры меньше
жаль что вы разочаруете около 200 человек ведь у них больше не будет контента по оаку от меня на ютубе

**Comment by PureOxy** [comment]
уомп уомп.

> Одной игры больше одной игры меньше жаль что вы разочаруете около 200 человек ведь у них больше не будет контента по оаку от меня на ютубе

**Comment by ReVaJeNe** [comment]
Если вы баните людей за типо "гриф"  на 7 дней то вы реально работаете не в том направление

**Comment by 1Peekaboo1** [comment]
Ах, флиппи
Ну, начнем.
Его заблокировали все кто только можно, ибо он постоянно к ним клеился в лс. Не знаю, он так друзей искал, или что, но всех это достало. 
Тикеты игнорируются по той же причине. Не осталось никого, кого он бы не достал своим поведением. 
Да и содержание этих тикетов, скажу честно, оставляет желать лучшего.
Началось это всё с тикета, где он репортил кросстрейдеров. Ну, благое дело. В первый раз ведь он действительно отловил семерых. 
В этом же тикете он предоставил слабые доказательства, в большинстве из которых тот сам байтил людей на нарушение. Коммьюнити менеджеры разумеется отклонили такой репорт, на что тот взбесился, крыл всех трехэтажным матом у меня в лс, грозился что он сам этих кросстрейдеров накажет (напоминает вас с вашей игрой в мстителей там где это не нужно)
Ну покричал и ладно. Он потом пачками начал эти однотипные репорты клепать, в которых он продолжал байтить людей на нарушения. А некоторые репорты вообще даже не нарушали правил платформы. В тот момент он уже у менеджеров заблокированный был.  
Важное замечание. Я в почти каждом из этих репортов БЫЛ и переводил его скриншоты. Так что не устраивайте тут про то что его полностью игнорировали.

Ну и что по итогу? Флиппи изначально повел себя по свински по отношению к старшей администрации, а его репорты не состояли ни из чего дельного.

**Comment by ReVaJeNe** [comment]
Реально сделайте так:
в целом в оак надо добавить систему антигрифа
тоесть если что что бы можно было счделать чужие машины без колизии
как unstuck кнопка типа
у нас на сервере вообще чел просто взял и мосты все перекрыл
я не заскринил ток
Ваши баны приводят только к еще большому разочарованию чем добавить эту функцию

**Comment by ReVaJeNe** [comment]
Короче не хочу с вами спорить тоже самое что стенке говорить вам же все равно в падлу посмотреть что они щас делают наверно как обычно унижают какого то новичка ну вам же интересней что вам напишит нытик на бан в репорте

**Comment by 1Peekaboo1** [comment]
Могу сказать то же самое и про вас. Всего доброго.

**Comment by PureOxy** [comment]
ух ты. как "мило" с твоей стороны после твоих нытьевых призывов разбанить тебя, смирись с этим

> Короче не хочу с вами спорить тоже самое что стенке говорить вам же все равно в падлу посмотреть что они щас делают наверно как обычно унижают какого то новичка ну вам же интересней что вам напишит нытик на бан в репорте

**Comment by ReVaJeNe** [comment]
И вообще у вас есть хоть один тикет на ники которые я написал выше если нету то игроки терпилы я сделал посижу в бане нечего страшного

**Comment by ReVaJeNe** [comment]
Kaj кто ты вообще такой чтоб мне указывать потеряйся

**Comment by PureOxy** [comment]
> Kaj кто ты вообще такой чтоб мне указывать потеряйся
уомп уомп

**Comment by LuckFire** [comment]
Fun fact bud, that's one of our game mods! womp womp.
