### ISSUE TITLE
[BUG]: The vinyl machine will create a vinyl with invalid IDs

### ISSUE THREAD

**Issue by LeeHansHinLun** [typical-developers/oaklands-feedback#102]
### Roblox Username

LeeHansHinLun

### What version did this issue occur in?

1.42.0 Testing

### Describe the issue in detail.

The Vinyl Machine can create a vinyl that has invalid IDs (example: 0, which doesn't exist)
Playing the vinyl will cause two errors to appear in the developer console from attempting to find the audio file, and it will play nothing and mute the Oaklands background music.

(Side Note: These vinyls appears to have some use as I can just mute the background music when I'm on my base where I need to focus, but should probably be fixed)

### Provide some images / videos of the issue in action.

The video version of the bug (Have to upload to YouTube because it is too big, sorry)
[![Redirect to YouTube](https://github-production-user-asset-6210df.s3.amazonaws.com/79551623/275366533-de2cbedc-8b76-4093-a98d-585b873f275d.png)](https://www.youtube.com/watch?v=UyxOg6UKNGg "Redirect to YouTube")

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by KinderDeveloper** [comment]
Fixed this, will be released with the next update.
