### ISSUE TITLE
[BUG]: UI disappears if you reset your character whilst having the event thingy open

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#1033]
### Roblox Username

tupisupi

### What version did this issue occur in?

1.68.0

### Describe the issue in detail.

Title and video

### Provide some images / videos of the issue in action.

https://github.com/user-attachments/assets/e7a72824-b68b-48d7-ba30-3137eb57bdac

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
this happens with the grabbiest quest menu too, wow
