### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by ap0a3sassin** [typical-developers/oaklands-feedback#1038]
### Roblox Username

ap_as3assin

### What version did this issue occur in?

1.68.0

### Describe the issue in detail.

the book gets claimed under someone elses name and also says only20chereters sometimes

### Provide some images / videos of the issue in action.

o

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by Assasinsquid** [comment]
I also had this happen to me. I found a book in the new store, but as soon as you talk to the store clerk, the book gets claimed by a user "onlytwentycharacter" (the store clerk doesnt say anything about buying).
Also a note: I noticed that the halloween balloons are placed, the too are claimed by "onlytwentycharacter"

**Comment by HooferDevelops** [comment]
I don't know who added this book but it wasn't meant to be in the game, sorry.
