### ISSUE TITLE
[BUG]: Only Receiving Hammer From New Quest

### ISSUE THREAD

**Issue by LordMagiTEK** [typical-developers/oaklands-feedback#1043]
### Roblox Username

icanteven420

### What version did this issue occur in?

1.68.0

### Describe the issue in detail.

Regardless of the shard used or the moon cycle i have only received the hammer when completing the new quest have tried 4 times now

### Provide some images / videos of the issue in action.

On console cannot get video

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Going to close this as not a bug because I haven't heard any other users experiencing this issue. The moon shard being used is what decides the tool. The first 3 shards are one tool, the full moon is another, and the last 3 shards is the last tool.
