### ISSUE TITLE
[BUG]: Meteor core turned into Infused core

### ISSUE THREAD

**Issue by Not-MatanEilat** [typical-developers/oaklands-feedback#105]
### Roblox Username

matancool12

### What version did this issue occur in?

1.41.0

### Describe the issue in detail.

I've had a Meteor Core anchored in my plot for about a week, when I logged on 2 days ago all of the sudden the Meteor Core became an Infused Core and got the corresponding sprite (black core). Then the next time I logged on, the same core still is an Infused Core but for some odd reason it has the sprite of the normal Meteor Core (As you could see in the image below). And now this behavior keeps happening every time I log in, it always stays an Infused Core (judging by the name when hovering over it) but keeps changing between the Infused Core sprite and the Meteor Core sprite.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/57912969/fdb3f3f8-c66d-47a3-bd53-3f97c0ebcac5)
![image](https://github.com/typical-developers/oaklands-feedback/assets/57912969/3f073988-e3c2-4f54-90df-9452b88604a1)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
This happened due to this issue being fixed in newer versions.
