### ISSUE TITLE
[BUG]: Tether for grabbers gets squished

### ISSUE THREAD

**Issue by lightgold-square** [typical-developers/oaklands-feedback#1050]
### Roblox Username

pro_prestoh

### What version did this issue occur in?

1.68.0

### Describe the issue in detail.

When grabbing stuff from afar and going close to another object, the tether for the bulls gets squished and does not return to its original position.

### Provide some images / videos of the issue in action.

Uploading RPReplay_Final1728155646.mov…

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
This was just fixed in 1.68.1, thanks!
