### ISSUE TITLE
[BUG]: Base Dissapeared

### ISSUE THREAD

**Issue by SnackHeadFS** [typical-developers/oaklands-feedback#1064]
### Roblox Username

iliaskilla

### What version did this issue occur in?

1.68.3

### Describe the issue in detail.

My game crashed while loading in my base and when I restarted the game and loaded my base back in my entire base was gone with only a few bits of my base left over.
![192682189c510-screenshotUrl](https://github.com/user-attachments/assets/e0d3a9c6-cad0-4858-8b5a-7440e47e8bf4)

### Provide some images / videos of the issue in action.

![192682189c510-screenshotUrl](https://github.com/user-attachments/assets/3e704235-d28e-4bd3-9069-2917fe8887a6)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Reverted. I still don't know how or why this happens, it's very rare. I just know it happens when a player is loading and the server crashes during that period.

**Comment by SnackHeadFS** [comment]
Thank you!
