### ISSUE TITLE
[BUG]: holes in the map

### ISSUE THREAD

**Issue by Jacob901388** [typical-developers/oaklands-feedback#11]
### Roblox Username

Jacob901388

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

there are holes in the map that are located in the pathway next to the mushroom cave that was added in v1.38.1 and the right side of the bridge going into the savannah.

### Provide some images / videos of the issue in action.

![Skärmbild 2023-08-30 210629](https://github.com/typical-developers/oaklands-feedback/assets/111160475/3f4980a2-32a8-4868-8559-851d73f0d67f)
![Skärmbild 2023-08-30 210903](https://github.com/typical-developers/oaklands-feedback/assets/111160475/88377c3d-f70c-4a3b-9abe-44ab53a3baa0)
![Skärmbild 2023-08-30 210916](https://github.com/typical-developers/oaklands-feedback/assets/111160475/dce34194-4ff2-4cf2-ab7f-0cdab8ec0bfa)
![Skärmbild 2023-08-30 210932](https://github.com/typical-developers/oaklands-feedback/assets/111160475/ebc40659-b707-4d43-846e-a1da1897304a)
![image](https://github.com/typical-developers/oaklands-feedback/assets/111160475/13f0e696-f6cb-4183-adbe-a2dccb99cac4)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Jacob901388** [comment]
is this correct this time?

**Comment by Jacob901388** [comment]
to anyone else dont do this! https://github.com/typical-developers/oaklands-feedback/issues/8

**Comment by KinderDeveloper** [comment]
All fixed
