### ISSUE TITLE
[BUG]: Objects Occasionally Remain In Air After Reloading.

### ISSUE THREAD

**Issue by Pufikas** [typical-developers/oaklands-feedback#111]
### Roblox Username

MistoperIsPower

### What version did this issue occur in?

1.42.4

### Describe the issue in detail.

Objects placed on structures, then reloading the save and moving the structure below the objects, occasionally fail to fall to the ground. Interacting with the given items causes them to fall.

### Provide some images / videos of the issue in action.

![Capt3123123ure](https://github.com/typical-developers/oaklands-feedback/assets/85221441/a747a2f1-2ed5-4736-a76a-e03ce0f2c30a)
![Captu3213213re](https://github.com/typical-developers/oaklands-feedback/assets/85221441/6e62edcd-7708-4642-9d3b-9049a0bdde42)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Unsure if this still happens in latest, does anyone know?

**Comment by HooferDevelops** [comment]
Closing due to lack of response
