### ISSUE TITLE
[BUG]: Lumite and Magmite still have pre-nerf values despite changelog stating they've been nerfed

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#1122]
### Roblox Username

definitelynottupisupiiwouldnotremindtheteacherabouthomework

### What version did this issue occur in?

1.69.1

### Describe the issue in detail.

Title, tested this out only on Lumite but it most likely applies to Magmite too.

Got a piece, checked its price with stat tool, divided that price with volume to see per stud value and it was 305, changelog states that lumite used to be 304 so rounding issue. Moved said piece to resource hub to check its current sell value and it was 289 which is still higher than after nerf lumite value.

Stock market % increase does not matter in this as a resource never goes above its base value which should be 270 for lumite according to changelog.

### Provide some images / videos of the issue in action.

![kuva](https://github.com/user-attachments/assets/fcee824f-1c81-4815-aa46-405edc6ddeb6)
![kuva](https://github.com/user-attachments/assets/9c6c4c7a-ab92-4bd9-9d5b-b9b7049de159)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by windturbineceo** [comment]
what is that user bro💀

edit: I mean the Roblox user

**Comment by Imjustjokingwithya** [comment]
> what is that user bro💀

buddy im not trying to get ganged on for "snitching" that nerfs havent applied so i used an alias 🙏
