### ISSUE TITLE
[IMPROVEMENTS]: Show latest changelog upon joining

### ISSUE THREAD

**Issue by HooferDevelops** [typical-developers/oaklands-feedback#113]
### Roblox Username

HooferBevelops

### What do you think can have quality-of-life improvements?

The latest changelog should show when a user loads in, and permanently disappear after closing.

### How do you think things can be improved?

Right now, many users don't pay close attention to the latest updates for the game. I think an improvement would to show some an excerpt of the latest update. This would only show once for that update, and not bother the user about it again.

Provided below is an example of what I mean:
![image](https://github.com/typical-developers/oaklands-feedback/assets/60201971/2df3eaa5-3b0a-4d14-ac89-6e6e2acc9c72)

**Comment by LuckFire** [comment]
This is something I was wanting us to do a while back from what I recalled from a conversation about it, it seemed it would have been annoying to have implemented. Glad to see it being considered again.

**Comment by HooferDevelops** [comment]
> This is something I was wanting us to do a while back from what I recalled from a conversation about it, it seemed it would have been annoying to have implemented. Glad to see it being considered again.

Whenever you feel in the mood to make a concept, you could, or I could just wing it based on the current changelog design.

**Comment by LuckFire** [comment]
> > This is something I was wanting us to do a while back from what I recalled from a conversation about it, it seemed it would have been annoying to have implemented. Glad to see it being considered again.
> 
> Whenever you feel in the mood to make a concept, you could, or I could just wing it based on the current changelog design.

It'd likely just have the same layout but not display the past changelog details, probably better to just wing it and base it off the current one.

**Comment by HooferDevelops** [comment]
Added.
![RobloxStudioBeta_PQwv8J8p1I](https://github.com/typical-developers/oaklands-feedback/assets/60201971/faea3df9-1a20-4817-9321-78d699e1670d)

**Comment by HooferDevelops** [comment]
Edit: I added support for custom headers, allowing us to do cool things like this...
![image](https://github.com/typical-developers/oaklands-feedback/assets/60201971/2f721030-e370-4062-b002-68189434dc49)

**Comment by HooferDevelops** [comment]
> Why not bring back the ability to press the TD logo for the change log?

This feature has been re-implemented with the summary changelog.
