### ISSUE TITLE
[BAN APPEAL]: {username}

### ISSUE THREAD

**Issue by yo4212** [typical-developers/oaklands-feedback#1133]
### Roblox Username

JayMKLhacker

### Ban Reason

Hello, i didn't play oaklands for like 5-6 months, and now when i decided to play it i was banned.
I dont know why this happened but i think my brother is involved in this because we use same emails.
Please do something about this!
![33123123123](https://github.com/user-attachments/assets/d179dd51-0bf1-4dc6-ad76-213876d4ace5)

### Before Submitting

- [X] I understand that this is the *only* appeal that I will get.
- [X] I have been completely honest about why I was banned.

**Comment by HooferDevelops** [comment]
What is your brother's username?

**Comment by yo4212** [comment]
8ukx

**Comment by yo4212** [comment]
> What is your brother's username?

8ukx

**Comment by HooferDevelops** [comment]
You should have access now.

**Comment by yo4212** [comment]
> You should have access now.

OMG THANK YOU!
