### ISSUE TITLE
[BUG]: Corner Conveyor scales wrongly

### ISSUE THREAD

**Issue by Pufikas** [typical-developers/oaklands-feedback#114]
### Roblox Username

MistoperIsPower

### What version did this issue occur in?

1.42.4

### Describe the issue in detail.

Corner Conveyor's main part (middle square) doesn't rescale

### Provide some images / videos of the issue in action.

![Captu13re](https://github.com/typical-developers/oaklands-feedback/assets/85221441/a8659e45-7ab3-48f9-b77d-37d5b699f03b)
![Cap213123ture](https://github.com/typical-developers/oaklands-feedback/assets/85221441/fe4e573f-371e-4ff8-bf56-9f93b97ae9ac)
![Ca3213213pture](https://github.com/typical-developers/oaklands-feedback/assets/85221441/7b7217f0-db9a-45e8-980c-bdcae5cad4c8)
![Capt51515ure](https://github.com/typical-developers/oaklands-feedback/assets/85221441/0f3fe9e8-0719-4183-8a0e-8d572ca34c06)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by KinderDeveloper** [comment]
Small Corner conveyors can no-longer scale down
