### ISSUE TITLE
[BUG]: "Clare De Lune" vinyl not playing music

### ISSUE THREAD

**Issue by artz144** [typical-developers/oaklands-feedback#116]
### Roblox Username

chechyva

### What version did this issue occur in?

1.42.4

### Describe the issue in detail.

I tried rejoining but there is still no audio, every other vinyl works fine.

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/143691115/f5b4dd76-2dbf-4617-aa4d-5343cc4e55da

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Roblox content deleted the audio even though it was in public domain. Uploaded from a new source, no idea if it will get accepted.
