### ISSUE TITLE
[BUG]: As soon as I loaded into the main menu of the game, a dev console menu appeared...

### ISSUE THREAD

**Issue by PoseidonFAN1** [typical-developers/oaklands-feedback#1161]
### Roblox Username

@RobloxDenisTDM

### What version did this issue occur in?

The most recent version.

### Describe the issue in detail.

Ok, I have no idea what happened. I'm scared that I'll get banned for something that I didn't do, so I'm taking immediate action. Last I was one was over 24 hours ago. Nothing weird during that time. I just now tried getting back on and it loaded up the save selection menu. But this time there was a dev console menu of some sort in the center. I had no idea if it was there because someone in the lobby was doing something, or what, but it scared me that I might wrongly get in trouble for it. So I immediately grabbed my phone, took a picture, and closed the entire Roblox application. I need reassurance that I didn't do anything wrong and that this was a fluke or something. Please and thank you. 

### Provide some images / videos of the issue in action.

I took the picture with my phone, so I'm not sure how to post it here on PC, but if someone can walk me through the steps to do so, I would highly appreciate it!!

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by PoseidonFAN1** [comment]
I think I might have found a way to send the picture, hope this works:

![20241106_121728](https://github.com/user-attachments/assets/0478c4dc-7b58-427e-babd-53c9c0170707)

**Comment by UltrasBlade** [comment]
anyone can open this by pressing F9, its a roblox feature

**Comment by PoseidonFAN1** [comment]
Really?? Thank you so much!! I just don't understand how I pressed F9, I don't think I had touched my keyboard yet. Thank you so much again! I'm not the most knowledgeable when it comes to tech, lol.
