### ISSUE TITLE
[BUG]: Lumite Went to Heaven

### ISSUE THREAD

**Issue by ascariis-sys** [typical-developers/oaklands-feedback#1179]
### Roblox Username

ascariis

### What version did this issue occur in?

1.69.9

### Describe the issue in detail.

Where did it go bro

### Provide some images / videos of the issue in action.

https://github.com/user-attachments/assets/f6e3c2fc-c451-4a28-aca2-06a087209508

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by Wateristic** [comment]
brother, it went into your blueprint and filled in part of it.
