### ISSUE TITLE
[BUG]: Spelling mistake for an ingame tip!

### ISSUE THREAD

**Issue by fruitloopes** [typical-developers/oaklands-feedback#1191]
### Roblox Username

DinkyFroggy

### What version did this issue occur in?

1.69.3

### Describe the issue in detail.

There is a spelling mistake, says peopl instead of people :)

### Provide some images / videos of the issue in action.

![image](https://github.com/user-attachments/assets/d15a01c7-11fa-4671-9f0a-86597e3dd892)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
This is just the Roblox chat cutting off text for some reason
