### ISSUE TITLE
[BUG]: Oaklands Wiki giving wrong information, technically right information but in game its different?

### ISSUE THREAD

**Issue by MaddisonJaycee** [typical-developers/oaklands-feedback#1204]
### Roblox Username

MadexChan

### What version did this issue occur in?

1.69.3

### Describe the issue in detail.

player canon is meant to shoot the player when an input of 1000 is given, it does BUT it also still rotates the canon

### Provide some images / videos of the issue in action.

https://github.com/user-attachments/assets/e5bc98e6-a362-44d9-811b-87a4617b3a63

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by 1Peekaboo1** [comment]
First off: wiki is not officially affiliated with TD.
Second: fandom wiki is no longer maintained by wiki staff as they are in the process of moving to miraheze.
