### ISSUE TITLE
[BUG]: my material gun got duplicated

### ISSUE THREAD

**Issue by mochoxiUwU** [typical-developers/oaklands-feedback#1216]
i bought the two new gamepasses from someone and when i rejoined to get the you have been gifted screen i rejoined with a material gun in my inventory and one on the ground anchored(i only had one material gun and it was the anchored one until i rejoined)

**Comment by bigflabbytesticles** [comment]
you get a “free” material gun when you buy the unlimited storage pass, it was not duplicated.
