### ISSUE TITLE
[BUG]: Materials In new material Gun all dissapeared

### ISSUE THREAD

**Issue by ContentD3leted** [typical-developers/oaklands-feedback#1223]
### Roblox Username

GianMCoolGamer

### What version did this issue occur in?

1.70.0

### Describe the issue in detail.

I was using the material gun and randomly after using it everything got deleted. Now i had like 10 different materials which where far from being easily consumed as they where large amounts but they just dissapeared. No, I did not delete them. I am sure about it, It just randomly dissapeared

### Provide some images / videos of the issue in action.

![image](https://github.com/user-attachments/assets/7eee3916-008f-431e-990f-12801fb7b3d5)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
This is just visual, you should have your stuff in 1.70.1
