### ISSUE TITLE
[BUG]: New gun ignores the gamepass

### ISSUE THREAD

**Issue by ContentD3leted** [typical-developers/oaklands-feedback#1224]
### Roblox Username

GianMCoolGamer

### What version did this issue occur in?

1.70.0

### Describe the issue in detail.

The new material gun is ignoring the gamepass i got so its not letting me add anythign to the gun and when i buy the upgrades manually it doesnt increase the storage eighder

### Provide some images / videos of the issue in action.

![image](https://github.com/user-attachments/assets/a571012b-5020-4c91-b1c5-31994ca930bb)
![image](https://github.com/user-attachments/assets/5b88f2fc-3221-484e-a6ba-b7423895333a)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Just visual, should be fixed in 1.70.1
