### ISSUE TITLE
[BUG]: Memory cells dead in new update? Both in 1.70.0 and 1.70.1

### ISSUE THREAD

**Issue by siubikYT** [typical-developers/oaklands-feedback#1228]
### Roblox Username

aaden123

### What version did this issue occur in?

1.70.0

### Describe the issue in detail.

Memory cells dont work when supplied with any combination of reset/set values. I tried reseting and setting at the same time, and many different combinations but memory cells dont seem to work with any of them. They worked before just fine but now doesnt work.

### Provide some images / videos of the issue in action.

![image](https://github.com/user-attachments/assets/2fcfaeee-10a2-47e7-9e27-a7d50554e1a2)
![image](https://github.com/user-attachments/assets/7c558464-5c83-465d-9607-2785e7f2d1ba)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [x] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by siubikYT** [comment]
pls fix. I want to finish my 8 bit ALU.

Pls oaklands gods.

**Comment by siubikYT** [comment]
btw tested in 1.70.1 and doesn't work either

**Comment by KrazyBigJ** [comment]
my memory cells have been working fine in my logic contraptions, and logic consistently doesn't show an output value on the output wire if it isn't connected to something. have you tried connecting the memory cell to something like an LED and testing if it's still broken?
