### ISSUE TITLE
[BUG]: Lanterns and ropes in desert highlands tunnel still have collisions

### ISSUE THREAD

**Issue by UltrasBlade** [typical-developers/oaklands-feedback#125]
### Roblox Username

awesomepuppydog3

### What version did this issue occur in?

1.43.4

### Describe the issue in detail.

the lanterns and ropes in this tunnel still have collisions

![image](https://github.com/typical-developers/oaklands-feedback/assets/143657573/43c5c7cb-950e-4743-9700-62a3a01841d6)

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/143657573/75e41a29-5411-4e74-bc2e-33ca44cd025f)

![image](https://github.com/typical-developers/oaklands-feedback/assets/143657573/3912980a-9fe1-488b-83a1-87642ffa18ca)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [x] The details of this report are legitimate.

**Comment by UltrasBlade** [comment]
apparently all hanging lanterns in caves still have collisions. i can't tell if i'm misinterpreting it or not

**Comment by KinderDeveloper** [comment]
Hmm, Hoofer removed collisions and then I removed them again. Not sure why, I'll look into this tomorrow
