### ISSUE TITLE
[BUG]: Disappearing Crates

### ISSUE THREAD

**Issue by SpiritsRider** [typical-developers/oaklands-feedback#130]
### Roblox Username

TheHorseRider13

### What version did this issue occur in?

1.43.4

### Describe the issue in detail.

I had a few crates with items in them, I went to un-anchor them with the wand to add something into them. After adding the items into the crates I didn't re-anchor them and instead left them as they were. I then left my base and when I got back realized they had fully disappeared, not the crate or any of the contents inside said crates.

### Provide some images / videos of the issue in action.

Crates were placed where the red circles were. I only have an after photo as I didn't expect the crates to disappear. I also have no videos as I don't normally record myself playing.

![Screenshot (391)](https://github.com/typical-developers/oaklands-feedback/assets/149978086/5718e521-07c5-497a-b6d3-c90902563484)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by PassiveLemon** [comment]
Can confirm, I did also lose a crate. It left the items behind but the crate itself just disappeared. I think mine also were not anchored but were closed.
