### ISSUE TITLE
[BUG]: Boxed WMI pre alpha gifts went missing

### ISSUE THREAD

**Issue by lncrypt3d** [typical-developers/oaklands-feedback#134]
### Roblox Username

Lncrypt3d

### What version did this issue occur in?

1.43.4

### Describe the issue in detail.

I first joined the game a few months ago in April I believe I bought wmi pre alpha access and received the 3 gifts, I opened the statue but decided to leave the other 2 closed because I figured it would increase there value, I played the game for around 30 minutes that day logged off and haven't played since. When I logged on today I decided I was going to start playing the game more often I relized that while the statue was on my property the other 2 gifts were no where to be found, I have not traded them or given anyone property access and haven't played the game in months, the gifts simply vanished and I'm not really sure what to do besides reporting it here. 

### Provide some images / videos of the issue in action.

![Uploading 16994134306356638286891605383402.jpg…]()
![Uploading 16994134575988426781757029346571.jpg…]()

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by JackOfCool** [comment]
theres only 2 wmi gifts

**Comment by lncrypt3d** [comment]
My bad, discord told me there was 3 it's been months since I played, either
way I'm still missing that one gift
