### ISSUE TITLE
[BUG]:  Marbles all changed into one size only

### ISSUE THREAD

**Issue by Katapillah** [typical-developers/oaklands-feedback#135]
### Roblox Username

Katapilah

### What version did this issue occur in?

1.43.x

### Describe the issue in detail.

I had the complete set of Marbles, including some duplicates. (That is all colours and 3 sizes of each)   However about 3 or 4 days ago now upon logging in, I noticed they are all just one size. (I think it's the Large ..maybe medium - nothing to compare to now)

I play on a private server with 2 friends. Their marbles are still in 3 sizes.

There was one day where the server had lapsed and we used a public server briefly, I cannot confirm or deny that this is when the Bug formed.   
(Only thing we did note is that our plots were all like 90 or 180 degrees rotated)

Regards,
Katapilah.

### Provide some images / videos of the issue in action.

No pics but it still happened.

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Katapillah** [comment]
2 friends I play with are able to confirm this, one being the renter of the private server we play on.

This may have happened when I switched server versions. (Playstation or public server may have been lagging Private PCs)

**Comment by Katapillah** [comment]
Fixed ..but my balls are still broken. how shit.

**Comment by HooferDevelops** [comment]
If you had any rare golden balls I can reimburse, otherwise the rest will remain the same. I do not find it worthwhile replacing a not so valuable item.
