### ISSUE TITLE
[IMPROVEMENTS]: Seat Seams on Oakmobile

### ISSUE THREAD

**Issue by Azytrx** [typical-developers/oaklands-feedback#14]
### Roblox Username

AlexBunnyyy

### What do you think can have quality-of-life improvements?

The Oakmobile

### How do you think things can be improved?

It would be nice if you guys could just union the seats so the textures don't look all wonky.
![image](https://github.com/typical-developers/oaklands-feedback/assets/117944634/abb57a35-4d5c-4da4-9b53-d321272ead77)

**Comment by JackOfCool** [comment]
I don't think it's made with parts they would need to go edit the mesh or something
