### ISSUE TITLE
[BUG]:  Trees have an underglow on the ground beneath

### ISSUE THREAD

**Issue by Katapillah** [typical-developers/oaklands-feedback#147]
### Roblox Username

Katapilah

### What version did this issue occur in?

No idea

### Describe the issue in detail.

Trees seem to have an underglow on the ground beneath them (albeit faint) which is opposite logic to real life. 

            "Is that a firefly in the distance.. oh shiz it's just a damn tree"

### Provide some images / videos of the issue in action.

not required

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
I still am not sure why this happens, it's very confusing.

**Comment by LuckFire** [comment]
This appears to be some sort of bug with Roblox's engine and not something with Oaklands only. From the image, you can tell it happens in the normal baseplate with no changes done to the atmosphere / lighting.

![image](https://github.com/typical-developers/oaklands-feedback/assets/39076891/c9cec42a-ece6-42f4-8e67-ac8f3a698b7a)

**Comment by LuckFire** [comment]
This will be fixed when Hoofer pushes the new tree generation. Changing the collisions for the leaves to box collision fixed this weird lighting / shadow issue.

![image](https://github.com/typical-developers/oaklands-feedback/assets/39076891/99e25315-73ba-41fb-ac8f-3bbcffb1bd5c)
