### ISSUE TITLE
[IMPROVEMENTS]: Quick dismissal of NPC's dialogue, like PS has

### ISSUE THREAD

**Issue by Katapillah** [typical-developers/oaklands-feedback#150]
### Roblox Username

Katapilah

### What do you think can have quality-of-life improvements?

NPC Interaction Dismissal

### How do you think things can be improved?

Would be nice if there was a hotkey to dismiss the NPC's dialogue after interacting with them, or even an automated timed dismissal, as the GUI remains, occupying a portion of screen real estate.

NB: As we're to use the Keyboard already to interact with the NPC, switching back to the mouse is cumbersome.
Playstation has a hotkey to dismiss but PC does not.

**Comment by Katapillah** [comment]
Escape would be an anticipated dismissal key, if not Enter or something I guess

**Comment by KinderDeveloper** [comment]
Let me know if you have any other ideas where you could close out

Just made it so that B shuts the menu
