### ISSUE TITLE
[IMRPOVEMENTS]: Bridge NPC Behavior

### ISSUE THREAD

**Issue by Brixixx** [typical-developers/oaklands-feedback#155]
### Roblox Username

theterrariaboy5

### What do you think can have quality-of-life improvements?

Bridge NPC Behavior

### How do you think things can be improved?

This is a very short issue I have found while playing, but whenever you drive up to the bridge, you have to get out of your car to talk to the NPCs. I think this should be fixed so that you can stay in your vehicle and be able to let down the bridge. Thank you!

**Comment by Katapillah** [comment]
Dupe of https://github.com/typical-developers/oaklands-feedback/issues/137
