### ISSUE TITLE
[IMPROVEMENTS]: Change text for fungodite to white instead of black, it's not readable

### ISSUE THREAD

**Issue by UsefullSpoon** [typical-developers/oaklands-feedback#163]
### Roblox Username

Yael0128

### What do you think can have quality-of-life improvements?

Me being able to read the signs

### How do you think things can be improved?

It'll be great to read the signs lol

**Comment by UsefullSpoon** [comment]
![image](https://github.com/typical-developers/oaklands-feedback/assets/96959805/f4eeea87-4be2-4408-8f5f-eeb734fdcca8)
adding mythril to the issue too

**Comment by UltrasBlade** [comment]
you can customize the text on signs

```
<i>Italicized text</i>
<b>Bold Text</b>
<color red>Colored Text</color> 
<color ff0000>Hex Colored Text</color>
<stroke red>Stroke Text</stroke> 
<stroke ff0000>Hex Stroke Text</stroke>

```
example:
![image](https://github.com/typical-developers/oaklands-feedback/assets/143657573/a50b3ab7-e004-4ead-9237-65458ce12979)
![image](https://github.com/typical-developers/oaklands-feedback/assets/143657573/fba081bc-f0d4-4a6e-9006-9e80c3217d46)

**Comment by UsefullSpoon** [comment]
> you can customize the text on signs
> 
> ```
> <i>Italicized text</i>
> <b>Bold Text</b>
> <color red>Colored Text</color> 
> <color ff0000>Hex Colored Text</color>
> <stroke red>Stroke Text</stroke> 
> <stroke ff0000>Hex Stroke Text</stroke>
> ```
> 
> example: ![image](https://private-user-images.githubusercontent.com/143657573/290043307-a50b3ab7-e004-4ead-9237-65458ce12979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzA2NzgsIm5iZiI6MTcwMjQzMDM3OCwicGF0aCI6Ii8xNDM2NTc1NzMvMjkwMDQzMzA3LWE1MGIzYWI3LWUwMDQtNGVhZC05MjM3LTY1NDU4Y2UxMjk3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMTE5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTA5YjU1OGY2ZGQ3MTYzZjYzMDk3ZGE1MmM3NTkyNmI3MjBiZGMzY2VjOTAzM2Q1OWMyNDVmZjMxMDIxY2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YO9RRz3IB0aQ3_-gwxrov_jI6upC8MD0lY_VwDZikIs) ![image](https://private-user-images.githubusercontent.com/143657573/290043728-fba081bc-f0d4-4a6e-9006-9e80c3217d46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzA2NzgsIm5iZiI6MTcwMjQzMDM3OCwicGF0aCI6Ii8xNDM2NTc1NzMvMjkwMDQzNzI4LWZiYTA4MWJjLWYwZDQtNGE2ZS05MDA2LTllODBjMzIxN2Q0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMTE5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODZlYmVjYWVjY2I2OTM4NmI0MmExZWRlZTcxYWIzYzg5YTM0ZTEzZDk5N2M0ZGFkNTc0YzkyNWUyNjJlMTQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tVaB45aac1Q6IYV9QF_EZOt6irVfDQz8dkQIfyhdXYc)

i, didn't know that was a thing but it'd be nice for the standard color to be readable

**Comment by HooferDevelops** [comment]
This happens because the materials of the sign would darken the color, all three of these parts are the SAME color to Roblox!
![image](https://github.com/typical-developers/oaklands-feedback/assets/60201971/81d5db4f-8d63-4b46-9c82-f066d8c0a9a9)

Fixed this by adding a color influence multiplier for materials.
