### ISSUE TITLE
[BUG]: Stuff in trailers dissapearing on rejoin.

### ISSUE THREAD

**Issue by TheRaidedRaider** [typical-developers/oaklands-feedback#164]
### Roblox Username

TheRaidedRaider

### What version did this issue occur in?

1.44.0

### Describe the issue in detail.

I gathered some mushrooms, and then I had to rejoin. After I went onto my plot, I left and rejoined, to be met with nothing in the trailers, but my car in the same exact spot that I left it. (picture shows trailer and truck as I found it) I lost 25k because of a simple rejoin (that's a lot for me).

### Provide some images / videos of the issue in action.

![image_2023-12-01_174405470](https://github.com/typical-developers/oaklands-feedback/assets/152583068/8078a0b6-c1a3-48dd-9a15-bbdd673fa73b)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Marking this as wont fix due to this requiring the tree rewrite. Raw trees currently do not save, sorry.
