### ISSUE TITLE
[BUG]: Vial Problem

### ISSUE THREAD

**Issue by Brainless-person** [typical-developers/oaklands-feedback#166]
### Roblox Username

ummmmmm2012 or my Display name Brainless_Guy

### What version did this issue occur in?

1.44.0

### Describe the issue in detail.

basically the vial quest for the key card, the vials don't act like other items it doesn't weld to the truck so it doesn't fall plus i lost one because it dropped into acid and i have to do it again please just make it so it sticks to the the cars so i don't have to restart. plus it doesn't spawn where it spawned i checked **Everywhere**

### Provide some images / videos of the issue in action.

<img width="1186" alt="Screen Shot 2023-12-03 at 6 08 56 AM" src="https://github.com/typical-developers/oaklands-feedback/assets/152821119/1b25e933-2dcb-48ca-9a42-f492723a84da">

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Brainless-person** [comment]
forgot the proof
<img width="874" alt="Screen Shot 2023-12-03 at 6 19 29 AM" src="https://github.com/typical-developers/oaklands-feedback/assets/152821119/dd2a7b92-9ef7-44d9-a106-ec84e6ed9ddc"> (Not me the picture is from an video called All steps to getting keycard in oaklands roblox (LOGIC UPDATE) Made by Lightcry)

**Comment by UsefullSpoon** [comment]
the not welding is done on purpose, abt respawning. yeah it's the same as the button, once per server
