### ISSUE TITLE
[BUG]: Train Tracks Outside Of Plot

### ISSUE THREAD

**Issue by NMedvesky** [typical-developers/oaklands-feedback#169]
### Roblox Username

nikoijp

### What version did this issue occur in?

v1.45.0

### Describe the issue in detail.

You're able to rotate and move the train track object, which is a 1x1x1 cube, allowing the train track to go outside of your plot.

### Provide some images / videos of the issue in action.

![RobloxScreenShot20231210_154449404](https://github.com/typical-developers/oaklands-feedback/assets/72529248/dffdb86c-82d5-4349-8c7b-b99c8c5ec728)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by UsefullSpoon** [comment]
have the same thing in my game 
![image](https://github.com/typical-developers/oaklands-feedback/assets/96959805/134a508f-56b4-4ccb-ae44-402c319e4070)
someone just did this
