### ISSUE TITLE
[BUG]: Stat Tool doesn't show details correctly

### ISSUE THREAD

**Issue by byWambo** [typical-developers/oaklands-feedback#17]
### Roblox Username

WamboTV

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

If you click on a piece of cheese with the "Statistic Tool" it doesn't show "Cheese Color"/"Color" correctly. Instead it shows "StatTool_CheeseColor".

### Provide some images / videos of the issue in action.

![grafik](https://github.com/typical-developers/oaklands-feedback/assets/40476420/b27912d8-b55d-4b60-ad7d-9a47573f0556)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [x] The details of this report are legitimate.

**Comment by AkkozaDevelops** [comment]
Noted, if possible can someone compile a list of all StatTool suggestions / missing translation strings so I can implement them
