### ISSUE TITLE
[BUG]: Cave regions bleed into main

### ISSUE THREAD

**Issue by LuckFire** [typical-developers/oaklands-feedback#171]
### Roblox Username

coltbarrett112

### What version did this issue occur in?

v1.45.xx

### Describe the issue in detail.

Some areas where the tunnel used to be have regions for the cave bleed into the main region, causing an unintended change to the atmosphere.

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/39076891/29834969-81df-4aa8-a539-06b83372dffc

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by KinderDeveloper** [comment]
done :D
