### ISSUE TITLE
[BUG]: Reset Character Failure

### ISSUE THREAD

**Issue by RolyMoly** [typical-developers/oaklands-feedback#177]
### Roblox Username

JJLOLROCKS

### What version did this issue occur in?

1.45.4

### Describe the issue in detail.

While driving my car flipped and I decided to reset my character so I would not have to walk all the way back. I reset my character seated in the driver's seat, however, my body fell apart and I did not respawn. This was on a VIP server. I tried remotely respawning my vehicle with my logic setup however this did not resolve the issue. I also attempted to reset again several times. In the end, I had to rejoin the game. It is also worth noting that my health bard was depleted.

### Provide some images / videos of the issue in action.

![image_2023-12-14_221640946](https://github.com/typical-developers/oaklands-feedback/assets/153888475/7872569a-d5cb-4c96-9c14-a6bf58b7d9fe)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by UsefullSpoon** [comment]
i have this issue in other roblox games. It's a client side error
