### ISSUE TITLE
[BUG]: Supporter does not properly display and grant starting currency.

### ISSUE THREAD

**Issue by LuckFire** [typical-developers/oaklands-feedback#186]
### Roblox Username

coltbarrett112

### What version did this issue occur in?

v1.45.xx

### Describe the issue in detail.

The supporter gamepass is not only displaying the wrong number ($250 when it should be $1000), it is also not properly granting the currency for newly created save slots. Reported by @hokies4life06 on Discord.

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/39076891/90a74c70-698a-4239-89df-bd2295cce559

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Well now I feel quite bad! It only worked for those who bought in-game.
![image](https://github.com/typical-developers/oaklands-feedback/assets/60201971/71ebfc12-2e5b-4cdc-be1b-05ebe61f6264)
