### ISSUE TITLE
[BUG]: Continually holding objects when going into ESC menu

### ISSUE THREAD

**Issue by SunnyFloppyDiskStudios** [typical-developers/oaklands-feedback#187]
### Roblox Username

backpacksucs

### What version did this issue occur in?

1.45.6

### Describe the issue in detail.

Whenever you hold an item, then press ESC to go to that menu, you continue holding it.

### Provide some images / videos of the issue in action.

OneDrive: https://1drv.ms/f/s!AhJ-85r3fzq3gfA39V1U6mRMKfu-_Q?e=gLseVm

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Roblox passes the input end event for inputs when the escape menu is open. This cannot be resolved.
