### ISSUE TITLE
[IMPROVEMENTS]: Change The Keybinds for zoom in and out on controller

### ISSUE THREAD

**Issue by Elliottgamer43221** [typical-developers/oaklands-feedback#189]
### Roblox Username

Elliott34221

### What do you think can have quality-of-life improvements?

Extended Zoom Feature

### How do you think things can be improved?

The Option to zoom far out is nice but the key binds for controller should be changed to DpadUp to Zoom Out and DpadDown to Zoom In.

Dpad Up and Down don't currently have a use on Controller so the Extended Zoom feature should be changed to Up and Down Dpad, Using right joystick to Zoom is not that good because is uncomfortable to press after long periods of time.

Me and fellow console players are used to the original ROBLOX zoom feature that Oaklands originally had so adding that feature
back to Oakland's along with the extended zoom feature would be better for the average gameplay.

![XboxSeriesX_Dpad_Up](https://github.com/typical-developers/oaklands-feedback/assets/119004563/25cc2851-ed03-440c-bcea-0765fb898503)

**Comment by HooferDevelops** [comment]
This is already being addressed. Dpad cannot be used as it is used elsewhere.
