### ISSUE TITLE
[BUG]: Gift of oinky poinky structure is immovable

### ISSUE THREAD

**Issue by mrshepss** [typical-developers/oaklands-feedback#193]
### Roblox Username

mrshepss

### What version did this issue occur in?

1.45.6

### Describe the issue in detail.

When trying to move the structure, when you confirm the position doesn't update .

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/105090825/4207fdd0-7bab-4b4f-8a40-1f8465b7e43d

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by mrshepss** [comment]
I just tried in a public server and It seems to work fine, I can't recreate it today, I should've tried to move other structures when I recorded the video. I also tried to recreate it by going into a solo server and loading it into slot 5 (the conditions I had while recording) and nothing appeared to be broken. No idea why this happened.

**Comment by HooferDevelops** [comment]
Sorry, forgot to mark this as fixed in live. I did a live push for a fix.
