### ISSUE TITLE
[IMPROVEMENTS]: Network ownership issues. (Uneccessary game lag)

### ISSUE THREAD

**Issue by 40kq** [typical-developers/oaklands-feedback#197]
### Roblox Username

K88L (or) 40kq

### What do you think can have quality-of-life improvements?

Disable workspace streaming. (workspace.StreamingEnabled) (Uneccessary lag)

### How do you think things can be improved?

Workspace.StreamingEnabled (Other known as network streaming) breaks most games causing parts to disappear, rendering issues, excessive lag, parts lagging, spawns not working, bad client/server communications, etc.

I've worked with and without it and it's a nightmare. It breaks more games than it conveniences. I noticed that your game has a lot of reports of "flickering" parts. That's mostly caused by workspace.StreamingEnabled I used to have the same issue in my friends game till we disabled the streaming.

https:///i.imgur.com/EtURYYd.png -- "Flickering issue" addressed by you guys.

workspace.StreamingEnabled should be disabled.

Here's some forums showing everything wrong with it and as proof it does slow games down;

https://create.roblox.com/docs/workspace/streaming -- Official documentation on streaming (Roblox)
https://create.roblox.com/docs/physics/network-ownership -- Official documentation on network ownership (Pls invest into)

https://devforum.roblox.com/t/streaming-enabled-issues/2695286 -- Issue 1
https://devforum.roblox.com/t/streaming-enabled-causing-more-lag-than-without-it/2472951-- Issue 2
https://devforum.roblox.com/t/problem-with-spawns-because-of-streaming-enabled/2066102 -- Issue 3 (Spawning)
https://devforum.roblox.com/t/streaming-enabled-lags-when-loading-in-new-terrain/1996001 -- Issues listed

If you want to "optimize" your game I suggest rewriting a lot of the code you have. Your map doesn't have that many parts so it shouldn't be a big issue.  You can just script realms to load in once you reach a certain region. 

P.S. Please make the FPS counter a separate local-script. That way when you toggle the frame it also just disables the FPS counter script. They're known for reducing FPS by a decent amounts. 

P.S.S. Fix your horrible raycasting. It makes me want to gauge my eyes out.

**Comment by 40kq** [comment]
Addressing the FPS counter issue. They're known for decreasing your fps. I tested a couple different methods in a blank baseplate game. Without the FPS counters I get a solid 1K FPS. With the FPS counters I get closer to 350-500. Sometimes even worse. If you guys changed your counter to be a separate localscript that can be disabled/enabled within the setting toggle that'd be nice. By disable I mean localscript.Enabled = false not just making the textlabel not visible.

**Comment by LuckFire** [comment]
Thanks for your feedback, but it appears you have no idea what you're talking about.

First, stremaing enabled is not a bad thing at all. Disabling it would result in *worse* performance from our game (based on the one time we had to disable it). Second, FPS counters should have no impact on your actual FPS.

We have no plans to disable streaming enabled nor to change anything with the FPS counter.
