### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by boemstok** [typical-developers/oaklands-feedback#199]
### Roblox Username

tanki1111

### What version did this issue occur in?

1.45.7

### Describe the issue in detail.

getting stuck in the lava and i cant to back without rejoining

### Provide some images / videos of the issue in action.

![Uploading ezgif-4-6a6bc74d60.gif…]()

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by LuckFire** [comment]
Please edit your issue, it appears you didn't allow your gif to upload.

**Comment by LuckFire** [comment]
Closing this as stale because not enough information was provided. If anyone, or you, has more information to give, reopen this issue with the files and information commented.
