### ISSUE TITLE
[BUG]: the achievement "greedy land buyer", is not given to some people because of the old plots

### ISSUE THREAD

**Issue by Jacob901388** [typical-developers/oaklands-feedback#20]
### Roblox Username

Jacob901388

### What version did this issue occur in?

pre 1.37.0 - 1.39.5

### Describe the issue in detail.

if you owned a older plot and then expanded it too max size you will not be awarded the "greedy land buyer" achievement

### Provide some images / videos of the issue in action.

![Skärmbild 2023-08-31 064346](https://github.com/typical-developers/oaklands-feedback/assets/111160475/446a7e34-0ae7-44f6-bb90-45d7bd227a3b)
![image](https://github.com/typical-developers/oaklands-feedback/assets/111160475/5c891f1b-b490-42f9-801f-e5bcd6200fa1)
![Skärmbild 2023-08-31 064433](https://github.com/typical-developers/oaklands-feedback/assets/111160475/9076c345-cbd1-4a84-81d6-0c9894eb7ca3)
![Skärmbild 2023-08-31 221515](https://github.com/typical-developers/oaklands-feedback/assets/111160475/eef14fa5-7d89-42fb-a4bc-2d33c438a57a)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by AkkozaDevelops** [comment]
Does it not award the badge but display complete, or does it not detect the land size and not mark the achievement complete?

**Comment by Jacob901388** [comment]
> Does it not award the badge but display complete, or does it not detect the land size and not mark the achievement complete?

it displays as me having it but it hasent sent it too me
