### ISSUE TITLE
[BUG]: Architect Gamepass does not give a schematic

### ISSUE THREAD

**Issue by NMedvesky** [typical-developers/oaklands-feedback#200]
### Roblox Username

nikoijp

### What version did this issue occur in?

1.45.7

### Describe the issue in detail.

After purchasing the Architect Gamepass I don't have the Angled Corner Cylinder Wedge, all the other schematics appears to be there. I have also left the game and rejoined to make sure it was not just bugged in that instance.

### Provide some images / videos of the issue in action.

![RobloxScreenShot20240107_125343536](https://github.com/typical-developers/oaklands-feedback/assets/72529248/8e5e753c-c1d2-457a-ba44-f38fd475aa7c)

![RobloxScreenShot20240107_125253323](https://github.com/typical-developers/oaklands-feedback/assets/72529248/4bb88ee1-9a62-49c9-9fe3-54cf7cb60ce0)

![RobloxScreenShot20240107_125247572](https://github.com/typical-developers/oaklands-feedback/assets/72529248/91f4e14c-aa73-4a2e-93a0-09360104c66a)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Funny typo, thanks!
https://github.com/typical-developers/oaklands-feedback/assets/60201971/bd418190-dbc9-4a03-a592-3a7bbfd4835d
