### ISSUE TITLE
[BUG]: Mushroom Cave Flying/Swimming 

### ISSUE THREAD

**Issue by bwatdraws** [typical-developers/oaklands-feedback#210]
### Roblox Username

TripleTheGlitch

### What version did this issue occur in?

1.48.0

### Describe the issue in detail.

In certain spots in Mushroom cave when climbing the walls/pillars The player seems to enter water and begin swimming through the air. I discovered it while trying to get to a mysterious mushroom and suddenly began swimming. 

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/158851307/a3442a7f-42cc-490a-a9b9-f9527ba94d01

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by UltrasBlade** [comment]
this is intentional
![image](https://github.com/typical-developers/oaklands-feedback/assets/143657573/14623b67-fa4b-4866-b1c9-dcf23f82a98b)

**Comment by LuckFire** [comment]
> In certain spots . . .

The bug report here is that they weren't hit with the mushroom, but I could be wrong.

**Comment by HooferDevelops** [comment]
> > In certain spots . . .
> 
> The bug report here is that they weren't hit with the mushroom.

That would mean it's intentional behavior. The hitting does not create the swimming.

**Comment by JSS-BugReporters** [comment]
Bruh Thats Intentional
