### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by Zanados** [typical-developers/oaklands-feedback#216]
### Roblox Username

Zaberdin

### What version did this issue occur in?

1.50.0

### Describe the issue in detail.

All wires disappeared from all my stuff. Hundreds of wires. All my wires disappeared from everything i had wired up.  It’s going to take me a couple weeks or so to rewire.  Can you roll me back before the QoL update??

### Provide some images / videos of the issue in action.

![IMG_0141](https://github.com/typical-developers/oaklands-feedback/assets/160803325/e62eb2b8-2c2f-4d53-84cf-14ea72f33347)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Rolled back, thanks for the report.
