### ISSUE TITLE
[BUG]: Boxed Water Broken

### ISSUE THREAD

**Issue by JSS-BugReporters** [typical-developers/oaklands-feedback#217]
### Roblox Username

XTheTitanPlayz

### What version did this issue occur in?

1.50.0

### Describe the issue in detail.

The Boxed Water Is Bugged And Only Has A thin top and bottom layer

### Provide some images / videos of the issue in action.

![RobloxScreenShot20240222_141959916](https://github.com/typical-developers/oaklands-feedback/assets/152740294/048348b0-21a7-4efb-bfc7-681f22056eaf)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
This is intentional behavior due to the transparent water update.
