### ISSUE TITLE
[BUG]: Konami code still doesnt work when holding things.

### ISSUE THREAD

**Issue by Ashent1** [typical-developers/oaklands-feedback#219]
### Roblox Username

TeamGPX2

### What version did this issue occur in?

1.50.0

### Describe the issue in detail.

Hovering over items with tools is rainbow, but holding them, which is what you do 90% of the time, doesnt work. Nobody else except me has suggested this once, and maybe yall never saw it? I, uh, dunno.

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/147450949/57d56ece-abfe-4837-a10a-2d38a83319c4

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by KinderDeveloper** [comment]
fixed
