### ISSUE TITLE
[BUG]: Ghost objects 

### ISSUE THREAD

**Issue by JackOfCool** [typical-developers/oaklands-feedback#22]
### Roblox Username

JackThePC_Overlord

### What version did this issue occur in?

1.39.5 (and previous versions)

### Describe the issue in detail.

This is when you are carrying anything around and due to lag(I'm fairly certain client) the object stops moving midair. After the lag passes, the object stays floating midair and cannot be moved or interacted with. The actual object is where the object would have fallen originally, but it is invisible to only you. Other players in the server don't see the ghost object and just see the normal one, not invisible. If you touch the invisible object or someone else touches it, the ghost object will disappear and the actual one will appear. 

### Provide some images / videos of the issue in action.

Its kinda hard to replicate so I drew a picture, but if anyone knows what I'm talking about and has anything put it in the comments and I'll add it

Here's a bad illustration sorta showing it
https://cdn.discordapp.com/attachments/700800766738432082/1146808134137041006/download6.png

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by JackOfCool** [comment]
This could be a Roblox issue but I haven't seen it in other similar games like Lt2 or rc

**Comment by AkkozaDevelops** [comment]
I believe I know the cause of this, investigating shortly

**Comment by AkkozaDevelops** [comment]
Will have to come back to this, as I forget why it happens 💀 i waited too long
