### ISSUE TITLE
[BUG]: Cut/Edit wire feature only works on the middle section of wires (does not work at the ends near connection points)

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#225]
### Roblox Username

tupisupi

### What version did this issue occur in?

1.50.0

### Describe the issue in detail.

Basically title, this is very noticeable on longer distances. See video, very easy to recreate.

### Provide some images / videos of the issue in action.

https://cdn.discordapp.com/attachments/1063479705723998359/1210737139567034388/RobloxPlayerBeta_j9eACvuj29.mp4?ex=65eba5d4&is=65d930d4&hm=5df461ccd0279916898a09641c27691155b4d13aada9e5dfb632cb40892ba0c8&

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Imjustjokingwithya** [comment]
Similar to this report but not exactly, cut/copy wire feature does not work on wires **with turns** if you stand near connection points but if you walk closer to the middle and try to interact at the same spot it works. Discord message link (not media link) to TD server where I uploaded video https://discord.com/channels/865737627712749579/894024102174658644/1259536763123138711

**Comment by LuckFire** [comment]
> Similar to this report but not exactly, cut/copy wire feature does not work on wires **with turns** if you stand near connection points but if you walk closer to the middle and try to interact at the same spot it works. Discord message link (not media link) to TD server where I uploaded video https://discord.com/channels/865737627712749579/894024102174658644/1259536763123138711

Please report this as a separate issue.
