### ISSUE TITLE
Should wind particles appear in mines?

### ISSUE THREAD

**Issue by piw-piw** [typical-developers/oaklands-feedback#226]
### Roblox Username

Ninja_948bin

### What version did this issue occur in?

1.50.0

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/76477070/16a73df0-3c4f-4297-9bb9-d3111b2aeca1)
on the left

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
At first, not intentional, but after further discussion we have decided to keep this in as it looks good with the new lighting coming in v1.51.0
