### ISSUE TITLE
[BUG]: Signing Tombstone on 2/29 (Leap Day) Turns Into March 1st

### ISSUE THREAD

**Issue by SamBurned** [typical-developers/oaklands-feedback#230]
### Roblox Username

SamBurned

### What version did this issue occur in?

1.50.1

### Describe the issue in detail.

I signed a tombstone from the Halloween event on leap day and instead of being February 29 it says March 01

### Provide some images / videos of the issue in action.

![image_2024-02-29_175906505](https://github.com/typical-developers/oaklands-feedback/assets/161784348/e5a1cd59-8db2-41c9-b144-dfc8932c06e6)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Sign dates are based on the UTC timezone.
