### ISSUE TITLE
[BUG]: Confetti launcher not working

### ISSUE THREAD

**Issue by artz144** [typical-developers/oaklands-feedback#233]
### Roblox Username

chechyva

### What version did this issue occur in?

1.51.0

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/143691115/d3be7728-d6b3-4b2f-a551-a6afe104a5b4)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by KinderDeveloper** [comment]
Fixed sorry you had to play the game without the best feature in the game :(
