### ISSUE TITLE
[IMPROVEMENTS]: Give Anniversary Cake triangular collision

### ISSUE THREAD

**Issue by artz144** [typical-developers/oaklands-feedback#236]
### Roblox Username

chechyva

### What do you think can have quality-of-life improvements?

Give Anniversary Cake triangular collision instead of box collision so it can also be stacked into full cakes

### How do you think things can be improved?

![Screenshot_1](https://github.com/typical-developers/oaklands-feedback/assets/143691115/fc8fdc54-8a10-42e9-a302-6d207648f995)

**Comment by artz144** [comment]
Despite the collision change, which is stated in the changelog, the bounding box of the cake still remains the same 🤔

**Comment by KinderDeveloper** [comment]
Hmmm, will look into thank you

**Comment by KinderDeveloper** [comment]
Okay it's "actually" fixed now! I apologize for the inconvenience, it'll be fixed in v1.53.0

**Comment by KinderDeveloper** [comment]
<img width="820" alt="Screen Shot 2024-03-16 at 9 58 53 PM" src="https://github.com/typical-developers/oaklands-feedback/assets/85457996/a4278e75-243e-410b-9084-55c932c8d486">
