### ISSUE TITLE
[BUG]: Magma tree cliping into the ground in the meteor

### ISSUE THREAD

**Issue by ManancialGD** [typical-developers/oaklands-feedback#25]
### Roblox Username

BrenoGamerBr205

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

When I chop down a magma tree from a meteor, it stucks on the ground, happened like 5 times to me already

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/143729780/18f28991-4f00-40e0-bf5b-26e3e29dd6e0

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
This happens due to the tree rotating into the ground from how it grows. I _could_ add raycast detection to ensure this doesn't happen, but I don't feel like it would be worth the performance impact. I may go back to this in the future.
