### ISSUE TITLE
[BUG] Stats on open crates dont show

### ISSUE THREAD

**Issue by CyerraOaklands** [typical-developers/oaklands-feedback#251]
### Roblox Username

Cyerra1530

### What version did this issue occur in?

1.51.0 and before

### Describe the issue in detail.

When a crate is opened the stat tool will say there are no items (when there is) and that it isnt sealed. When a crate is closed it shows there are however many items and that its sealed, the worth of items and materials etc etc with the closed crate stats.

### Provide some images / videos of the issue in action.

![IMG_4957](https://github.com/typical-developers/oaklands-feedback/assets/162067142/16f6dd7f-b309-41cb-a55b-2002f6e9e38b)
![IMG_4956](https://github.com/typical-developers/oaklands-feedback/assets/162067142/10027ef6-9067-458d-91d6-54aa862ce6b0)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by KinderDeveloper** [comment]
Did this ever work before? Or is it a QoL suggestion, currently looking into the problem.

**Comment by CyerraOaklands** [comment]
> Did this ever work before? Or is it a QoL suggestion, currently looking into the problem.

Im not sure if it did work before because i dont usually use stat tool on open crates bc i can see whats in there.

**Comment by HooferDevelops** [comment]
I am unsure if this was originally in the game, but I have removed the display for this data if the crate is opened. This is all due to performance reasons.
