### ISSUE TITLE
[BUG]: Christmas Moai and Christmas Wreath

### ISSUE THREAD

**Issue by Chrisb2309** [typical-developers/oaklands-feedback#253]
### Roblox Username

Robloxbuddy_123

### What version did this issue occur in?

latest

### Describe the issue in detail.

Christmas Moai was a thing, and it had a Santa hat. I recently joined the game and I now realize that the hat is now gone.
Christmas Wreath won't fit on structures. What I mean by this, is that the inside of the wreath appears to be mesh. It is see through and I'm trying to place it on a cylinder hanging from the wall. The Wreath won't fit on it. I'm not sure if this item is intended to be made like this, but it would be nice to actually be able to use this item.

### Provide some images / videos of the issue in action.

![Screenshot 2024-03-05 170309](https://github.com/typical-developers/oaklands-feedback/assets/162259154/91b0a6eb-ded8-4408-9fa4-09f8f985f494)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HDMICIDE** [comment]
Christmas moai was applied to all moais then removed when the event was removed, it was not its own unique item,
