### ISSUE TITLE
[BUG]: New coil's icon is invisible

### ISSUE THREAD

**Issue by ManancialGD** [typical-developers/oaklands-feedback#26]
### Roblox Username

BrenoGamerBr205

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

The new coil icon on the hotbar is invisible

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/143729780/c93d271b-5d50-441a-ae13-78a4fe857bf5

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by AkkozaDevelops** [comment]
Fixed.

`Image Id was rbxassetid://rbxassetid://14559769009 rather than rbxassetid://14559769009`

**Comment by ManancialGD** [comment]
> Fixed.
> 
> `Image Id was rbxassetid://rbxassetid://14559769009 rather than rbxassetid://14559769009`

Jonathan is the GOAT!!
