### ISSUE TITLE
[BUG]: Property spawn point can't be removed

### ISSUE THREAD

**Issue by Sunivana** [typical-developers/oaklands-feedback#260]
### Roblox Username

Sunivana

### What version did this issue occur in?

1.51.1

### Describe the issue in detail.

put a property spawn point under my plot at an angle, which then caused it to get stuck, and not allowing me to interact with it. I can't remove it, and other property spawn points can't overwrite it

steps to reproduce
1. get spawn point
2. place under plot at a angle
3. cant remove it

**(sorry for the edits, pressed enter by mistake, the title should be _Property spawn point can't be removed_)**

### Provide some images / videos of the issue in action.

https://www.youtube.com/watch?v=Z64iBsmPIcA
![RobloxScreenShot20240306_180023328](https://github.com/typical-developers/oaklands-feedback/assets/162514920/335f791f-ae80-456d-bb91-ad72fbbac90c)

### Before Submitting

- [x] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by hokies4life06** [comment]
Have you tried putting a seat upside down and using that as a way to go under your base?

**Comment by Sunivana** [comment]
No I haven’t, I am going to try this, thank you!

**Comment by Baller1625** [comment]
Filters don't work properly pls fix
