### ISSUE TITLE
[BUG]: Typo in uncertain pickaxe description.

### ISSUE THREAD

**Issue by BlueSkyBothers** [typical-developers/oaklands-feedback#264]
### Roblox Username

BlueSkyBothers

### What version did this issue occur in?

1.51.1

### Describe the issue in detail.

The description for the uncertain pickaxe contains a typo.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/162658430/f013d2fa-1059-466e-bf54-1b8d5f44dcee)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by CyerraOaklands** [comment]
I feel like this was kinda intentional, its purple but you cant say purpleaxe and have it make sense but pink is close to purple. This is more likely a typo though.
