### ISSUE TITLE
[BUG]: Pirate boat spawn but there is nothing

### ISSUE THREAD

**Issue by Argonsov** [typical-developers/oaklands-feedback#265]
### Roblox Username

Argonsov

### What version did this issue occur in?

1.51.1

### Describe the issue in detail.

Pirate boat spawned (i think) but its invisible and only a single dynamite spawned.

### Provide some images / videos of the issue in action.

![image_2024-03-08_101412101](https://github.com/typical-developers/oaklands-feedback/assets/162659408/7fb32781-90d3-45f9-9929-75e1fe210bf7)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
This looks like it's due to assets failing to load.
