### ISSUE TITLE
[BUG]: Fliped normals in Moai

### ISSUE THREAD

**Issue by ManancialGD** [typical-developers/oaklands-feedback#27]
### Roblox Username

BrenoGamerBr205

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

I bought a moai, bring it to my plot, when I saw it's nose, I saw that the normals were fliped

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/143729780/e87f74d4-8055-4238-ab47-ad5dffff52a1

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by AkkozaDevelops** [comment]
haha funny nose

**Comment by AkkozaDevelops** [comment]
(in reality, doesn't matter and also fits the item)
