### ISSUE TITLE
[BUG]: Electric stones lose their electric effect after reload

### ISSUE THREAD

**Issue by Teatoes** [typical-developers/oaklands-feedback#278]
### Roblox Username

TehOnlyWinner

### What version did this issue occur in?

1.51.1

### Describe the issue in detail.

When saved on plot, electric stone loses its electric effect. 

### Provide some images / videos of the issue in action.

![img](https://github.com/typical-developers/oaklands-feedback/assets/138766266/d77615b9-9280-4d97-b025-1a3dabe4feb7)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
This is due to the Roblox particle limit, it's simply visual
