### ISSUE TITLE
[BUG]: Achievement UI not showing some achivements completion

### ISSUE THREAD

**Issue by ManancialGD** [typical-developers/oaklands-feedback#28]
### Roblox Username

BrenoGamerBr205

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

I don't know why, but I can't get the achievement "Avarage Oaklands Enjoyer" and "Alpha Player"
I have 80 hours of game right now, and the game still on alpha.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/143729780/63248bf5-a026-415a-b7be-06c26011a6ed)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by ManancialGD** [comment]
Oh, and this one too! 
![image](https://github.com/typical-developers/oaklands-feedback/assets/143729780/5c5b07a4-a3e8-49e3-85c6-fa287298d199)

**Comment by ManancialGD** [comment]
And this symble too
![image](https://github.com/typical-developers/oaklands-feedback/assets/143729780/9ffc30ef-7c8d-40d5-8bd7-46e40b5bfea0)

**Comment by TimLiz** [comment]
Enjoyer and Alpha achivements are being given, the problem is in UI, it not displays that its given.

**Comment by TimLiz** [comment]
https://www.roblox.com/badges/2129537559/Alpha-Player

https://www.roblox.com/badges/2129481339/Average-Oaklands-Enjoyer

You can make sure that you own it by going on those links

**Comment by ManancialGD** [comment]
> https://www.roblox.com/badges/2129537559/Alpha-Player
> 
> https://www.roblox.com/badges/2129481339/Average-Oaklands-Enjoyer
> 
> You can make sure that you own it by going on those links

Thank you!

**Comment by TimLiz** [comment]
Rename issue to "Achievement UI not showing some achivements completion"

**Comment by KinderDeveloper** [comment]
> And this progress doesn't make sense...
> ![image](https://user-images.githubusercontent.com/143729780/264697283-846cdcae-6353-466a-83ad-0cf75a780871.png)

What do you mean by the progress not making sense?

**Comment by ManancialGD** [comment]
> > And this progress doesn't make sense...
> > ![image](https://user-images.githubusercontent.com/143729780/264697283-846cdcae-6353-466a-83ad-0cf75a780871.png)
> 
> What do you mean by the progress not making sense?

because it should be 84 hours out of 216, but it is a 269,955 out of 777,660
Why 777,660? it should be 216, I am jot saying it is incorrect, but it should be in hours
