### ISSUE TITLE
[BUG]: breaks in water

### ISSUE THREAD

**Issue by piw-piw** [typical-developers/oaklands-feedback#280]
### Roblox Username

Ninja_948bin

### What version did this issue occur in?

1.51.1

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/76477070/81fc2ae7-1b92-4f6f-a2b0-7f100361a18c)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Roblox has building precision issues, and this unfortunately randomly happens, we cannot ever see it when creating.
