### ISSUE TITLE
[BUG]: Cannot replicate old unfilled schematics  

### ISSUE THREAD

**Issue by Pizzafan622** [typical-developers/oaklands-feedback#294]
### Roblox Username

Pizzafan622

### What version did this issue occur in?

1.52.1

### Describe the issue in detail.

When I try to replicate an unfilled schematic in the build menu, nothing happens. However, if I make a new schematic, I am able to replicate it until I rejoin the game.

### Provide some images / videos of the issue in action.

Uploading robloxapp-20240316-2055033.mp4…

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Going to mark this as closed as we are revamping the placement system soon.
