### ISSUE TITLE
[BUG]: Ambient sounds when chopping

### ISSUE THREAD

**Issue by Azytrx** [typical-developers/oaklands-feedback#3]
### Roblox Username

AlexBunnyyy

### What version did this issue occur in?

v1.39.5 (and previous)

### Describe the issue in detail.

When you hit a tree with an axe, you can hear after the initial chop a faint nature/birds/ambience which obviously shouldn't be there, this is with every sound effect turned off apart from sound effects itself.

### Provide some images / videos of the issue in action.

https://streamable.com/q85t3j

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by KinderDeveloper** [comment]
Are you sure that's not from the Living Axe "hiss" / "whisper" effect after chopping something?

**Comment by Azytrx** [comment]
> Are you sure that's not from the Living Axe "hiss" / "whisper" effect after chopping something?

I am very sure, I originally found this with the Tall Refined Axe (didn't have it at the time of that recording),
I've tested it with 3 more axes which confirms as I suspected, that it is an issue with the actual sound effect file itself.
https://streamable.com/vbqylz

**Comment by HooferDevelops** [comment]
Will need to get new sounds for chopping.

**Comment by KinderDeveloper** [comment]
Will be fixed with new tree chopping

**Comment by HooferDevelops** [comment]
This was fixed with the new chopping sounds that were added.
