### ISSUE TITLE
[IMPROVEMENTS]: Notify when a meteor is coming in from the atmosphere / lands

### ISSUE THREAD

**Issue by LuckFire** [typical-developers/oaklands-feedback#30]
### Roblox Username

coltbarrett112

### What do you think can have quality-of-life improvements?

How players are notified about meteors.

### How do you think things can be improved?

The shake is pretty good as is for letting players know when a meteor crashes, but there's a common issue I've seen where players just don't know when one spawns (presumably because it's so hard to hear the SFX for the meteor in the sky), so they don't know where one lands nor when it lands until there's a shake.

This is a huge issue when it comes to searching for it, because if the player didn't see where it landed, they're not going to know where it is if they want it. A way this could be made better is when one spawns, there could be UI that appears or a system chat message sent that states that one spawned, so players know that one spawned and they can look around in the sky for it.

However, this sort of change may defeat the purpose of buying information from the scientist, since she tells you when one spawns for cash.

**Comment by ManancialGD** [comment]
Honestly, I think it's very fun when the meteor strikes, and I start running in the map, chacing the meteor, after a while,you remember the common places that it spawns, I like the way it is now

**Comment by InvertedReaIity** [comment]
I find it especially annoying if I leave my computer on for a few minutes and I miss the meteor crashing. Combined with how fast it despawns after landing, this can often become pretty frustrating. Having some kind of tool in-game that would let you check if a meteor is present (Weather Radar), could possibly be another solution to the problem.

**Comment by ManancialGD** [comment]
> I find it especially annoying if I leave my computer on for a few minutes and I miss the meteor crashing. Combined with how fast it despawns after landing, this can often become pretty frustrating. Having some kind of tool in-game that would let you check if a meteor is present (Weather Radar), could possibly be another solution to the problem.

If you want to know when it lands, you can pay the scientist. I think it's a good solution,

**Comment by InvertedReaIity** [comment]
I'm talking about after it's landed in-game. This way you could check if it's currently in the server.

**Comment by ManancialGD** [comment]
> I'm talking about after it's landed in-game. This way you could check if it's currently in the server.

Yeah, maybe, but I think it is good as it is

**Comment by HooferDevelops** [comment]
I think a simple chat message would suffice, better to not overcomplicate it.

**Comment by ManancialGD** [comment]
> I think a simple chat message would suffice, better to not over-complicate it.

I vote "no"

**Comment by UltrasBlade** [comment]
I've never seen a meteor in the sky, so this would be a nice feature.

**Comment by CrimsonClaws** [comment]
> I think a simple chat message would suffice, better to not over-complicate it.

I think this could be nice as added functionality to the Scientist NPC. If everyone got a chat message when a Meteor spawns there'd be less of a reason to pay 3.5k to know when a meteor will fall since everyone would get a heads up at the most important time anyways.
