### ISSUE TITLE
[BUG]: Initializing Save Slots Forever.

### ISSUE THREAD

**Issue by jukepilot** [typical-developers/oaklands-feedback#308]
### Roblox Username

Jukepilot

### What version did this issue occur in?

1.52.1

### Describe the issue in detail.

Getting stuck on initializing save slots forever bug might be back. I solved it by rejoining, but that might be an issue worth looking into. The issue happens about 20 percent of the time, its annoying though.

This seems to be mentioned before but closed as solved**?** (hard question mark)

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/140344252/db3bbd92-005c-44ee-9e5c-e2257799993f

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
This can happen if your slot is unloading somewhere else. The other bug was a different issue.
