### ISSUE TITLE
[BUG]: barely any lumite spawning

### ISSUE THREAD

**Issue by DanielTheRealer** [typical-developers/oaklands-feedback#312]
### Roblox Username

@Kitten_Queen07

### What version did this issue occur in?

1.52.1

### Describe the issue in detail.

is this a bug or something? theres barely any lumite spawning in the caves and ive server hopped all day and all the river caves have maybe 0-1 lumite stones throughout the entire thing, whether someone mined in it or not
i didnt have this issue yesterday when i was farming for lumite, i was able to get around 40-30 or so with each trip
(yes i also checked the water for lumite)

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/165378541/7d823dc2-b5e2-4930-be39-053de11dc50c)

a video of me trying to find lumite:
https://youtu.be/Ve-fi3z280I

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by DanielTheRealer** [comment]
nvm my luck jus sucked balls today >_<

**Comment by RedstoneRelic** [comment]
It does take forever to respawn in, anytime I want lumite I need to go to a solo server because theres just never any there in public servers

**Comment by DanielTheRealer** [comment]
i was abt to say that solo servers werent working for me either
but when i tried again a few minutes ago the lumites were spawning normally again
i think this game jus wanted to give me a hard time to grind
