### ISSUE TITLE
[BUG]: Unanchored crate results in all items from it lost, flung.

### ISSUE THREAD

**Issue by Lilithienne** [typical-developers/oaklands-feedback#32]
I unanchored my crate where I left all of my valuable items. Which made stuff from it disappear, I found a rose and some other stuff near my base. Missing a pink teddy and some alpha gifts. Not asking for anything to get back. Just make sure to fix this so it doesn't happen again. Still feel sad though.

**Comment by LuckFire** [comment]
Please create an issue under the proper template.
