### ISSUE TITLE
[IMPROVEMENTS]:Makes the price of private servers cheaper

### ISSUE THREAD

**Issue by LetMeInnnnn** [typical-developers/oaklands-feedback#328]
### Roblox Username

aof0633

### What do you think can have quality-of-life improvements?

idk what this mean

### How do you think things can be improved?

Sometimes, normal servers will have a lot of lag due to players or other things. which is difficult to play And private servers are very expensive. You just lower the price to allow for a smoother experience for players.

**Comment by CyerraOaklands** [comment]
I strongly agree with this. Public servers = insanely laggy and kick me out if i go into them and make my stuff clip thru the floor. Solo Servers = Grinder servers, boring, cant play with friends. Private servers = the best way to play with your friends without all the unnecessary lag, can still be used as a grinder but you dont need to go thru a server to get to another its just right there, and you dont have annoying people to deal with like public servers do.

**Comment by LetMeInnnnn** [comment]
Oh, I didn't know there was a solo server, sorry :)

**Comment by CyerraOaklands** [comment]
Its alr but solo servers just get boring without friends

**Comment by HooferDevelops** [comment]
Private servers are currently a major source of our income, if we had alternative income strategies that allowed us to lower the price of private servers, we would consider this. For now, it's not viable for us.

**Comment by UsefullSpoon** [comment]
> Private servers are currently a major source of our income, if we had alternative income strategies that allowed us to lower the price of private servers, we would consider this. For now, it's not viable for us.

perhaps add a few gamepasses, i'm sure plenty of folks wanna spend some robux on some fancy perks they'll be getting. Such as a faster type of car or such.
