### ISSUE TITLE
[BUG]: Loose items have a chance of randomly flinging into the abyss

### ISSUE THREAD

**Issue by Lilithienne** [typical-developers/oaklands-feedback#33]
### Roblox Username

Lilithienne

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

I unanchored my crate where I left all of my valuable items. Which made stuff from it disappear (they all flung I think), I found a rose and some other stuff near my base. Missing a pink teddy and some alpha gifts. Not asking for anything to get back. Just make sure to fix this so it doesn't happen again. Still feel sad though, since I won that teddy on a giveaway in the dc server and wanted to keep it.

### Provide some images / videos of the issue in action.

don't have proof

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by CrimsonClaws** [comment]
I've had something similar happen to me twice, where I've had unanchored crates full of tools or jars disappear from my plot, even though I keep a fence around them. I've anchored my crates now, but it's annoying that I have to unanchor them when I want to take something out. I think 1.39.X has had problems with loose items being randomly flung in general.

**Comment by HooferDevelops** [comment]
We believe we have fixed this issue in 1.58.0 (pending).
