### ISSUE TITLE
[IMPROVEMENTS]: Flowers and Fruit So Profitable Economy Will Break

### ISSUE THREAD

**Issue by 0rangeChicken** [typical-developers/oaklands-feedback#333]
### Roblox Username

FloppyDolphins

### What do you think can have quality-of-life improvements?

Flower and Fruit Prices

### How do you think things can be improved? 

I have compiled a price list for every flower and fruit I have found so far. With the ease of access to all of these flowers and fruits, the game economy will be broken and wood will be useless to collect anymore once you get a flower press. I think the prices here need to go down significantly otherwise the entire game's economy will shift to fruits and flowers because they make so much.

**(Please see an extra comment below for price suggestions)**

Prices I found are her, per jar:
Pear Juice: 2000$
Apple Juice: 2000$
Banana Juice: 2000$
Lemon Juice: 3800$
Dragonfruit: 3800$
Cranberry Juice: 2000$

Daisy: 2000$
Red Tulip: 2000$ 
Purple Tulip: 2000$
Orange Tulip: 2000$ 
Green Tulip: 2000$ 
Blue Hydrangea: 2000$
Pink Hydrangea: 2000$
White Hydrangea: 2000$
Sunflower: 2000$
Marigold: 2000$
Green Cactus Flower: 2000$

**Comment by CyerraOaklands** [comment]
Yep, were screwed. You have just killed our economy. CONGRATS ON BEING THAT ONE DUDE WHO REMINDS THE TEACHER ABOUT THE DUE HOMEWORK.

**Comment by polychromatizen** [comment]
Did you account only for the price? It costs $2000 for a jar and when you sell it is $2000, so no profit is being made? (the other stuff is only $1800 in profit)

**Comment by Yrukio** [comment]
No economy is dead you buy the jar 2000$ but it's reusable so you just have to farm flowers if you have enough jar you can do 200000$ in 1 truck

**Comment by polychromatizen** [comment]
Did not know the jar was reuseable... that is definitely breaking the economy

**Comment by 0rangeChicken** [comment]
No, not closed, oops

**Comment by 0rangeChicken** [comment]
Test

**Comment by 0rangeChicken** [comment]
New Price List Suggestion:

I think that while the prices should be reduced, they should also be adjusted for rarity and ease or difficulty of collection. Many of the items need a ladder to obtain. I noticed the price of the originals also were pretty similar. I think some more varied pricing would be nice. Here are my suggestions and reasons for: 

Adjusted Price Proposal
Pear Juice: $750 - Pears require a ladder to reach, and are more difficult.
Apple Juice: $500 - Apples are pretty easy to collect, and don't need a ladder.
Banana Juice: $250 - Bananas spawn in group of 15+. I think this would be a better price as they are pretty easy to make large amounts of juice with.
Lemon Juice: $1000 - Lemons are pretty hard to reach, even with a ladder sometimes, requiring climbing up the tree carefully.
Dragonfruit: $1250 - Dragonfruit is in more remote locations on the map, and is harder to find, so should I think have a high price.
Cranberry and other berry bush juice: $250 - Berry juice is very easy to collect, being at ground level, so I think should have it price slashed a lot to reflect this.



Daisy: $150 - Daisies spawn in the area with all of the plots and are very easy to collect. I think the price should go down significantly.

Red, Purple, Orange, and Green Tulips: $350 - These are in the flowery biome. They are remote, but come in quite large numbers once you get to them.

Blue, Pink, and White Hydrangeas: $500 - These are somewhat rarer, spawning on some bushes, but not as common as berries, so I think this is a fair price.

Sunflower: $250 - These are after the bridge if you go straight on the road past the Oak Store. Due to the amount of them, I feel this is a fair price - similar to Tulips.

Marigold: $750 - I haven't seen very many of these, they seem rare ish. I think this is a fair price.

Green Cactus Flower: $750 - These also seem fairly rare, so I think this is a fair price.

**Comment by OopsS34rus** [comment]
if this is implemented foraging update will die in few seconds

**Comment by 0rangeChicken** [comment]
> if this is implemented foraging update will die in few seconds

The prices are way too much right now. These prices would still make collecting fruit worth it, but you'd have to actually put in effort to make good money rather than just print it like you do now. Remember that these prices are per flower. If you have 40 tulips which is honestly pretty easy you'd still get 10,000$.

**Comment by OopsS34rus** [comment]
if prices should be reduced they should not be just worthless

**Comment by 0rangeChicken** [comment]
> you would need to also buy jars and a press machine, collect flowers/fruits, get them to your base then wait for them to be actually made into dye or jam. just jars are costly and im not talking about some flowers or fruits that are either hard to acquire or they are just far away like burning bloom or dragon fruit

You don't loose the jars, you get to re-use them. If you want to propose a set of different prices or upping them by a certain amount go ahead.

**Comment by 0rangeChicken** [comment]
Consider: You can fit 4, maybe 5 crates here with this setup. Go to the new biome, stuff them full of tulips, and close. Each flower is worth 2k per, you can fit like 40 in a crate. That's 80k per crate, multiplied by 4 or 5. This is insanely overpowered.

![RobloxScreenShot20240414_210039246](https://github.com/typical-developers/oaklands-feedback/assets/18521215/99f7e7d3-2aa4-4432-8082-2f3cd35b95a3)

![RobloxScreenShot20240414_210102628](https://github.com/typical-developers/oaklands-feedback/assets/18521215/2823d16e-98ba-4c81-9c39-e3dd65e39dd5)

![RobloxScreenShot20240414_210405467](https://github.com/typical-developers/oaklands-feedback/assets/18521215/23ea8553-a6d9-4f6e-aaab-0832f910691c)

**Comment by polychromatizen** [comment]
I used purple tulips and only got $450 so I think they've nerfed it!

**Comment by 0rangeChicken** [comment]
Prices have indeed been nerfed. The new prices are better, but I do not think the issue is fully resolved.

The new list is as follows:
(
(
FRUITS
(
Pear Juice: 1650$
Apple Juice: 1500$
Orange Juice: 1800$
Banana Juice: 300$
Lemon Juice: 1800$
Dragonfruit Juice: 2100$
Cranberry Juice: 1800$
Grape Juice: 1800$
Coconut Juice: 1800$
(
(
FLOWERS
(
Daisy: 450$
Red Tulip: 150$
Blue Tulip: 150$
Purple Tulip: 150$
Orange Tulip: 150$
Green Tulip: 150$
Blue Hydrangea: 600$
Pink Hydrangea: 600$
White Hydrangea: 600$
Purple Hydrangea: 600$
Lavender: 600$
Sunflower: 750$
Marigold: 750$
Green Cactus Flower: 1200$
Purple Cactus Flower: 1800$
(
(
(
(
Comments, fruits: Cranberries are worth way too much for the ease of access. Pears (and lemons) are harder to get, the price is fine. I think apples should go down 500 because of ease of access, and oranges down 600. Bananas deserved the price nerf, that feels fine. Dragonfruit juice - dragon fruit is actually pretty rare, maybe a price hike to 2500 would help. Grapes, like cranberries, sell for way too much given ease of access. Coconuts are fine.
(
(
Comments, flowers: Prices are pretty reasonable, aside from sunflowers; these are very easy to get in large amounts and should be maybe 250$ cheaper. I think.

**Comment by 0rangeChicken** [comment]
They have adjusted the prices down with the update for truck visuals. I think that the new prices I have observed are fine and fix the initial issues. I see no reason to keep this open.
