### ISSUE TITLE
[BUG]: We can clip into the ship

### ISSUE THREAD

**Issue by ManancialGD** [typical-developers/oaklands-feedback#34]
### Roblox Username

BrenoGamerBr205

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

We can clip into the ship, the video say for it's self

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/143729780/e4841b65-a7e7-4c09-aa3a-1dbb4b2d6b59

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by AkkozaDevelops** [comment]
Added a collision box to hull of ship

**Comment by ManancialGD** [comment]
> Added a collision box to hull of ship

Yooo! Jonathan is the beast!!!

**Comment by HooferDevelops** [comment]
> Added a collision box to hull of ship

No! This messes up collision on the entire ship
