### ISSUE TITLE
[BUG]: Alignment conveyors are not telepoorting items or aligning them

### ISSUE THREAD

**Issue by Nova-Sage** [typical-developers/oaklands-feedback#345]
### Roblox Username

@willzrulez

### What version did this issue occur in?

1.54.2

### Describe the issue in detail.

Items, when coming into contact with an alignment conveyor, are not teleporting or aligning to the middle of the conveyor.

### Provide some images / videos of the issue in action.

![RobloxScreenShot20240415_175308053](https://github.com/typical-developers/oaklands-feedback/assets/147571683/f99fb976-6762-4840-8b21-b2155033c28a)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by BuzzingSniper38** [comment]
Fixed in new servers, this is a duplicate bug
