### ISSUE TITLE
[BUG]: "inspect object" on blue button on vehicles does nothing

### ISSUE THREAD

**Issue by JackOfCool** [typical-developers/oaklands-feedback#36]
### Roblox Username

JackThePC_Overlord

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

The blue button next to the steering wheel on all vehicles has option to inspect object, and it does nothing. 

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/143646161/dbc23505-c5b8-4f7b-b648-309d3ee97f91)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by JackOfCool** [comment]
also its kind of weird that it just say vehicle, I would have it say the actual name of the vehicle

**Comment by ManancialGD** [comment]
Does nothing to me too
