### ISSUE TITLE
[BUG]: CAR LODGES ITSELF IN ROOF

### ISSUE THREAD

**Issue by ukuleleman** [typical-developers/oaklands-feedback#361]
### Roblox Username

L_Bios

### What version did this issue occur in?

1.54.3

### Describe the issue in detail.

your stupid latest update broke my spawner so now it just lodges itself in the roof

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/167048683/d67911f1-2aed-4a85-aa17-018e20cde842)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by ukuleleman** [comment]
You made it spawn higher than before. WHY???
There is ZERO BENEFIT

**Comment by LuckFire** [comment]
You're acting like this change was intentionally made for no reason and has no chance of being accidental while also reporting it as a bug.
