### ISSUE TITLE
[IMPROVEMENTS]: New vehicle models

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#368]
### Roblox Username

tupisupi

### What do you think can have quality-of-life improvements?

New vehicle models

### How do you think things can be improved?

Images and videos are attached in these messages in discord:
https://discord.com/channels/865737627712749579/894024102174658644/1230546134498283692
https://discord.com/channels/865737627712749579/894024102174658644/1230547211583230034
https://discord.com/channels/865737627712749579/894024102174658644/1230547371872489565

**Proportions:**
XYZ (length, height, width)

Old extended trailer volume in studs 20.5 x 3.5 x 6.75 = 484,3125 studs
New extended trailer size 19.5 x 3.25 x 7.25 = 459,46875 studs

Length and height is less on new extended trailer but it is wider than old extended trailer. Old extended trailer has more volume compared to new one. Old ones are better for grinding due to length and height making it easier to stack wood higher and it being able to hold more volume. See images.

**Respawning:**
Respawning new sellner causes it to appear really high up in the air which causes problems with setups. See video.

**Trailers:**
Trailers are really easy to flip compared to old variants. See video.

If you try to move a trailer that has another trailer attached to it, it just points upwards. This wasn't the case with old models. See video.

If you chain trailers to other trailers they are significantly angled instead of flat, IIRC this happened with old models but not to this extent, 2nd pair of wheels don't even touch the ground on new models due to this. See images:

Oh forgot to add that driving up hills is significantly more difficult with new models and almost impossible in plek cave due to rams being really steep.

Images and videos are attached in these messages in discord:
https://discord.com/channels/865737627712749579/894024102174658644/1230546134498283692
https://discord.com/channels/865737627712749579/894024102174658644/1230547211583230034
https://discord.com/channels/865737627712749579/894024102174658644/1230547371872489565

**Comment by HooferDevelops** [comment]
Going to close this as it's no longer relevant due to us completely redoing the models. Thanks for the feedback, we will keep it all in mind for when we redo.
