### ISSUE TITLE
[IMRPOVEMENTS]: Allow for Old Cars and New to Coexist

### ISSUE THREAD

**Issue by HDMICIDE** [typical-developers/oaklands-feedback#378]
### Roblox Username

HDMICIDE

### What do you think can have quality-of-life improvements?

The car models and the feelings towards them.

### How do you think things can be improved?

I believe that if you added an option on the car spawn pad where you can change your car to be the old model it would make everyone who dislikes the new cars happy, and it would make the car selection feel fuller and have more diversity. This prevents everyone from being forced into a change that quite a large amount of people are against. Below you can see the menu I'm mentioning it should be added to. 

![image](https://github.com/typical-developers/oaklands-feedback/assets/153624280/00ad5d99-f485-4ffa-a405-d53c0df685a8)

**Comment by HooferDevelops** [comment]
Not interested in maintaining two sets of vehicle models. It's time to adapt and move on.
