### ISSUE TITLE
[BUG]: goblin memorabilia is not displayed correctly

### ISSUE THREAD

**Issue by deadmenwalking** [typical-developers/oaklands-feedback#379]
### Roblox Username

olek8776

### What version did this issue occur in?

1.54.4

### Describe the issue in detail.

goblin is not showing on the platfrom for him 

### Provide some images / videos of the issue in action.

![Zrzut ekranu 2024-04-19 195217](https://github.com/typical-developers/oaklands-feedback/assets/167569499/182fccc3-a4f7-4de4-a19e-cc284acf1bb0)

### Before Submitting

- [ ] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
This is likely due to the asset failing to load on your client, which can be fixed with a rejoin. Not something we can control.
