### ISSUE TITLE
[BUG]: Boxed Tall gift doesnt save

### ISSUE THREAD

**Issue by JackOfCool** [typical-developers/oaklands-feedback#38]
### Roblox Username

JackThePC_Overlord

### What version did this issue occur in?

1.35.9 and previous

### Describe the issue in detail.

the boxed form of the tall gift doesnt save 

### Provide some images / videos of the issue in action.

n/a

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Imjustjokingwithya** [comment]
They save for me 🤷‍♂️

**Comment by JackOfCool** [comment]
> They save for me 🤷‍♂️

R u sure
I'm not talking about the gift form

**Comment by Imjustjokingwithya** [comment]
ohh

**Comment by AkkozaDevelops** [comment]
Tested, and this is true, currently looking into.

**Comment by AkkozaDevelops** [comment]
The issue has been found, and will be published in the next game patch

`fixed unboxing issue where type was not accounting for the gift's specified convert type.`
