### ISSUE TITLE
[IMPROVEMENTS]: Logic "Publicity" QOL Change

### ISSUE THREAD

**Issue by sourcedv** [typical-developers/oaklands-feedback#380]
### Roblox Username

SOURCED_V

### What do you think can have quality-of-life improvements?

Publicity on Switches - Tooltip Addition

### How do you think things can be improved?

When you hover over a button / switch, you can toggle publicity. You have no idea whether or not a button or switch is public, so it should either show on the tooltip itself, or you can use the Statistic Tool to see whether or not it's public.

**Comment by HooferDevelops** [comment]
![image](https://github.com/typical-developers/oaklands-feedback/assets/60201971/cc7af8ef-9446-4e13-9fed-d48a76c5d0ee)
