### ISSUE TITLE
[IMPROVEMENTS]: Toggle Schematic Fill

### ISSUE THREAD

**Issue by sourcedv** [typical-developers/oaklands-feedback#381]
### Roblox Username

SOURCED_V

### What do you think can have quality-of-life improvements?

The ability to toggle whether or not a schematic should be filled in at any given point.

### How do you think things can be improved?

When I'm building, I typically have schematics in close vicinity or close to eachother, see image below.
![image](https://github.com/typical-developers/oaklands-feedback/assets/49532251/4d73205b-7cac-4f4b-acf9-87f2f872ff95)

This is obviously a simple example, but in 50% of the cases, materials get caught and placed in the wrong schematic. It'd be cool if you could hover over a schematic and toggle to disable filling.

**Comment by sourcedv** [comment]
![image](https://github.com/typical-developers/oaklands-feedback/assets/49532251/9efa4b4a-4707-4e3e-a979-c2979fb8c707)

**Comment by HooferDevelops** [comment]
We're working on a tool that will be out in a future update that should address this concern.
