### ISSUE TITLE
[IMPROVEMENTS]: "Despawn" button on vehicles.

### ISSUE THREAD

**Issue by sourcedv** [typical-developers/oaklands-feedback#386]
### Roblox Username

SOURCED_V

### What do you think can have quality-of-life improvements?

Add a "Despawn" button on vehicles.

### How do you think things can be improved?

![image](https://github.com/typical-developers/oaklands-feedback/assets/49532251/2c72ff12-8177-4e4a-a683-f2d5966d67b9)

It would be nice to despawn vehicles either by despawning off of the vehicle itself, or from the spawner. It's a little tedious having to move around vehicles when they're not in use, even when respawned.

**Comment by HooferDevelops** [comment]
Good suggestion, you can also replace the spawn pad in build mode to despawn them, but I think there should be a native way as well.

**Comment by sourcedv** [comment]
> Good suggestion, you can also replace the spawn pad in build mode to despawn them, but I think there should be a native way as well.

Would be appreciated if this applied to trailers as well
