### ISSUE TITLE
[BUG]: Attaching a trailer while driving does not reduce speed.

### ISSUE THREAD

**Issue by TheReff** [typical-developers/oaklands-feedback#39]
### Roblox Username

DaRefff

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

The easiest way to replicate this bug is by attaching two trailers together, they should stay level with the truck's hitch, and then reverse into the trailer with the truck. No speed reductions will be applied until after you exit the truck, but this bug can be replicated anywhere so I doesn't really matter. 
 I have only tested this with the Sellner and two extended trailers, but I'd assume this works with X amount of trailers. Doesn't really effect gameplay in a negative way, just something to be noted.

### Provide some images / videos of the issue in action.

Clip demonstrating the bug:
https://youtu.be/-njDqTJjwZI

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by SunnyFloppyDiskStudios** [comment]
i think that's normal

**Comment by Azytrx** [comment]
I can confirm this works on 10+ extended and/or normal trailers

**Comment by KinderDeveloper** [comment]
Thanks to @AkkozaDevelops this was patched in a previous version, but it seems to've been undone since the port of the new UI update. This was a common problem with a lot of the features added during the UI update, since we worked on the game in two separate sub places and had to manually port over the code.

I tried adding this fix back, but never could find what Akkoza actually did to fix it. Any comment regarding the solution @AkkozaDevelops ?

**Comment by AkkozaDevelops** [comment]
> Thanks to @AkkozaDevelops this was patched in a previous version, but it seems to've been undone since the port of the new UI update. This was a common problem with a lot of the features added during the UI update, since we worked on the game in two separate sub places and had to manually port over the code.
> 
> I tried adding this fix back, but never could find what Akkoza actually did to fix it. Any comment regarding the solution @AkkozaDevelops ?

When I get home later I'll reimplement the fix, as it seems important due to the fact people can pull 10-20 trailers of Mysterious Mush with them at a time.
