### ISSUE TITLE
[IMRPOVEMENTS]: 

### ISSUE THREAD

**Issue by InvertedReaIity** [typical-developers/oaklands-feedback#40]
### Roblox Username

InvertedReaIity

### What do you think can have quality-of-life improvements?

Switching between plots while in-game.

### How do you think things can be improved?

Having the ability to switch between saves while not having to rejoin would be really helpful.

**Comment by JackOfCool** [comment]
I think they haven't done this bc it could introduce dupes

**Comment by Imjustjokingwithya** [comment]
> I think they haven't done this bc it could introduce dupes

This is true and has been confirmed in the past.

**Comment by LuckFire** [comment]
As others have stated, we do not plan to have this as a feature because it adds the risks of dupes.
