### ISSUE TITLE
[IMPROVEMENTS]: Add hotbar dragging

### ISSUE THREAD

**Issue by artz144** [typical-developers/oaklands-feedback#41]
### Roblox Username

chechyva

### What do you think can have quality-of-life improvements?

Bring back hotbar dragging as it can help players sort tools in their inventory for easier access.

### How do you think things can be improved?

I understand that this feature was previously added twice but was removed due to issues with duping and item loss. However, this useful feature shouldn't be scrapped. My suggestion is to first introduce this feature on the public beta test server in order to find any potential bugs it may have before adding this into the game.

**Comment by LuckFire** [comment]
We want to revisit it in the future, likely with the testing sessions we plan to do so we can properly tackle any issues it may have before pushing it to a public build.
