### ISSUE TITLE
Im sorry

### ISSUE THREAD

**Issue by DragonMcHun** [typical-developers/oaklands-feedback#422]
### Roblox Username

DragonMcHun

### What version did this issue occur in?

Uncertainty Cave

### Describe the issue in detail.

It happend a long time ago. My account got hacked my password got changed (i was younger and i dont knew how to secure my account) i got a new password and i saw games i played in the past were on my home page. I joined almost every game was ruined or banned for weeks and oaklands too... but not for a few weeks. I dont have idea what to do nobody helping me fix it i just dont know what i should do. I had a lot of progress already and i really enjoyed the game. Im sorry this doesnt happens now cus i know how to secure my account

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/66668430/c1e274b0-e542-4fbd-8871-1c7d48243469)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Elliottgamer432** [comment]
seems legit
