### ISSUE TITLE
[IMPROVEMENTS]: Lightning Volume

### ISSUE THREAD

**Issue by Azytrx** [typical-developers/oaklands-feedback#43]
### Roblox Username

AlexBunnyyy

### What do you think can have quality-of-life improvements?

Lightning Volume Control

### How do you think things can be improved?

The volume of lightning should be controlled by the Miscellaneous slider inside the audio options

**Comment by LuckFire** [comment]
This doesn't really fall under an "improvement" since it's a bug that the audio doesn't apply to sound effects (it wouldn't be under misc). It would be fixed in next, but we're unable to push any new updates out at the moment since we're working on other things.

**Comment by Azytrx** [comment]
Ah okay, I wasn't aware that was the plan, thank you
