### ISSUE TITLE
[IMPROVEMENTS]: Ability to change between saves easier

### ISSUE THREAD

**Issue by TheeCorrupted1** [typical-developers/oaklands-feedback#45]
### Roblox Username

TheCoruptedOneAlt

### What do you think can have quality-of-life improvements?

Being able to swap between plots

### How do you think things can be improved?

just have a button that makes you leave the game and instantly rejoin the server you were in. (Kinda like the shutdown thing that u have)

**Comment by LuckFire** [comment]
Adding a button to instantly rejoin would be a nice touch, though I'm not sure if it's possible to make it rejoin you into the server you were just in (@HooferDevelops would have to chime in and confirm).

**Comment by LuckFire** [comment]
Also, I guess I misunderstood this request at first, I'm assuming you want it specifically so you can rejoin the server and choose a different property to load on? Or was I correct about changing between save slots?

**Comment by HooferDevelops** [comment]
You could make it rejoin same server (I think, idk) but if someone gets in before you, you are out of luck.

This also would not work for private servers / solo servers at all.

**Comment by LuckFire** [comment]
> solo servers at all 
Aren't you able to check if it was redirected from a one-player server and just automatically redirect to a solo server?

**Comment by KinderDeveloper** [comment]
> Are you able to check if it was redirected from a solo server and just automatically redirect to a new one?

You could do that quite easily, but it feels kind of strange that private servers just flat out wouldn't work.

**Comment by HooferDevelops** [comment]
Yeah, solo servers is an easy solution, but private servers has no possible solution.

**Comment by torrensstuff** [comment]
You could try to add a "back to menu" option in the settings that will take you back to the menu, save the game, & erase all loose items that are not on your plot, similar to just leaving and rejoining except without the hassle. It might even be easier to code but I don't know jack about coding so don't hold me to that.

**Comment by LuckFire** [comment]
We don't want to add that sort of thing since it increases the amount of potential dupes people could do. We rather have poor QoL when it comes to the save selection (where you have to rejoin every time you want to choose a new save) compared to risk any dupes that we may not even know how to fix.

**Comment by HooferDevelops** [comment]
There may be a way to safely clean up player data, but I'm not sure still.

**Comment by HooferDevelops** [comment]
Going to close this as discussion has not continued.
