### ISSUE TITLE
[BUG]: Mushroom cap and clover leafs can fill up alot of scematics

### ISSUE THREAD

**Issue by bacosmatic** [typical-developers/oaklands-feedback#451]
### Roblox Username

Aldric12112012

### What version did this issue occur in?

1.54.6

### Describe the issue in detail.

So went i was messing around with a friend i found a bug with caps and clover leafs i accidently placed a cap on a scematic and it filled 50k %

### Provide some images / videos of the issue in action.

![Uploading Screenshot (1924).png…]()

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by UsefullSpoon** [comment]
screenshot failed

**Comment by uhhhhhhhhhhhhhhhh58** [comment]
this seems intentional
