### ISSUE TITLE
[BUG]: Jump button while on vehicle (mobile)

### ISSUE THREAD

**Issue by VFGemink** [typical-developers/oaklands-feedback#456]
### Roblox Username

VICKY_827

### What version did this issue occur in?

1.54..6

### Describe the issue in detail.

This issue actually happen in a few version ago, before that this bug were almost never happen, it does happen but less likely. But now it is guarantee to show jump button while driving

Reason this need to be fixed is whenever I(or other people that use mobile device) drive and accidentally clicking jump button while having something on truck, some of them will fall off and in some cases also not stackable again because the stack on truck already messed up

### Provide some images / videos of the issue in action.

`
![Screenshot_20240427-141234_Roblox](https://github.com/typical-developers/oaklands-feedback/assets/168281597/3fbc9ac8-c3d0-4d8a-bd9f-efc2320189b0)
`

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by hokies4life06** [comment]
I have tested this in the past, I do believe it only occurs when you have the scooba tank equipped.
