### ISSUE TITLE
Music notes play sound when switch is turned off, in different pitch

### ISSUE THREAD

**Issue by GalaxyMan77** [typical-developers/oaklands-feedback#477]
### Roblox Username

Galaxyboss777

### What version did this issue occur in?

1.54.8

### Describe the issue in detail.

Whenever you connect a music note to a switch to play sound, it plays both when you turn it ON, as well as when you turn it OFF, but in a different transposed pitch. I don't know why this happens, as music notes should not play sound when they have 0 power. I believe it is due because the music note needs to have power connected from a number interface to be assigned a pitch, but when the switch is also connected, it messes with the pitch. I would like it to only play sound when turned ON, and play no sound when turned OFF, even if it is connected to a number interface. The music note should prioritize the input power over the number interface. 

### Provide some images / videos of the issue in action.

You can see here how the song plays correctly when powered on, but sounds distorted when powered off. It is a bit laggy however, and has its timings a little off. Here I show what it is like with the switch and the button. 

https://github.com/typical-developers/oaklands-feedback/assets/168718097/17b3ab10-ad62-41dd-8397-827a85df8493

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HDMICIDE** [comment]
so youre kinda just misusing the logic, there is no bug, what youre reporting is due to the fact that theres always a current from the num interface, then youre adding to it, then when it goes back down, it plays another because its not at 0, it goes back to whatever the num interface is set to. theres ways around this, you might have to spend more on logic though

**Comment by GalaxyMan77** [comment]
Thanks for explaining that. I will take this down then.
