### ISSUE TITLE
[BUG]: Floord Putter keeps BRRRTing

### ISSUE THREAD

**Issue by ukuleleman** [typical-developers/oaklands-feedback#480]
### Roblox Username

L_Bios

### What version did this issue occur in?

1.54.8

### Describe the issue in detail.

Floord Putter has misaligned wheels so it has a jittery pattern

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/167048683/39fc8186-ff61-4b9c-94a9-00b3d60e2f85

https://github.com/typical-developers/oaklands-feedback/assets/167048683/5c5702f4-3b53-4753-afcc-bedafc76d0b7

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HDMICIDE** [comment]
im pretty positive thats intentional

**Comment by LeonThe-Professional** [comment]
I'm pretty sure as well, it's always done that since I've started playing

**Comment by HooferDevelops** [comment]
This was only supposed to happen with the rusty variant.
