### ISSUE TITLE
[BUG]: Steel Planker can "refine" Plek and Magma trees

### ISSUE THREAD

**Issue by Redisps** [typical-developers/oaklands-feedback#485]
### Roblox Username

VisualMT

### What version did this issue occur in?

1.54.8

### Describe the issue in detail.

When refining sanded Plek or Magma trees, you can turn them into planks by using a Steel Planker instead of its industrial counterpart, thus rendering it useless.

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/120352904/68ae2855-26d6-4b69-9007-9462534e2c85

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HDMICIDE** [comment]
Yeah the only difference is supposed to be thinner and wider planks from industrial. up to 4x4 vs 5x5
