### ISSUE TITLE
[BUG]: Emberbane axe will bug trees that have been hit several times.

### ISSUE THREAD

**Issue by FuyNick** [typical-developers/oaklands-feedback#49]
### Roblox Username

Fuy_Nick

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

When you cut a tree with the emberbane axe, it does multiple hits. Even though this is probably a feature, it bugs the tree and makes the game think that the tree has spawned in but it's unanchored. Basically, sometimes you can't drag the tree after cutting it with the emberbane axe.

### Provide some images / videos of the issue in action.
Here is the url for evidence:
https://youtu.be/2e7Pp32whhU

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by AkkozaDevelops** [comment]
https://github.com/typical-developers/oaklands-feedback/issues/52#issuecomment-1709381041
