### ISSUE TITLE
[BUG]: anticheat ban

### ISSUE THREAD

**Issue by stasyk22** [typical-developers/oaklands-feedback#498]
### Roblox Username

stasyk2_0

### What version did this issue occur in?

1.54.8

### Describe the issue in detail.

I played with cheats on another account (not in oaklands) and on a new account (stasyk2_0) I didn't even open the injector, but I was banned, please help me

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/114261364/34a95ac5-baa8-425d-8e53-7263754ed2f0)

### Before Submitting

- [ ] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by stasyk22** [comment]
can I use an alt account?

**Comment by HDMICIDE** [comment]
i mean theres nothing stopping you from playing on an alt and playing 100% legitimately

**Comment by NotHammer043** [comment]
First time playing the game cuz my friend recommended it to me and i completely forgot to unload so it ran all of my autoexec and got banned instantly lol need help
