### ISSUE TITLE
[BUG]: purple surfboard has black box on texture

### ISSUE THREAD

**Issue by JackOfCool** [typical-developers/oaklands-feedback#5]
### Roblox Username

JackThePC_Overlord

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

Texture on the back of the purple flower surfboard has a black box

### Provide some images / videos of the issue in action.

![Screenshot_20230830-1423442](https://github.com/typical-developers/oaklands-issues/assets/39076891/01eaef72-7dd7-4321-b75f-bce362eccbae)

### Before Submitting

- [x] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by AkkozaDevelops** [comment]
Not really a bug, just how the texture worked out, wont be fixed unless Shurikeno _wants_ to fix it.

**Comment by KinderDeveloper** [comment]
What do you mean? That's where the rocket booster is, silly 🚀
