### ISSUE TITLE
[BUG]: Large hole leading under the map

### ISSUE THREAD

**Issue by tornado-tube** [typical-developers/oaklands-feedback#519]
### Roblox Username

tornadotube

### What version did this issue occur in?

1.55.3

### Describe the issue in detail.

In the path to the tower to place the mushroom for the petalfall, there's a large hole that leads to the underside of the map. It's also between the path up, making it more difficult to cross without losing the mushroom. I found this issue on a private server.

### Provide some images / videos of the issue in action.

![RobloxScreenShot20240511_113211886](https://github.com/typical-developers/oaklands-feedback/assets/99630906/8b34041e-863b-45ed-acd2-32f6d3220724)
![RobloxScreenShot20240511_113248401](https://github.com/typical-developers/oaklands-feedback/assets/99630906/e427586a-ab51-44de-8aab-07b1892fadbb)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Paperfox204** [comment]
Clone of #510
