### ISSUE TITLE
[BUG]: Chopping tree sometimes does not set a primary part

### ISSUE THREAD

**Issue by AkkozaDevelops** [typical-developers/oaklands-feedback#52]
### Roblox Username

Akkoza

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

There is a rare chance that when you chop a tree it will not assign a primary part, causing Dragger to error and Grabbers aswell.

This can be "fixed" by chopping the tree again and it will assign a primary part.

### Provide some images / videos of the issue in action.

Following is errors from Dragging, which is from trying to find the PrimaryPart.
`...Object.PrimaryPart:GetConnectedParts()...`

![Dev Console Error](https://cdn.discordapp.com/attachments/1131349576746545245/1148356326070689884/image.png)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by InvertedReaIity** [comment]
I can confirm this is true. I’ve especially had it happen when chopping Red Cactus.

**Comment by AkkozaDevelops** [comment]
Tree Regen being rewrote, and will fix this issue.
