### ISSUE TITLE
[BUG]: Not recieved items when bought 

### ISSUE THREAD

**Issue by Kristupas122** [typical-developers/oaklands-feedback#522]
### Roblox Username

@Krisolo009

### What version did this issue occur in?

1.55.3

### Describe the issue in detail.

Purchased headlamp and refined scuba did not recieve

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/160326074/09643606-c30d-41db-81f7-ad2b038f7cf3)
![image](https://github.com/typical-developers/oaklands-feedback/assets/160326074/d80bb2e4-cb8e-4bae-875d-ba76ba1bf2e9)
![image](https://github.com/typical-developers/oaklands-feedback/assets/160326074/3e2552a1-21d0-4bdc-a381-c7135b516307)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by UltrasBlade** [comment]
answered in discord
![image](https://github.com/typical-developers/oaklands-feedback/assets/143657573/ca775628-6128-4d1f-9bbd-fb94c393e6a8)
