### ISSUE TITLE
[BUG]: Storage Drawer drops all items when an interactor uses it

### ISSUE THREAD

**Issue by throwaway20000** [typical-developers/oaklands-feedback#524]
### Roblox Username

Illbiteyourskinoff

### What version did this issue occur in?

1.55.3

### Describe the issue in detail.

When an interactor uses a storage drawer it instantly drops all the items stored inside
I'm not sure if this is intended, but I feel like it should only drop a single item per signal to make it identical to a player interacting with it

In my example I have a switch connected to an interactor which is placed to interact with the storage drawer
The storage drawer has 9 planks inside and when I turn the switch on they all drop instantly instead of a single plank dropping

This also occurs with any other signal 
(I've tested commanders, frequency signals, and buttons)

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/169598183/7f015bcd-ce57-4dce-a3e4-5ec99c556dce

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by fawaz-rizky** [comment]
As the drawer's description said, the amount of dropped items when you're using interactor is depends on how much the power is (1-10). This is not a bug, it's simply how that works. You have 9 items in the crate while commanders, frequency signals, and buttons, are all outputting 10 power, hence why it dropped all your items. You have to set 1 power to the interactor if you want to drop it one by one.

**Comment by throwaway20000** [comment]
thanks my bad lol i didnt read it just guessed
