### ISSUE TITLE
Gaping Hole in the tamed mushroom cave for the petalfall quest

### ISSUE THREAD

**Issue by BurntThighHighs** [typical-developers/oaklands-feedback#529]
### Roblox Username

Mahirozgu

### What version did this issue occur in?

1.55.3

### Describe the issue in detail.

Okay, so, I was going to the mushroom donation part of the quest, when there was this hole in the cave?? I just assumed it was a part of the challenge and just tried to get past it but fell into it, and realized it's basically an opening to the entire cave system of the game and i think it wasnt intended to be like this.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/169612940/733d5995-fec2-474a-b829-ff66d1a6601a)
![image](https://github.com/typical-developers/oaklands-feedback/assets/169612940/ae705dde-1ac6-44c3-a88c-1ab07a46d04a)
![image](https://github.com/typical-developers/oaklands-feedback/assets/169612940/645c5246-1ce3-4c10-8494-d1c5e65fbbde)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Paperfox204** [comment]
Clone of #510
