### ISSUE TITLE
[IMPROVEMENTS]: Indicator in the description of the rocket launcher that specifies that it doesn't shoot explosives

### ISSUE THREAD

**Issue by UltrasBlade** [typical-developers/oaklands-feedback#53]
### Roblox Username

awesomepuppydog3

### What do you think can have quality-of-life improvements?

Rocket Launcher's description

### How do you think things can be improved?

There needs to be an indicator in the description of the rocket launcher that it shoots confetti, as some people think it can shoot explosives.
Current description:
![image](https://github.com/typical-developers/oaklands-feedback/assets/143657573/63246821-3a91-437d-8317-da40b54f9c3b)

**Comment by KinderDeveloper** [comment]
Will update the Name to "Confetti Launcher" along with something in the description
