### ISSUE TITLE
Magma tree vanished repeatedly after few minutes later. [BUG]: 

### ISSUE THREAD

**Issue by Rafik350z** [typical-developers/oaklands-feedback#533]
### Roblox Username

Rafikhasan350z

### What version did this issue occur in?

1.55.3

### Describe the issue in detail.

1. Yesterday , Me and my 2 friend went to magma cave. i was cutting magma tree and dropped them from the up. my 2 buddy cutting them into pieces, loading them on our truck. my truck was the first. its Sellner explorer with Extended trailer. then they were loading their truck and trailer. after 30 minutes later they informed me that my whole truck got empty , like all the magma tree de spawned automatically.
1.2  then we reload again and realized half of magma tree vanished  from my friends (blue1rex) truck and trailer.
then we left the cave immediately.
1.3  we were roaming around, when blue1rex went back to his property he noticed half of his magma tree vanished again. 
2.   We got 4 magma tree from meteor . Loaded on my another friends truck ( 00FLORA003 ) . She just unload them on her property and left the game. when she rejoined us few hours later , she notice there was only 1 magma tree, rest of 3 missing.
3. today morning one of my other friend ( Hellboy_351 ) reported me that same thing happened to him also.
Please kindly check this issue . we worked hard for magma tree, if this happening continuously we loose our interest soon.  
Hope this will fixed soon and we can enjoy our magma tree hunting Adventure again .
Thank you 

### Provide some images / videos of the issue in action.

Sorry we didnt have any  chance to  record those moment  

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by fawaz-rizky** [comment]
I'm sure trees and ores have 30 mins despawn time, so it's not exactly a "bug". But I'm not sure whether it always despawn after 30 mins or after 30 mins not get interacted

**Comment by Rafik350z** [comment]
But before the day before yesterday , when big update came and before 1.55.3 , we ware more than 90 minutes and nothing despawned from our truck and trailer . 
And what about 1.2, 1.3, 2 ? that magma tree vanished from our property

**Comment by Rafik350z** [comment]
i got the reason  solution ,thanks
