### ISSUE TITLE
[BUG]: Meteorite sound volume doesnt match with master volume

### ISSUE THREAD

**Issue by Dimas-Saputra-Me** [typical-developers/oaklands-feedback#539]
### Roblox Username

UlangTahun

### What version did this issue occur in?

1.55.4

### Describe the issue in detail.

So, usually I have my master (music) volume on 5% or below. It works fine it decrease all the things to 5%

But then it occur a meteorite event with a loud sound of the meteor (I think the meteor sound doesnt match with the master/music volume). That's all I can explain, I will provide the details if needed

### Provide some images / videos of the issue in action.

Unfortunately I didn't record the gameplay at the time, I will edit this issue with a video if the meteorite event occur once again.

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Hm. All of the sounds for the meteor are assigned to the SoundGroup. I can't reproduce this issue.

**Comment by Dimas-Saputra-Me** [comment]
Nevermind, I think I found the problem.  I mistakenly thought there was only one main volume control labeled "music" all in one section. But now I see there are actually separate settings for "music" and "sound effects".
