### ISSUE TITLE
[BUG]: Stupid crates supposedly idk I'm too lazy to test (I hate crates I hate crates I hate crates) cause items to anchor outside of ur plot for whatever reason after 1.55.4 update.

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#543]
### Roblox Username

tupisupi

### What version did this issue occur in?

1.55.4

### Describe the issue in detail.

Title, basically unanchor an item in an anchored opened crate, put that item in ur truck, close the anchored crate back up, drive off ur plot, occasionally this should cause the item to anchor whenever you drive off your plot with the only way of unanchoring it being rejoining and enclosing the items in a crate.

I've had this happen twice to me and saw someone else experience this, see https://discord.com/channels/865737627712749579/894303588556357692/1239615482668253266

### Provide some images / videos of the issue in action.

https://cdn.discordapp.com/attachments/894024102174658644/1239877834189832222/Stupid_Anchor_Crate_Bug1.mp4?ex=664485b7&is=66433437&hm=154a3b8c5aa24e9efce9a25f4193111b477f8a41155b23b758a858e96b6e700c&

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
This was not related to crates, but another issue that is now resolved.
