### ISSUE TITLE
[BUG]: Floor Missing during Petalfall

### ISSUE THREAD

**Issue by Kazeneo** [typical-developers/oaklands-feedback#548]
### Roblox Username

oKazetio

### What version did this issue occur in?

1.55.4

### Describe the issue in detail.

During the Petalfall quest, part of the floor is missing when the user is meant to go inside the cave and place the mushroom flower inside the tower. Where the small piece of pink roof is laying on the ground the user climbs up inside a little cavern, during their adventure into the section above this part there is a chunk of the floor missing.

### Provide some images / videos of the issue in action.

![Screenshot 2024-05-14 143406](https://github.com/typical-developers/oaklands-feedback/assets/134341841/44408d2c-e667-41cc-bca3-a4799e65d862)
![Screenshot 2024-05-14 143426](https://github.com/typical-developers/oaklands-feedback/assets/134341841/44adfc53-c944-42fd-9124-0c1b1429debe)
![Screenshot 2024-05-14 143440](https://github.com/typical-developers/oaklands-feedback/assets/134341841/f7395513-8bdf-4ed3-8e76-4c4780c05105)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Paperfox204** [comment]
Clone of #510
