### ISSUE TITLE
[BUG]: Magma Wood and Saw

### ISSUE THREAD

**Issue by MayoIsTaken** [typical-developers/oaklands-feedback#549]
### Roblox Username

IDont_HaveAdmin

### What version did this issue occur in?

1.55.4

### Describe the issue in detail.

Sorry I am new, but I got some magma wood and when I hover my saw over it with my steel saw and it says it needs reinforced one, but I am sawing it easily with a steel saw. Just something I noticed. Thank you for the great game so far, I am enjoying it alot :). I am sorry if anyone else has already reported this, I havent ever used github? im sorry if i am wasting your time, I saw one report about it but it was the sawmill not the saw itself.

### Provide some images / videos of the issue in action.

![Screenshot 2024-05-15 070757](https://github.com/typical-developers/oaklands-feedback/assets/169904587/f6ab1cb4-3c9a-4d0c-9544-b91fff2db2b6)
![Screenshot 2024-05-15 070746](https://github.com/typical-developers/oaklands-feedback/assets/169904587/5804e4e8-083d-45df-a5b8-4527a757b137)
![Screenshot 2024-05-15 070731](https://github.com/typical-developers/oaklands-feedback/assets/169904587/868f9e05-9002-40c3-be6b-79825680f060)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
This one was quite funny, I forgot to actually check if they were able to saw, thanks!
