### ISSUE TITLE
[BUG]: The game hangs at any moment

### ISSUE THREAD

**Issue by helloinchik7777** [typical-developers/oaklands-feedback#551]
### Roblox Username

helloinchik7777

### What version did this issue occur in?

1.55.4

### Describe the issue in detail.

The game hangs at any time, at first I thought it was because I have a lot of wood, but even if I go very far away from the base, it lags the same, fps drops to 15 or even 2 fps.When I played before version 1.55.0 it was all normal. 

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/169542281/fdbdf64c-0da2-49c2-803c-b5793e94bcc0

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
Same to me, it even crashed other programs, might be memory leak

**Comment by helloinchik7777** [comment]
How can you get rid of the problem? Or just wait until it is fixed?
