### ISSUE TITLE
[IMPROVEMENTS]: Simplify Collisions for all Structures and Items

### ISSUE THREAD

**Issue by HooferDevelops** [typical-developers/oaklands-feedback#56]
### Roblox Username

HooferBevelops

### What do you think can have quality-of-life improvements?

The collisions of all structures and items can be improved upon.

### How do you think things can be improved?

Right now, all structures and items have very complex multi-part collisions. This is evident in machinery, conveyors, vehicles, and more. Adding invisible boxes to replace the collision and disabling all queries possible for the complex parts may heavily help with physics performance. When throwing mass amounts of planks / ores / trees on conveyors, the server lags BADLY. This may be why!

![image](https://github.com/typical-developers/oaklands-feedback/assets/60201971/ed3bee44-3e5c-4f22-97eb-a4932e47cde2)
![image](https://github.com/typical-developers/oaklands-feedback/assets/60201971/28f26a0e-2289-419c-9821-95c9a516ffe8)

**Comment by Imjustjokingwithya** [comment]
Feel free to test this out on the best factory in the game *cough cough* from the one and only tupisupi 😁😁😁👍👍👍
