### ISSUE TITLE
[BUG]: Error code 600 / This account is prohibited from accessing this experience

### ISSUE THREAD

**Issue by Dovdas89524** [typical-developers/oaklands-feedback#567]
### Roblox Username

gamestoplayfun

### What version did this issue occur in?

newest (cant see)

### Describe the issue in detail.

So it says: This account is prohibited from accessing this experience and on the bottom Error code 600

### Provide some images / videos of the issue in action.

https://cdn.discordapp.com/attachments/1224731926678605906/1243081850935578695/image.png?ex=66502db0&is=664edc30&hm=4964d713ac8071375cd1471ba6b101538d264b0dd4bc3168097a8d734c066180&

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by LuckFire** [comment]
This means you are banned from the game.

**Comment by Dovdas89524** [comment]
what did i do??????

 i littelely played yesteday why did i get banned for no reason??????
