### ISSUE TITLE
[BUG]: Resources get 0.01 studs smaller everytime you output them from a storage drawer: trees, rocks, ores.

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#569]
### Roblox Username

tupisupi

### What version did this issue occur in?

1.55.5

### Describe the issue in detail.

Title

### Provide some images / videos of the issue in action.

https://cdn.discordapp.com/attachments/894024102174658644/1243190479772979250/RobloxPlayerBeta_5GPm2bRu5I.mp4?ex=665092db&is=664f415b&hm=a2ffd67d4b3908d9ca0f35d05c452901b49b75cd64c22b0e1418ce4bf5d7599d&

https://cdn.discordapp.com/attachments/894024102174658644/1243190685377757245/RobloxPlayerBeta_Ch2iZbcalA.mp4?ex=6650930c&is=664f418c&hm=463b3c81a9df4f7822b01c0a685548e0d807341540b6a6799cfa2e7a6f9e605f&

used keyword smaller. storage drawer and resource to search for duplicates

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Discord attachments do not work here anymore, as they expire. This is likely due to resources rounding down the amount of decimals for their sizes. This is intended behavior.
