### ISSUE TITLE
[IMPROVEMENTS]: Remove collison from the skirt of borderless conveyors like you (Kinder) promised 🙏🙏

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#57]
### Roblox Username

tupisupi

### What do you think can have quality-of-life improvements?

Remove collison from the skirt of borderless conveyors like you (Kinder) promised 🙏🙏

### How do you think things can be improved?

Link to #oak-news post where said thing was mentioned:
https://discord.com/channels/865737627712749579/894303481421262923/1127712850912223242
Quote:
> Both would have the exact same bounding box, and the only collideable part of the conveyor would be the velocity piece! @📝 Polls
Screenshot:
![kuva](https://github.com/typical-developers/oaklands-feedback/assets/96913351/5a150529-4772-49d5-9271-f1764622d594)

This is a bug as it is not working as intended/promised :bleh:
Thank you developers!

**Comment by KinderDeveloper** [comment]
alr

**Comment by Imjustjokingwithya** [comment]
Thank you Kinder ❤️ 👍
