### ISSUE TITLE
[BUG]: Error code 600

### ISSUE THREAD

**Issue by Streetyzzz** [typical-developers/oaklands-feedback#570]
### Roblox Username

Ducky101211

### What version did this issue occur in?

Unsure

### Describe the issue in detail.

I haven't played the game for a few days, but when I got on today there's a message saying "Error code 600 " But the thing is I haven't done anything wrong, can I have some help please ?

### Provide some images / videos of the issue in action.

![image_2024-05-24_181041089](https://github.com/typical-developers/oaklands-feedback/assets/170710728/e3605ad4-f427-4740-9bbe-e28c9995b366)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by berni1212** [comment]
This is not a Bug its the New ban system from Roblox. You have an ALT account what was used to Cheat in any other Game on Roblox. thats why you got banned. You need to know the account name without it you have no chance to get unbanned atm.

![Anticheat](https://github.com/typical-developers/oaklands-feedback/assets/34841220/e058c023-890c-46bc-b7d1-35fa3506c271)

**Comment by Streetyzzz** [comment]
Well I have found the account that was used for it, is there any chance I can appeal ?

**Comment by berni1212** [comment]
Join the Official game discord and Message Doofer (lehoofer) with the banned account. It will take some time but you should get unbanned [Offical Discord](https://discord.gg/typical)
