### ISSUE TITLE
[BUG]: Prohibited from joining 

### ISSUE THREAD

**Issue by Scyvre** [typical-developers/oaklands-feedback#572]
### Roblox Username

Kingofpiecedev

### What version did this issue occur in?

1.55.5

### Describe the issue in detail.

I can't access the game and i know the problems but. It's been many days I've been asking the moderation to unban me from the experience. But they still doesn't reply me, I've been tagging alot but still no response. Thanks 

### Provide some images / videos of the issue in action.

![Uploading Screenshot_2024-05-25-01-56-28-264_com.roblox.client.jpg…]()

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by berni1212** [comment]
Did you do the Requested things?
DM doofer with the ALT account what got banned for cheating and your main account?
