### ISSUE TITLE
[BUG]: Grabbiest Grabber animations are not set correctly

### ISSUE THREAD

**Issue by ProGamerDoggo** [typical-developers/oaklands-feedback#58]
### Roblox Username

ProGamerDoggo

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

When the grabbiest grabber is not holding anything, it uses the grabbing animation instead of the idle animation, and when its holding something it uses the idle animation instead of the grabbing animation.

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/144557370/afd84c84-f86d-42d0-a6e8-a86551da8624

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by KinderDeveloper** [comment]
I don't know why it took us so long to get to this report, haha! All done
