### ISSUE TITLE
[BUG]: Pressure Pads

### ISSUE THREAD

**Issue by Jaspingo** [typical-developers/oaklands-feedback#584]
### Roblox Username

UnknownPjs

### What version did this issue occur in?

1.56.0

### Describe the issue in detail.

A pressure pad can be activated through doors, including sliding doors. 
Trying to create a mechanism in which a pressure pad will appear if there is no vehicle blocking a laser using a sliding door. 

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/171175636/e6a5f5fb-97e9-4d03-a2f5-acfd73cb57e2

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HDMICIDE** [comment]
just put the pressure pad lower, in the ground if you have to, it has a hitbox and youre still hitting it, most likely your car is spawning inside of it aswell then deactivating when your car reaches its final spot

**Comment by HooferDevelops** [comment]
This is considered intentional behavior.
