### ISSUE TITLE
[BUG]: Dye machine indicators desynced

### ISSUE THREAD

**Issue by Samuel-StitchedDev** [typical-developers/oaklands-feedback#586]
### Roblox Username

StitchedDev

### What version did this issue occur in?

v1.56.1

### Describe the issue in detail.

The indicators for the press and dye machine are completely incorrect after using them. They don't go down enough, so become desynced. In the image, there is **no** dye and **no** jars in the machines, yet it says there is. Hitting the eject button fixes this, but of course ejects stuff that is in there.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/167721193/32971be5-2079-4960-a5fa-89da17880c07)
![image](https://github.com/typical-developers/oaklands-feedback/assets/167721193/1da0207c-a490-49b0-9128-fb3d214c48dd)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by SniperOnSunday** [comment]
I was just about to make a post on this, but yeah, this is a common problem.
