### ISSUE TITLE
[BUG]: The account has been blocked

### ISSUE THREAD

**Issue by ivvhgc** [typical-developers/oaklands-feedback#587]
### Roblox Username

sojxie6666

### What version did this issue occur in?

1.54.6

### Describe the issue in detail.

I don't know what I did wrong.My account was playing well a month ago, but after a month, I wanted to play it again, but I saw that my account was blocked.

### Provide some images / videos of the issue in action.

![Screenshot_2024-06-02-00-34-41-91_080032403b0f3d7ce099ec68649d222a](https://github.com/typical-developers/oaklands-feedback/assets/171444994/c3646b93-1a4c-443c-8324-34afd2e87c49)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
This is not a bug. You are correctly blocked from the game. This means that either:
a) you cheated on an alternative account
b) you cheated and are banned

Have a good day.
