### ISSUE TITLE
[BUG]: Animation doesn't play when charge meter is too low

### ISSUE THREAD

**Issue by yzlean** [typical-developers/oaklands-feedback#59]
### Roblox Username

Austin_Cooper

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

Whenever I join the game for the first time and pull out the axe/pickaxe to hit something the swinging animation wont apply on a low power swing, I have to do a 90-100% swing for the animation to activate then it will start to activate on lower powered swings. 

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/144559782/47aa5dd1-a405-486f-b9cd-a290148b88cb

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
This is due to Roblox loading the animation in, not because it's a low powered swing. Our content loading system needs revised and that should help with this issue.
