### ISSUE TITLE
[BUG]: My items from the Classic Event have disappeared from my plot

### ISSUE THREAD

**Issue by NewtTheMazeRunner** [typical-developers/oaklands-feedback#592]
### Roblox Username

AvengersfanIOOO

### What version did this issue occur in?

1.56.0

### Describe the issue in detail.

Today I had about 280k money in my ":D" plot and so I found about the Classic event items and went to the classic store to obtain some, I had bought 50 ducks, 7 of the space things, 5 Maui statues, 2 capture the flag items, and one classic jeep, that brought me down to about 14k subtracting other items I had bought that weren't involved in the classic event so it brought me down to about 60k, once I left the game and joined 20 minutes later, all of the classic event items I had bought were gone, I would like for either all my money back, or all the items back, please and thank you.

### Provide some images / videos of the issue in action.

I have no proof because I was not expecting for all of my classic event items to disappear

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [x] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
you put the items outside of your plot. this is not a bug, it's your mistake.

**Comment by IceChief2862** [comment]
> you put the items outside of your plot. this is not a bug, it's your mistake.
Their items disappeared since they went to a version of the game before they were added. Not sure why these old servers are still up but they said it happened in 1.56.0. This same thing happened to me and I lost 200k from it. It is not their fault but be careful joining public lobbies right now.

**Comment by HooferDevelops** [comment]
I know this is late, but I can reimburse you the money if wanted. This has been fixed for a while and shouldn't happen again.
