### ISSUE TITLE
[BUG]: Disappearing items in 1.57.0 (can join 1.56.0 servers, still!)

### ISSUE THREAD

**Issue by samuelvoo** [typical-developers/oaklands-feedback#594]
### Roblox Username

SaSaGamingXD

### What version did this issue occur in?

1.57.0 (and 1.56.0)

### Describe the issue in detail.

Yesterday I bought the new items in the classic store (7x Ducky, 1x classic jeep, 1x capture the flag, 3x classic moai, 5x Tripmine) with a total of more than 110k. Now today, I joined the game again and suddenly the screen appeared as if the 1.56.0 version was there again. And all the 1.57.0 stuff disappeared, EXCEPT the classic Tree, stone and cactus. Those were still on my plot. I already put the new items in my convenience shop, anchored them, but they were still gone. Then I joined another server and it said welcome to the 1.57.0 update again, and I can probably buy the new items again in the classic store. But how was I able to join (a server with) the old version? I did not get my money back with it, so that's a loss of at least 110k. But for a next time it would be helpful to not get this setback.

I hope I can point this out so you (devs) can make sure it won't happen to people that are gonna spend even more money on this. Thanks.

There is 1 person I found with the problem reported on Github, so I won't click that button (aperently I have to), but still, second is not that much. But i'm sure more people will get the problem.

### Provide some images / videos of the issue in action.

![Afbeelding2](https://github.com/typical-developers/oaklands-feedback/assets/171700847/5e7e9e8a-d0b7-406e-9b62-cc22867c0f63)
![Afbeelding1](https://github.com/typical-developers/oaklands-feedback/assets/171700847/4ad0fe9f-a78b-4b2c-81be-e961bf4e214e)
![imagerobloxdisappearingitemsoaklands](https://github.com/typical-developers/oaklands-feedback/assets/171700847/8c135ad0-0ffd-4ded-986e-fdecb6101fdf)

The last is a screenshot I sent to friends when I bought the truck load of stuff as proof. And the other screenshots are the (now) empty spaces in the shop where used to be items, that are now gone. 

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Hey. I know this is a month late, but I can reimburse the money if wanted. This issue shouldn't happen again, we now have systems in place to prevent you from loading.

**Comment by samuelvoo** [comment]
If you could refund te money, it would be nice. But if its too much work,
just let it be. It was a somewhat over 100k, but 100k is enough.
Thanks for fixing the version update!
Username: SaSaGamingXD / Sam

Op za 13 jul 2024 07:29 schreef Hunter ***@***.***>:

**Comment by HooferDevelops** [comment]
Next time you rejoin & load a slot the money will be reimbursed. It expires in 24 hours from this message!
