### ISSUE TITLE
[BUG]: gift of alpha uncertainty dissapeared when i tried to grab it to mvoe it into my base

### ISSUE THREAD

**Issue by screentimer** [typical-developers/oaklands-feedback#598]
### Roblox Username

Charljnr

### What version did this issue occur in?

1.57.0

### Describe the issue in detail.

So i bought the gift of alpha uncertainty, all that was normal and i drove to my base, then when i grabbed it to put into my little house, it dissapeared, this may be a mobile issue.
(Video inserted is at 720p quality so i can insert it)

### Provide some images / videos of the issue in action.

Uploading copy_B4DEA5A8-4C30-4FBD-9540-9B8FEC7ACEFB.mov…

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
#33
