### ISSUE TITLE
[BUG]: i got ban from oakland idk why that got closed

### ISSUE THREAD

**Issue by timoooooo000000000000000** [typical-developers/oaklands-feedback#599]
### Roblox Username

tim_gaming1039

### What version did this issue occur in?

1.57.0

### Describe the issue in detail.

Idk why but my older post got closed

### Provide some images / videos of the issue in action.

![Screenshot_20240605_094448_Roblox](https://github.com/typical-developers/oaklands-feedback/assets/165175862/a6212271-16bd-49c7-a4b0-d27213d6b256)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by kickTROLL** [comment]
Pretty cool huh

**Comment by 1Peekaboo1** [comment]
It was closed because this is an OFF-TOPIC post. I already explained to you in enough detail on what to do about this. Go to the previous post and read it. All you're doing right now is filling up this issue tracker with garbage posts.

**Comment by INTELUG** [comment]
I have the same problem, I don't know what to do.
