### ISSUE TITLE
[BUG]: Flinging items

### ISSUE THREAD

**Issue by Cheesy15** [typical-developers/oaklands-feedback#611]
### Roblox Username

jagscp3004

### What version did this issue occur in?

1.57.3

### Describe the issue in detail.

Small items like Dynamite and apples go flying once I pick them up
This happens after I buy the item and place it in my truck

### Provide some images / videos of the issue in action.

Video is too big DM me on discord for it my discord is danielcheese

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
#33
