### ISSUE TITLE
[BAN APPEAL]:dwgiawhi

### ISSUE THREAD

**Issue by INTELUG** [typical-developers/oaklands-feedback#619]
### Roblox Username

dwgiawhi

### Ban Reason

Hello, my account (ivanolom-dwgiawhi) was banned by mistake. I did not use any cheats or anything else. I was banned only once when the game first came out but then I was unbanned and I swore that I would NEVER use cheats again and since then I have not betrayed my oath and never used cheats again. Also this ban was given to me when I did not play for about a month. Also I am a very kind player and very often give things and money to other players if they ask me. so now I have on my account if you go and look I have 0 dolars because the last time I played I gave everything to one person who asked me. And everything that I got in the game I got myself and would like to continue to play this wonderful game. so please recheck the ban. Thanks in advance.
![image](https://github.com/typical-developers/oaklands-feedback/assets/132822586/e1b15286-cc58-4e0d-9c74-bb250558f738)

### Other Information

I also wanted to apologize to the administration of this page for writing earlier about my problem at that time. But this was not a section (appealing the ban) and this allowed them to interfere with their work. I hope you will forgive me for this too. I have great respect for the administration and did not want to interfere with it. I just didnt know then where to write about this problem.

### Before Submitting

- [X] I understand that this is the *only* appeal that I will get.
- [X] I have been completely honest about why I was banned.

**Comment by INTELUG** [comment]
I would like to add that most likely this is some kind of bug because other people also complain about it and they also didn’t play for a while and then got banned for no reason.
I can also assume that the bug is related to the fact that you change your account and at the same time you don’t even need to enter the game and then you get a ban.
I honestly can’t understand why all this is connected, but it seems like it is.

**Comment by Topcathel** [comment]
I want and can confirm that this person did nothing against the rules of the game. He brought me into this game, told me the basics, helped me develop, and now my slot in the game is already 1 year old, and I continue to enter this game thanks to this man. I kindly ask you to reconsider his ban. This person is very good, he has never broken the rules of the game since he was unbanned. I want to say that the ban happened by mistake.

**Comment by 1Peekaboo1** [comment]
I need the banned alt account's name. I will not be able to unban you until i unban the alt.

**Comment by INTELUG** [comment]
well, maybe it's this account but I haven't played on it for a very long time (ConeFriend1
@ConeFriend1)

**Comment by INTELUG** [comment]
I just can’t understand at all why I got banned. But as far as I understand, I’m accused of using another account to bypass punishments that I couldn’t even know about and this is very strange

**Comment by INTELUG** [comment]
for me there is no point at all in using cheats on an account on which I already have almost all the things

**Comment by 1Peekaboo1** [comment]
> I just can’t understand at all why I got banned. But as far as I understand, I’m accused of using another account to bypass punishments that I couldn’t even know about and this is very strange

Newly introduced native banning system allows the developers to detect and ban all related alt accounts if even a single one got banned. Due to the fact you were banned on an alt a long while ago it has locked all the other ascociated accounts now with the intorduction of the system. I will unban you when i'm granted the permission to do so by Hoofer.

**Comment by INTELUG** [comment]
Thanks so much !!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by 1Peekaboo1** [comment]
Appeal accepted. User unbanned

**Comment by Topcathel** [comment]
yoohoo
thanks so muchhh!!!

**Comment by INTELUG** [comment]
thanks so much guys !!!
