### ISSUE TITLE
[BUG]: Items flinging on pick up. 

### ISSUE THREAD

**Issue by Zanados** [typical-developers/oaklands-feedback#620]
### Roblox Username

Zaberdin

### What version did this issue occur in?

1.57.3 and some prior. 

### Describe the issue in detail.

Please make this a **_High Priority_** bug to fix. 

Items, sometimes fling on pick up.

This is very aggravating. I have bought 1063 baby ducks in order to get two evil baby ducks. I have lost both of my evil ducks because of this.  I have looked High and Low both times this has happened, but I haven’t been able to find them.  For materials, it’s no big deal, I just go get more. But, for the rare items, it is so aggravating.  I’m not asking to get my evil ducks back, I would just like to have this fixed.

I’m pretty sure this has been happening through several of the last updates.  I thought it had been reported previously, but it’s still happening.

FYI, I play on iPad.

### Provide some images / videos of the issue in action.

None

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
#33
