### ISSUE TITLE
[BUG]: You are able to attach multiple trailers in one hitch

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#63]
### Roblox Username

tupisupi

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

Title and video:

### Provide some images / videos of the issue in action.

https://cdn.discordapp.com/attachments/894303588556357692/1150785476169564191/two_trailers_in_one_attachment_point.mp4

### Before Submitting

- [x] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
I don't think this is necessary to fix. Could create some cool setups as well.
