### ISSUE TITLE
[BUG]: Magma cave glitch damage.

### ISSUE THREAD

**Issue by jballar3** [typical-developers/oaklands-feedback#634]
### Roblox Username

jball2014

### What version did this issue occur in?

1.58.4

### Describe the issue in detail.

Im playing on PS5. Whenever I walk or drive over the planks in the magma cave, I take damage. This is not a one time occurrence and happens every time I access the cave. This makes it extremely hard if not impossible to access magma trees.

### Provide some images / videos of the issue in action.

Uploading IMG_5127.mov…

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by 1Peekaboo1** [comment]
that's

that's intended. You're walking across a lava lake. You're literally getting roasted, of course you're gonna take damage

**Comment by 1Peekaboo1** [comment]
just drive over the planks fast, it's not an issue

**Comment by jballar3** [comment]
Even on land I take the damage though. I cant get to any part of the cave
without dying, especially on the parkour bits.

**Comment by OopsS34rus** [comment]
that's also intended, you take damage from heat every time you're close to lava, just use fusion or healing coil its not this much of a problem

> Even on land I take the damage though. I cant get to any part of the cave without dying, especially on the parkour bits.
