### ISSUE TITLE
[BUG]: 7x dynamite not exploding

### ISSUE THREAD

**Issue by Jaspingo** [typical-developers/oaklands-feedback#638]
### Roblox Username

UnknownPjs

### What version did this issue occur in?

1.58.4

### Describe the issue in detail.

7x dynamite not exploding when interacted with. Other players tried interacting on my 7x dynamite which also didn't work, didn't get a chance to try regular dynamite or 3x sorry! Bombs seemed to have worked fine. 

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/171175636/c01a704c-c2f1-402c-8762-308b0cf4808d

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
I don't think this is a bug, this seems to be because someone is not giving trust, resulting in it not exploding. I will look into adding some sort of visual indicator.

**Comment by Jaspingo** [comment]
Just to clarify, in the video I owned the dynamite and tried to activate it. I then gave another user trust to make sure it wasn't my connection affecting it, however, they could not activate it either.  I tried it again without any other players nearby, just me, and it still didn't activate when interacted with. 

I do think that adding a visual indicator is useful though thank you!

**Comment by HooferDevelops** [comment]
The other person has to trust you, as it can damage them
