### ISSUE TITLE
[IMPROVEMENTS]: Can't select design and a friend's base

### ISSUE THREAD

**Issue by ManancialGD** [typical-developers/oaklands-feedback#639]
### Roblox Username

BrenoGamerBr205

### What do you think can have quality-of-life improvements?

I think that would be great if it had a perm to select designs in someones base. 

### How do you think things can be improved?

I am building with my gf and I can't take some design that myself made, cuz I made in her base... kinda annoying
![imagem_2024-06-18_183837569](https://github.com/typical-developers/oaklands-feedback/assets/143729780/05018ebd-6a45-4af8-963e-0c3c6d74fbea)

**Comment by HooferDevelops** [comment]
Hey, this is a bug. It will be fixed for 1.59.0, thanks!

**Comment by ManancialGD** [comment]
No, thank you! It also doesn't work it the blueprint is mine and I'm in other's place, but should be the same fix. Thank you very much!
