### ISSUE TITLE
[BAN APPEAL]: {Nexlup3}

### ISSUE THREAD

**Issue by Nexlup** [typical-developers/oaklands-feedback#648]
### Roblox Username

Nexlup (@Nexlup3)

### Ban Reason

![2024-06-23_19-31-41](https://github.com/typical-developers/oaklands-feedback/assets/104732866/5bb8559d-c16a-4bea-9b1e-028286cb5d1f)

Hello, I'm explaining everything honestly, I once stopped playing Oaklands, but after 2-3 months I came back (it's 3 days ago I logged into this game) and I see a window saying "you created or used an account to bypass the ban" (I may not write correctly), yes, I used another account, but I didn't use any programs related to the virus, but just so that I could transfer things from the first slot to the slot of another account and give myself only to another slot, but I don't think it's forbidden, I won't give things to strangers to they can scam me.

### Before Submitting

- [X] I understand that this is the *only* appeal that I will get.
- [X] I have been completely honest about why I was banned.

**Comment by Nexlup** [comment]
tell me at least one reason why I was banned, I will apologize to you if it was dont need to use another account.

**Comment by Nexlup** [comment]
Sir, how is it long?

**Comment by Nexlup** [comment]
We don’t have the right to use other accounts when I was constantly out of the bath? “the bot doesn't lie” a person who received a ban for no reason, but that person himself writes that he did not use other accounts, and his admin (or whoever was there) checked and unbanned, thinking that it was a malfunction of the bot, you you know that not all bots can work properly

**Comment by Nexlup** [comment]
It can’t be that BOTS work PERFECTLY, so I’m still interested, I wasn’t allowed to use other accounts in honor of “just replay for fun or let’s say I needed to transfer things to another slot using them”, other than such actions I didn’t use anything

**Comment by LuckFire** [comment]
If you're impatient, make a ticket in the Discord, which is advised in the README if you read it before making an appeal. GitHub appeals aren't prioritized, this is just to keep people from making issues about something that has nothing to do with a bug.

**Comment by Nexlup** [comment]
LuckFire, when I was looking for a "ban complaint" or similar, but I found this for GitHub, explain to me which README and where to create a ticket.

**Comment by HooferDevelops** [comment]
You're not banned. You're locked for ban evasion on Oaklands by Roblox. If you don't want to state your main account, you'll remain locked out.
