### ISSUE TITLE
[BUG]: The ore will reduce size and value when leave then rejoin

### ISSUE THREAD

**Issue by dhminh99** [typical-developers/oaklands-feedback#65]
### Roblox Username

R1chBaconn

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

The ore will reduce size 0.01 studs and a bit of value when leaving the game, then re -enter and load saved (I only test on raw ore and refine ore)

### Provide some images / videos of the issue in action.

[robloxapp-20230912-2113209.zip](https://github.com/typical-developers/oaklands-feedback/files/12587449/robloxapp-20230912-2113209.zip)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by dhminh99** [comment]
![Screenshot 2023-09-13 165639](https://github.com/typical-developers/oaklands-feedback/assets/144800846/a4b163a8-dd94-49db-912a-30bc3676c197)
![Screenshot 2023-09-13 165653](https://github.com/typical-developers/oaklands-feedback/assets/144800846/dbb01b4b-4494-48ca-8d2e-f566240b7c46)
![Screenshot 2023-09-13 165904](https://github.com/typical-developers/oaklands-feedback/assets/144800846/bac08b0e-6035-4c60-a300-95bc72a7fdab)
![Screenshot 2023-09-13 165938](https://github.com/typical-developers/oaklands-feedback/assets/144800846/81d49226-7ce0-45a7-8dad-8f89b6f3771e)

**Comment by HooferDevelops** [comment]
Intended behavior. Size values are rounded by small amounts in order to save on data size.
