### ISSUE TITLE
[BUG]: Resizing broke

### ISSUE THREAD

**Issue by 1Stud2Tall** [typical-developers/oaklands-feedback#650]
### Roblox Username

1Stud2Tall

### What version did this issue occur in?

1.59.0

### Describe the issue in detail.

With the latest update switching to resize in build mode works but won't let you actually resize schematics, see attached screenshot for dev console logs

### Provide some images / videos of the issue in action.

![grafik](https://github.com/typical-developers/oaklands-feedback/assets/78302203/e001f6fb-9a19-4693-96ad-87eee9f7fd6d)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Does this still happen?

**Comment by 1Stud2Tall** [comment]
Fixed with 1.59.1
