### ISSUE TITLE
[BUG]: adurite changing to something else

### ISSUE THREAD

**Issue by Vindicativa** [typical-developers/oaklands-feedback#651]
### Roblox Username

Vindicativva

### What version did this issue occur in?

1.58.4

### Describe the issue in detail.

So, i just made my floor with lava slate, and somehow it all became white. I also had a storage drawer made out of lava slate with lava slate inside, and it became this (i also cant take things out of it, neither unlock it)

### Provide some images / videos of the issue in action.

![imagen_2024-06-24_182718341](https://github.com/typical-developers/oaklands-feedback/assets/118635020/211f3e2c-3fbf-4d10-9afe-c4369eef5e01)
![image](https://github.com/typical-developers/oaklands-feedback/assets/118635020/ae3b09e7-5e14-4d5e-9480-73b6ea336edb)
![image](https://github.com/typical-developers/oaklands-feedback/assets/118635020/da31dcce-c010-4f60-a8fc-7b1f9a2b8b30)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by jballar3** [comment]
Same exact thing happened to me just now. My marble stairs and floor turned into that same white wood.
![image](https://github.com/typical-developers/oaklands-feedback/assets/173003617/68a2adea-70aa-4198-8cb8-125e437adc6a)

**Comment by jballar3** [comment]
Possibly linked to the update? I’ve noticed some servers have not updated yet.

**Comment by Canvus-Paint** [comment]
The same thing happened to me. It sucks because I had stored a good bit of electrified stone in one of the drawers.
![Uploading Screenshot 2024-06-25 083137.png…]()
