### ISSUE TITLE
[BUG]: Visual Bug

### ISSUE THREAD

**Issue by Marklolz** [typical-developers/oaklands-feedback#660]
### Roblox Username

Marklolz

### What version did this issue occur in?

1.58.4

### Describe the issue in detail.

When loading in plot and playing over half my plot has been turned into Sawed Birch, the materials I used for the areas that are now birch was Dark Slate, Lights Slate, Red Bricks, Copper, Tin. I believe it's just a visual bug because the statistics tool doesn't allow me to view it.

### Provide some images / videos of the issue in action.

![Roblox VR Screenshot 2024 06 25 - 14 21 06 69](https://github.com/typical-developers/oaklands-feedback/assets/173842289/90d0bb64-76d2-4339-9476-6e90201fe6a5)
![Roblox VR Screenshot 2024 06 25 - 14 21 32 99](https://github.com/typical-developers/oaklands-feedback/assets/173842289/b4493bc4-bfe2-4ca0-9457-ac3983d9d06e)

### Before Submitting

- [ ] I have confirmed that nobody else reported this issue.
- [x] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by jballar3** [comment]
I’ve noticed that this happens when building in a 1.59.1 server, then loading again into a 1.58.4 server. These issues would be fixed if they would just shut down the old severs.

**Comment by jballar3** [comment]
However do not worry because your builds will reverse back to normal as soon as you load back into a 1.59.1 server.

**Comment by Marklolz** [comment]
thanks
