### ISSUE TITLE
[IMPROVEMENTS]: Make common black "black" and rare black "really black" (brick colors)

### ISSUE THREAD

**Issue by JackOfCool** [typical-developers/oaklands-feedback#67]
### Roblox Username

JackThePC_Overlord

### What do you think can have quality-of-life improvements?

Black car colors

### How do you think things can be improved?

Make common black "black" and rare black "really black" (brick colors).
Please
Why would you have a rare version of black that is quite literally identical. Make common black worse so rare black can have purpose/actual value. 🙏🙏🥺🥺

im talking about car colors btw 
ty

**Comment by InvertedReaIity** [comment]
I agree. There’s no point of having a rare version that’s identical to the common one.

**Comment by Imjustjokingwithya** [comment]
literally no difference in the ss ultrablade sent hence i agree with this
