### ISSUE TITLE
[BUG]: terracotta refinery

### ISSUE THREAD

**Issue by BladeeReal** [typical-developers/oaklands-feedback#670]
### Roblox Username

medusabloodd

### What version did this issue occur in?

1.60.0

### Describe the issue in detail.

 only some of my terracotta gets refined and the rest just passes through

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/174147392/58a2468b-ef8f-462d-8d63-de25727bb86a

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by SniperOnSunday** [comment]
Seems to happen a lot with the long/large stones.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
The rocks are larger than acceptable size of refined in 1 axis, but devs never fixed that.
My solution is accept rock that dosen't exceed 2 axies, as it can fit in.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
The solution about this is:
```lua
function CheckIfTheHoleFits(Hole:Vector2,Size:Vector3)
	local LongestHoleSize = math.max(Hole.X,Hole.Y)
	local ShortestHoleSize = math.min(Hole.X,Hole.Y)
	local PartSizes = {Size.X,Size.Y,Size.Z}
	table.sort(PartSizes) -- needs optimization
	local LongestPartSize = PartSizes[3]
	local MiddlePartSize = PartSizes[2]
	local ShortestPartSize = PartSizes[1]
	return MiddlePartSize <= LongestHoleSize and ShortestPartSize <= ShortestHoleSize
end
```
As this works with rocks that are longer than 1 axis acceptable size. it rejects rocks exceeding acceptable size.

**Comment by 1Peekaboo1** [comment]
you're late
![изображение](https://github.com/typical-developers/oaklands-feedback/assets/127379625/fdbf6560-6749-4e1d-8223-976cc088ca90)


> The solution about this is:
> 
> ```lua
> function CheckIfTheHoleFits(Hole:Vector2,Size:Vector3)
> 	local LongestHoleSize = math.max(Hole.X,Hole.Y)
> 	local ShortestHoleSize = math.min(Hole.X,Hole.Y)
> 	local PartSizes = {Size.X,Size.Y,Size.Z}
> 	table.sort(PartSizes) -- needs optimization
> 	local LongestPartSize = PartSizes[3]
> 	local MiddlePartSize = PartSizes[2]
> 	local ShortestPartSize = PartSizes[1]
> 	return MiddlePartSize <= LongestHoleSize and ShortestPartSize <= ShortestHoleSize
> end
> ```
> 
> As this works with rocks that are longer than 1 axis acceptable size. it rejects rocks exceeding acceptable size.

**Comment by megachris84** [comment]
my base size went 6 fold for the update is that normal
![image_2024-06-29_081947515](https://github.com/typical-developers/oaklands-feedback/assets/173970049/f4ff2d84-6256-429d-80b8-7ebb83d7cf82)

**Comment by Somethingthatisnttakenplz** [comment]
No shot he actually coded that
