### ISSUE TITLE
[BUG]: Ore too thin for Refining

### ISSUE THREAD

**Issue by AgentVen** [typical-developers/oaklands-feedback#677]
### Roblox Username

AgentVen_RBLX

### What version did this issue occur in?

1.60.0

### Describe the issue in detail.

Attempting to put thin ores in to the Refinery will result in them not being processed. (`see Video#1`)
I've even attempted to force it to be processed by shake it around inside. (`see Video#2`)

Now, I thought maybe it works with the Rusty Refinery, however after I bought one to test, not even it worked! (`see Video#3`)

And, though I've yet to buy it, it's safe to assume the Industrial Refinery wouldn't work either.

### Provide some images / videos of the issue in action.

`Video#1`
https://github.com/typical-developers/oaklands-feedback/assets/98724434/006db459-7146-4410-aca9-4b3678545080

`Video#2`
https://github.com/typical-developers/oaklands-feedback/assets/98724434/5e8cd89d-3d51-48c4-9dcb-59a04a86d86e

`Video#3`
https://github.com/typical-developers/oaklands-feedback/assets/98724434/de9d5dc2-612c-45a7-a444-0216e08e97f6

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by 1Peekaboo1** [comment]
Fixed in 1.60.1

**Comment by AgentVen** [comment]
Understood.
