### ISSUE TITLE
[BUG]: Fusion coil changes the gravity of blocks when equipped

### ISSUE THREAD

**Issue by Teiiks** [typical-developers/oaklands-feedback#679]
### Roblox Username

TylerPlysRoblox

### What version did this issue occur in?

1.60.1

### Describe the issue in detail.

When equipping the fusion coil the blocks coming off my conveyor seem to be almost weightless and will fly further than they would when the fusion coil is not equipped.

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/174209755/06d61848-0302-4a57-8724-f1e47e2684c4)
![image](https://github.com/typical-developers/oaklands-feedback/assets/174209755/fbb1e4f4-f42b-4fdb-a851-2c8809f06a71)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
This is due to how the fusion coil works, and we've decided we won't fix it
