### ISSUE TITLE
[BUG]: Sanders incorrectly sizing milled wood

### ISSUE THREAD

**Issue by Z0SC** [typical-developers/oaklands-feedback#681]
### Roblox Username

Z3SC

### What version did this issue occur in?

1.60.1

### Describe the issue in detail.

When Sanding wood the game can incorrectly determine the size of bark and spawn piece(s) of milled wood that are way too small, resulting in money loss.

### Provide some images / videos of the issue in action.

https://medal.tv/games/roblox/clips/iaCki8r8q0baSB_Sn/d1337EE8b9qs?invite=cr-MSxsTXQsMzg5MDM2ODAs
https://medal.tv/games/roblox/clips/iaCimUUjF4itZlq3P/d133787Aqquz?invite=cr-MSx0bjksMzg5MDM2ODAs

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by ShastaIsaDog123** [comment]
I believe the wood piece is too big and it teleports it under the floor to give it room. I have noticed that the longer pieces tend to go random places. I suggest a fix to be instead of having long skinny pieces for those trees with many pieces that get processed to have it be a more chunky piece
