### ISSUE TITLE
[BUG]: Anchoring tool doesn't use client position

### ISSUE THREAD

**Issue by Z0SC** [typical-developers/oaklands-feedback#682]
### Roblox Username

Z3SC

### What version did this issue occur in?

1.60.1

### Describe the issue in detail.

When you press "F" to anchor an object it doesn't take the current client position into account before anchoring, meaning when the server receives the event it anchors the object wherever it is (even if its off base) this also means you cannot get your item back and it is stuck there in this case.

### Provide some images / videos of the issue in action.

https://medal.tv/games/roblox/clips/iaDdMqLutlLCSB8rJ/d1337qsqXGib?invite=cr-MSxDYzQsMzg5MDM2ODAs

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by Z0SC** [comment]
It actually came back onto the base after like 5 minutes so you guys might already have a system to prevent this, but it would be nice if there is a way to prevent it entirely.

**Comment by HooferDevelops** [comment]
This was a really unique one, thanks for reporting
