### ISSUE TITLE
[BUG]: Neon Rocks

### ISSUE THREAD

**Issue by Enaty23** [typical-developers/oaklands-feedback#685]
### Roblox Username

Enatitus23

### What version did this issue occur in?

1.60.1

### Describe the issue in detail.

When you select a stone with the chisel, there are some parts where the entire stone is selected, and it turns neon white. Also, when you go to make the rock smaller, there is a Z-fighting bug, which previously did not exist.

### Provide some images / videos of the issue in action.

![Roblox 30_06_2024 10_54_12](https://github.com/typical-developers/oaklands-feedback/assets/172948224/833b62e8-e0fc-446a-a65c-d084e04f551a)
![Roblox 30_06_2024 10_54_27](https://github.com/typical-developers/oaklands-feedback/assets/172948224/3f286688-4dcb-4d18-abbd-4af051421a47)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Going to close this as we plan on revamping the chisel entirely. Thank you!
