### ISSUE TITLE
[BUG]:lost items 

### ISSUE THREAD

**Issue by zyyy-155** [typical-developers/oaklands-feedback#695]
### Roblox Username

Maybe_olive125

### What version did this issue occur in?

1.60.1

### Describe the issue in detail.

okay so i don’t know if it’s a bug or if im just doing something wrong but i bought the starter pack and when i did i wasnt near my land so as i was trying to take my stuff back to my land my internet shut off and i got kicked out, when i joined back the stuff i bought was gone. I’m not sure if there’s a way to get it back or not but i went everywhere looking for it and clicked every button to see if i could spawn it but it didn’t work.

### Provide some images / videos of the issue in action.

i don’t have any images or videos of it happening i’m on console 

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
If you could make a ticket for this in our Discord, you can get help there
