### ISSUE TITLE
[BUG]: Occasional BIG physics lag spikes after v.1.60.0 update

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#698]
### Roblox Username

tupisupi

### What version did this issue occur in?

1.60.0

### Describe the issue in detail.

Basically title, even when having less than 10 items on conveyors you occasionally get these massive physics lag spikes that last anywhere from a couple seconds to 30.

### Provide some images / videos of the issue in action.

Discord message link (not media link) to video I uploaded in TD discord server: https://discord.com/channels/865737627712749579/894024102174658644/1258093635707342988

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
I believe this is sort of fixed? It's a confusing problem.

**Comment by HooferDevelops** [comment]
*in 1.62.0
