### ISSUE TITLE
[BUG]: Burning Blossoms spawn in invalid locations

### ISSUE THREAD

**Issue by frosteeskecth** [typical-developers/oaklands-feedback#700]
### Roblox Username

Mac_OSmonterey

### What version did this issue occur in?

Alpha 1.60.1

### Describe the issue in detail.

A burning blossom spawned floating on top of the lava.

### Provide some images / videos of the issue in action.

![wtfisthis](https://github.com/typical-developers/oaklands-feedback/assets/84553403/869c82ca-a803-4880-9d86-188db16f3cf6)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
This is a side effect of our generation, too minor to fix
