### ISSUE TITLE
[BUG]: Invisable paintings

### ISSUE THREAD

**Issue by DNGRnoodle** [typical-developers/oaklands-feedback#701]
### Roblox Username

baconbaconmeow

### What version did this issue occur in?

1.60.1

### Describe the issue in detail.

All paintings on my plot are invisible to me, the image, not the frame. Everyone else can see them besides me. Trying to reload the paintings by moving it in build mode doesn't fix the issue, but changing the decal ID to another fixes it. I don't understand why I suddenly cannot see all the decals that are in my house. I uploaded all the decals myself but there are also a few default ones that I didn't touch that i also cannot see now. 

### Provide some images / videos of the issue in action.

![Screenshot (1018)](https://github.com/typical-developers/oaklands-feedback/assets/174666738/fdeebba9-71f8-4e97-bcc1-1169c643ba1f)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
The assets likely failed to load, a rejoin would fix this. If that's not the case, then they may have been moderated.
