### ISSUE TITLE
[BUG]: Some tip signs aren't affected by "Disable Tips around the Map" setting

### ISSUE THREAD

**Issue by piw-piw** [typical-developers/oaklands-feedback#702]
### Roblox Username

Ninja_948bin

### What version did this issue occur in?

1.61.0

### Provide some images / videos of the issue in action.

![image](https://github.com/typical-developers/oaklands-feedback/assets/76477070/3cb9add6-f37a-4744-abe3-a02ee1ff9467)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
These likely won't be fixed because they are a core part of the map, not one of the random cycling tips
