### ISSUE TITLE
[BUG]: Multiselect

### ISSUE THREAD

**Issue by Jc042** [typical-developers/oaklands-feedback#705]
### Roblox Username

042509_Jc

### What version did this issue occur in?

1.61.0

### Describe the issue in detail.

So the issue is mobile (I don't know about pc) multi select gets in the of building or selecting options. Example 1, if i try to press on an option like it select a structure but also still presses the button i clicked on. Example 2, if you try to change the size on a structure it thinks you clicked on another on structure and stops you from getting your work done. To fix this problem I suggest to add multi select as an option like delete which also lets you  multi select but to delete structures.

### Provide some images / videos of the issue in action.

It said the file was too big (it was a 8 second video)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Fixed in 1.60.1
