### ISSUE TITLE
[BUG]: Lithium not spawning in Sandslate and Terracotta nodes.

### ISSUE THREAD

**Issue by artz144** [typical-developers/oaklands-feedback#711]
### Roblox Username

chechyva

### What version did this issue occur in?

1.61.0

### Describe the issue in detail.

Before the 1.61.0, lithium used to frequently spawn in desert caves, and now there's not A SINGLE LITHIUM there. Bring it back bevelopers please

### Provide some images / videos of the issue in action.

not needed

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] #723

**Comment by HooferDevelops** [comment]
Lithium appears to still be in the RNG

**Comment by artz144** [comment]
Ummm, no it doesn't? I've mined an entire ravine of sandslate and terracotta nodes but I still haven't found ANY lithium, I even found uranium and paladium but not that. (server ver. was 1.61.0)
![image](https://github.com/typical-developers/oaklands-feedback/assets/143691115/4163563e-40ac-4cc2-b2d3-01dbb8b613b2)
