### ISSUE TITLE
[IMPROVEMENTS]: Multi-select

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#714]
### Roblox Username

tupisupi

### What do you think can have quality-of-life improvements?

Multi-select

### How do you think things can be improved?

It would be neat if multi select mode wouldn't automatically deselect everything after confirming placement allowing for more finer adjustments and more time saved. You could call this a user error and such, I haven't had this happen to me yet but it is a thought that popped up when I selected 100 schematics and moved them elsewhere. Lets say I misplaced it by 1 stud, I'd have to reselect all 100 schematics again to adjust it.

AND/OR

Have a multi-select option similar to the fabricator, where you specify a zone and everything within it would get selected instead of manually selecting stuff one by one.

**Comment by Z0SC** [comment]
Personally my favorite idea of quick selection is in Miners Haven where you hold down a specific key bind and it will automatically select all the items that that mouse goes over while the keys are pressed.
Example: https://youtu.be/uqSAFAE_Owk?t=227

**Comment by HooferDevelops** [comment]
Going to close this, but unfortunately I can't make it remember what you just placed. It's mostly due to technical reasons. I hope the second option is good enough for now.
