### ISSUE TITLE
[IMPROVEMENTS]: There should be a positive difference between different forge variants (rusty, metal, industrial)

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#72]
### Roblox Username

tupisupi

### What do you think can have quality-of-life improvements?

Players should have a reason to buy different tier forges

### How do you think things can be improved?

Currently there is no point in buying the industrial variant of a forge as you don't gain any more money from it nor does it have any unique abilities compared to metal and rusty other than a bigger input. Players are just able to scale the refiner output to as small as possible and place a rusty forge after it and achieving the same result as an industrial forge.

How it can be improved:
- Have it make more money compared to other ones whether that is with making worse variants of forges lose X amount of % of the ore in volume or adding a multiplier or something. Do note that since you are able to reprocess forged stuff in a forge do not make it so that it grows in volume as that can be abused.
- Give it a unique ability such as a chance to get ores from stone pieces that do not have any ore. For example forging a piece of refined lightslate has a chance to turn it into iron.

If anyone else has some neat improvements please comment below this, thank you.

**Comment by HooferDevelops** [comment]
This is no longer relevant due to our power requirements for certain materials (I think).
