### ISSUE TITLE
[BAN APPEAL]: {Violetgamergirl280}

### ISSUE THREAD

**Issue by Cloudxian** [typical-developers/oaklands-feedback#720]
### Roblox Username

Violetgamergirl280

### Ban Reason

![Screenshot_2024-07-07_142222](https://github.com/typical-developers/oaklands-feedback/assets/174928796/52caa7b2-3edb-4d67-a627-3c32a5960ac7)

### Other Information

Sorry about previous appeal, i cant speak english properly, all what i write is based on google translate, The details about it is im never logging on oakland like 4-5 days, and then im loggiing this time its said i got banned for avoiding enforcement on another account, i dont understand about it because i never play with another account and i never cheat, all what i do is logging and exploring new map last time i played this game, thats all from me, thank you. 

Sincerely cloudxian

### Before Submitting

- [X] I understand that this is the *only* appeal that I will get.
- [X] I have been completely honest about why I was banned.

**Comment by 1Peekaboo1** [comment]
That's better
Okay, so. You're pretty much caught by the alt detection system. That means someone in your household on their account or you on an alt. In order for us to even help we'll need the roblox names of these accounts. Otherwise we'll be unable to help

**Comment by Cloudxian** [comment]
I only have 3 accounts, Violetgamergirl280, sifahricemeffa, and nutella_lyndx, yeay thats all account that i have

**Comment by 1Peekaboo1** [comment]
first off
sifahricemeffa is written in caps lock, Just so you know the nicknames are case sensitive so keep that in mind. And no, this one isn't banned

second: I cannot find nutella_lyndx on roblox. There's plethora of similarly named accounts but there's none that are named like this. Are you sure you wrote the name correctly?

**Comment by Cloudxian** [comment]
Im sorry, there is a typo at nutella accound, it should be nutella_lindx

**Comment by 1Peekaboo1** [comment]
and...this account isn't banned either.
Do you have relatives that play roblox? Could you provide me their roblox names too?

**Comment by Cloudxian** [comment]
I don't have any family members who play Roblox, but I have one friend whose house is not far from mine, if I'm not mistaken his account name is Nizarmasta or nizaarmasta.

**Comment by 1Peekaboo1** [comment]
Unless you provided an incorrect user - this user isn't banned either.

Unfortunately none of the accounts you provided were initially banned. Due to that we cannot help you whatsoever

**Comment by Cloudxian** [comment]
Can I ask something?, like, can people commit slander by using the same account name or username and making mistakes to harm others? Im afraid if someone do that, Because there is a lot of account same with my display name

**Comment by 1Peekaboo1** [comment]
no. That's not possible. The bans are not manual. If the anti-cheat bans you, this ban spreads to all existing accounts that were made on the same device/under the same IP/same MAC adress. To unban you i need to unban the account that was banned first.

**Comment by Cloudxian** [comment]
I never cheat and i dont know how this thing can happen, i think ill quiting from playing oaklands, thanks for your help
