### ISSUE TITLE
[BUG]: Signs don't support Rich text

### ISSUE THREAD

**Issue by SuperDed2006** [typical-developers/oaklands-feedback#73]
### Roblox Username

GamEditoPro

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

Sign schematics have statement in descripting, that it supports RichText. Instead, when I try to type it, sign just cuts it off. So if you will open text edit again, you won't see any RichText pieces you typed.

### Provide some images / videos of the issue in action.

I tried to use this to change text color:
<font color="FF8000">Orange</font>
This should output orange text "Orange". Instead, I see white/black "Orange" text (based on sign material's color)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Our sign system does not use an exact copy of rich text. <color red>This is what red text looks like.</color>
