### ISSUE TITLE
[BUG]: Refinery Machine

### ISSUE THREAD

**Issue by NaitoAku128** [typical-developers/oaklands-feedback#733]
### Roblox Username

ZACHARY_128

### What version did this issue occur in?

1.61.2

### Describe the issue in detail.

It seems that there is an issue with the disappearance of rocks and ore when using the Refinery machine.

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/175138233/974d67fa-b536-45dd-8571-342b5072de9e

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
That piece of wood on the side of the refinery is making it considered blocked.

**Comment by NaitoAku128** [comment]
> That piece of wood on the side of the refinery is making it considered blocked.

Thank you for taking the time to comment on my issue. I apologize if it caused any inconvenience.
