### ISSUE TITLE
[BUG]: Copy wire feature allows you to connect stuff from input to input and does not allow you to connect input to output

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#734]
### Roblox Username

tupisupi

### What version did this issue occur in?

1.61.2

### Describe the issue in detail.

Title and video

### Provide some images / videos of the issue in action.

Discord message link to TD server where I uploaded video https://discord.com/channels/865737627712749579/894024102174658644/1260286904667078816

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by azavier-a** [comment]
I have also confirmed this bug still exists. 

step 1: wire the output of something to the input of something

step 2: copy the wire

step 3: It is now impossible to correctly wire, as the input to the second thing will now only connect to other inputs


has caused me a lot of time wasted making my wires look nice, but other than that it's not a big deal
