### ISSUE TITLE
[BUG]: fly glitch pre patch on controller 

### ISSUE THREAD

**Issue by LunixShotz** [typical-developers/oaklands-feedback#74]
### Roblox Username

limitedshotz99 

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

You can do the fly glitch pre patch with a controller and it’s supper op you can go really fast

### Provide some images / videos of the issue in action.

[Example of fly glitch ](https://vimeo.com/868158556) 

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by LuckFire** [comment]
Please double check the version -- does not seem accurate.

**Comment by HooferDevelops** [comment]
Edited.
