### ISSUE TITLE
[BUG]: FABRICATOR DOESN'T SELECT MACARONI SCHEMATICS

### ISSUE THREAD

**Issue by vbdoob** [typical-developers/oaklands-feedback#742]
### Roblox Username

yourfriendlybotanist

### What version did this issue occur in?

1.61.2

### Describe the issue in detail.

I was doing a commission for someone and when I went to blueprint it, all the macaroni schematics were missing. I was trying to figure out why and I confirmed, all macaroni schematics aren't able to be selected during "design select region".

### Provide some images / videos of the issue in action.

![RobloxScreenShot20240712_164508281](https://github.com/user-attachments/assets/94ea279b-dacd-4ec6-9443-0ecc6b615344)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Fixed 1.62.0, thanks
