### ISSUE TITLE
[IMPROVEMENTS]: Living axe should retain 100% of forgeables

### ISSUE THREAD

**Issue by Z0SC** [typical-developers/oaklands-feedback#743]
### Roblox Username

Z3SC

### What do you think can have quality-of-life improvements?

Living axe ability

### How do you think things can be improved?

Since the living axe recently gained the ability to retain leaves on trees, I believe a really USEFUL and POWERFUL addition to its ability would be the power to keep all fruits / flowers on the tree that is chopped down with it.

Photo of current axe behavior which kills ~50% of forgeables when chopped down:
![image](https://github.com/user-attachments/assets/821cadc8-131f-4852-8f1a-942703778a1e)

**Comment by HooferDevelops** [comment]
Great, idea, thanks, will be added 1.62.0!
