### ISSUE TITLE
[BAN APPEAL]: xcarterx12

### ISSUE THREAD

**Issue by PapaHugs** [typical-developers/oaklands-feedback#748]
### Roblox Username

xcarterx12

### Ban Reason

i wont lie late last year i was using some explicit clients to help me get the edge in Oaklands on a alternate account. i decided to hop on my main account today to play the game because I'm really board but I'm banned. i promise i wont do it again i am a reformed man and i hope you take me back. <3 love Oaklands!

### Before Submitting

- [X] I understand that this is the *only* appeal that I will get.
- [X] I have been completely honest about why I was banned.

**Comment by 1Peekaboo1** [comment]
what's your alt account's name

**Comment by PapaHugs** [comment]
thats a good question if i had to guess probably xcarterx1231

**Comment by 1Peekaboo1** [comment]
You should now be unbanned

**Comment by 1Peekaboo1** [comment]
Appeal Resolved
