### ISSUE TITLE
[BUG]: Anchoring an item also selects the structure behind it.

### ISSUE THREAD

**Issue by Luminatron** [typical-developers/oaklands-feedback#749]
### Roblox Username

second_sphere

### What version did this issue occur in?

1.62.0

### Describe the issue in detail.

It's annoying. You have to press B and 5 after every anchor.
Y'all should change the Anchor key to E or something. Makes more sense than F.

### Provide some images / videos of the issue in action.

https://github.com/user-attachments/assets/2baf6125-449a-4418-9702-a16ed3014a9d

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by SniperOnSunday** [comment]
Can corroborate this. It's actually very annoying, and I hope they fix it soon.
