### ISSUE TITLE
[BUG]: Drag multi-select continues selecting stuff even after you release F key 

### ISSUE THREAD

**Issue by Imjustjokingwithya** [typical-developers/oaklands-feedback#750]
### Roblox Username

tupisupi

### What version did this issue occur in?

1.62.1

### Describe the issue in detail.

Title, I reckon it has something to do with server ping but yeah.

### Provide some images / videos of the issue in action.

No video cuz pretty self explanatory. Others are also experiencing this
![kuva](https://github.com/user-attachments/assets/6aeebd77-0786-4371-913f-a79877312839)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by Silbersix** [comment]
Can confirm also experience this issue and it seems be dropping the release input of the f key. Additional check of (is held) on a delay should be a simple script fix.

**Comment by AresWalker8** [comment]
I keep getting this too. If I press f again it stops until what ever causes it happens again. I think the save system or anti-cheat causes it.
