### ISSUE TITLE
[BUG]: can't swim

### ISSUE THREAD

**Issue by Geckguru** [typical-developers/oaklands-feedback#778]
### Roblox Username

Geckguru

### What version did this issue occur in?

1.62.2

### Describe the issue in detail.

Starting yesterday, I went into the lucite caves to go mining for lumite, and I jumped into the water because lucite spawns there. When I tried to swim up the waterfall to get back up to where I could drop the ores off, I couldn't. For some reason, I can't swim. I can see other people swim, but I can't. My oxygen still depletes, which is weird.

### Provide some images / videos of the issue in action.

![45DD1174-1265-43D9-B4D0-BC5CD3FFA262_1_201_a](https://github.com/user-attachments/assets/1656d651-d381-4c39-95f6-8d37766d9bf4)
![0DC8972B-CDBC-449D-AFC8-E873259F1570_1_201_a](https://github.com/user-attachments/assets/cea0b37c-3c61-4bb4-a046-4b470945c8ab)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by SniperOnSunday** [comment]
Do you have a Scooba tank equipped?

**Comment by Geckguru** [comment]
I do, yeah

**Comment by SniperOnSunday** [comment]
Refined scooba tank causes you to sink while enabled.

**Comment by Geckguru** [comment]
really? It hadn't done that before

**Comment by Geckguru** [comment]
That's really weird

**Comment by Geckguru** [comment]
I see now, thank you
