### ISSUE TITLE
[IMPROVEMENTS]: Network ownership for elevators

### ISSUE THREAD

**Issue by artz144** [typical-developers/oaklands-feedback#791]
### Roblox Username

chechyva

### What do you think can have quality-of-life improvements?

elevators

### How do you think things can be improved?

In laggy public servers elevators become unusable: server lag heavily slows them down. My proposal is to transfer its network ownership to the player, possibly making it move at full speed as intended.

**Comment by SniperOnSunday** [comment]
Please please please please please please add this for the love of God

**Comment by HooferDevelops** [comment]
This is added in the next update, thanks for the suggestion!
