### ISSUE TITLE
[BUG]: Missing assets (visualy)

### ISSUE THREAD

**Issue by saucepizza** [typical-developers/oaklands-feedback#792]
### Roblox Username

Diamondguy2017

### What version did this issue occur in?

1.62.2

### Describe the issue in detail.

after logging into oaklands earlier my game was missing some icons in the menu, i thought nothing of it and loaded in, after i loaded in i was still missing some icons but now I was not seeing any leaves on the trees some rocks are missing from the terrain, but the physics were still there, along with that the crazy man NPC had no clothes, apon going in the shop some of the images were missing. it seems to just be visual but im going to stay ingame for further testing

### Provide some images / videos of the issue in action.

![63172709_9938675423_1722367824870](https://github.com/user-attachments/assets/e902c9df-18ea-4e64-a3f9-60a9c80181bc)
![63172709_9938675423_1722368382921](https://github.com/user-attachments/assets/4896a96e-36da-49b7-8e49-f2c899153f7d)
![63172709_9938675423_1722368818172](https://github.com/user-attachments/assets/ee324681-ce4e-42d7-9cc1-2d4928cfe0ac)
![63172709_9938675423_1722368854685](https://github.com/user-attachments/assets/a95f3d6e-e4e5-45f8-a6b1-0458284d696c)
![63172709_9938675423_1722368870183](https://github.com/user-attachments/assets/7baea687-a2f1-4a29-8994-35e9690d2278)
![63172709_9938675423_1722368907750](https://github.com/user-attachments/assets/6992ef2c-e927-42f9-acbf-b55b2dd54828)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by saucepizza** [comment]
Forgot to mention, i did restart my game to see if it was just a fluke it was not

**Comment by HooferDevelops** [comment]
Unfortunately this is just a Roblox issue. Some users have reported that reinstalling Roblox fixes it, others it fixed with a simple restart, some with restarting their computer, etc.
