### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by pavel355** [typical-developers/oaklands-feedback#797]
### Roblox Username

pavelbat3

### What version did this issue occur in?

1.62.2

### Describe the issue in detail.

after selling anything in the jar, jar loses its owner and the press machine doesn't eat jars fix it in the recent update please, i want to earn money with this method

### Provide some images / videos of the issue in action.

https://www.youtube.com/watch?v=PvoBJK2h__Q

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Will be fixed 1.63.0, thanks!

**Comment by pavel355** [comment]
thank you so much man
