### ISSUE TITLE
[BUG]: holes in the map

### ISSUE THREAD

**Issue by Jacob901388** [typical-developers/oaklands-feedback#8]
there are holes in the map that are located in the pathway next to the mushroom cave that was added in v1.38.1 and the right side of the bridge going into the savannah.
![Skärmbild 2023-08-30 210932](https://github.com/typical-developers/oaklands-feedback/assets/111160475/50da5257-2e37-415f-8256-f124252af4b8)
![Skärmbild 2023-08-30 210916](https://github.com/typical-developers/oaklands-feedback/assets/111160475/af5964a8-f425-4f7a-bbf7-3c432fb6d3cc)
![Skärmbild 2023-08-30 210903](https://github.com/typical-developers/oaklands-feedback/assets/111160475/b892737d-ffd7-4abc-a92c-0db788da8009)
![Skärmbild 2023-08-30 210629](https://github.com/typical-developers/oaklands-feedback/assets/111160475/3b43ceb1-2db5-4751-8f1d-d5aa8f5517c3)

**Comment by LuckFire** [comment]
please make this report under the proper issue template
