### ISSUE TITLE
[BUG]: Items anchoring and crates being weirdly affected by the vehicle anchoring system through roofs

### ISSUE THREAD

**Issue by SunnyFloppyDiskStudios** [typical-developers/oaklands-feedback#81]
### Roblox Username

backpacksucs

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

In my demonstration, a car, trailer, oakmobile, (and maybe trolley?) were used to show how crates were being affected by the car's "loading area" being up by the roof.

In my demonstrations (clip 1, 2), I was unable to recreate the initial reaction. Initially, the crates were moved up, and all items inside them were noclipped out of the crates. However, these videos show how the crates CAN be affected by the anchoring system.

In my third clip (clip 3), I showed that it does also affect loose items, and also that the anchoring bug occurs with trailers.

In clip 4, i proved that it also works with a putter. While undocumented, i tested it with the other available vehicles (even a rusty joop), and smaller trailer, and open-sided trailers, and it also worked. It did not work with a sellnor (documented in the third clip)

### Provide some images / videos of the issue in action.

ALL HAIL THE GRACIOUS ONEDRIVE OVERLORDS!

[Onedrive Link](https://1drv.ms/f/s!AhJ-85r3fzq3ge9hKk1nw_oSVSp5rw?e=I6zdE5)

--> https://1drv.ms/f/s!AhJ-85r3fzq3ge9hKk1nw_oSVSp5rw?e=I6zdE5

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by HooferDevelops** [comment]
Is this issue still occurring?
