### ISSUE TITLE
[BUG]: Gifted gamepass not showing up as bought outside of game

### ISSUE THREAD

**Issue by Alex-Purschwitz** [typical-developers/oaklands-feedback#821]
### Roblox Username

Buddermcman

### What version did this issue occur in?

1.63.3

### Describe the issue in detail.

I don't know if this is a issue or not but i wanted to bring it up as a gifted gamepass I got shows up in game but not outside of it in the store on the game page or inventory. I want to make it clear I have the gamepass in game but i wanted some clarity if this was a issue about if it was to show up outside of the game aswell.

### Provide some images / videos of the issue in action.

![image_2024-08-09_215832795](https://github.com/user-attachments/assets/a018c8c8-ea80-4262-b5a3-d9b65bc52f59)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by Alex-Purschwitz** [comment]
![image_2024-08-09_215939413](https://github.com/user-attachments/assets/15c1a8ac-70f1-4695-ad38-536fdf58019b)

**Comment by HooferDevelops** [comment]
Unfortunately there's no way for us to actually give you the gamepass itself. The way it works is it gives you the perks via a flag on your save data. This means you'll basically have everything (except it won't show you own the gamepass).

**Comment by Alex-Purschwitz** [comment]
alright thank you for clarifying.
