### ISSUE TITLE
[BUG]: Vinyl Music doesn't play in basements

### ISSUE THREAD

**Issue by Mindlesslamo** [typical-developers/oaklands-feedback#822]
### Roblox Username

Mindlesslamo

### What version did this issue occur in?

1.63.1

### Describe the issue in detail.

When having a vinyl playing, you will hear it on the surface of your base but you will not hear it in the basement

### Provide some images / videos of the issue in action.

https://github.com/user-attachments/assets/5b8e0eaf-21f4-48bb-a4fd-c4ee452f044c

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by SniperOnSunday** [comment]
Duplicate of #820.

**Comment by SniperOnSunday** [comment]
Also, since Hoofer hasn't mentioned it yet, fixed as of 1.63.2
