### ISSUE TITLE
[BUG]: VIP gamepass costs more than the stated price when gifting

### ISSUE THREAD

**Issue by Henry4799** [typical-developers/oaklands-feedback#832]
### Roblox Username

godlybossman234

### What version did this issue occur in?

1.64.0

### Describe the issue in detail.

When buying the VIP gamepass for yourself it only costs the stated price of 349, however when gifting it to someone else it costs 449. As far as i can tell no other gamepasses are like this.

### Provide some images / videos of the issue in action.

![glitch 1](https://github.com/user-attachments/assets/6a7eaca4-f127-4265-b91c-da0bbadc3bd2)
![glitch 2](https://github.com/user-attachments/assets/cbaf6aa6-e4da-471d-8fbf-a41144f3d9a9)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Fixed, thanks!
