### ISSUE TITLE
[IMRPOVEMENTS]: Boxed Structures with Increased Contents should allow you to continue placing without exiting out of the build menu each time

### ISSUE THREAD

**Issue by WhalesMW** [typical-developers/oaklands-feedback#85]
### Roblox Username

WhalesMW

### What do you think can have quality-of-life improvements?

Boxed Structures with Increased Contents

### How do you think things can be improved?

Boxed Structures with Increased Contents currently exit you out of the build menu each time you place the structure and then you have to interact with the box again, this should not be the case. You should be able to just keep placing while it takes away from the amount inside the box. This will be a massive improvement and make the Increase Contents feature actually useful.

**Comment by HooferDevelops** [comment]
Will look into doing this with the revamped building system, current system is very spaghetti code.
