### ISSUE TITLE
Rain FPS Bug?

### ISSUE THREAD

**Issue by KaiiCommits** [typical-developers/oaklands-feedback#861]
### Roblox Username

iPookScore

### What version did this issue occur in?

1.65.3

### Describe the issue in detail.

on console the fps seems to drop below 25 when idle and drop to below 20 when moving and looking around. when it appears to rain and lighting. It has caused a lot of issues and needs to be fixed. 

Sincerely, kaii.

### Provide some images / videos of the issue in action.

![IMG_8178](https://github.com/user-attachments/assets/cbc1298e-938a-44b8-bdba-e8fec3df1c60)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
I did some performance changes that should improve this in the next update.
