### ISSUE TITLE
[IMRPOVEMENTS]:  Sanded Hallow Wood is too similar to Quartz

### ISSUE THREAD

**Issue by WhalesMW** [typical-developers/oaklands-feedback#87]
### Roblox Username

WhalesMW

### What do you think can have quality-of-life improvements?

Sanded Hallow Wood Texture/Material

### How do you think things can be improved?

Perhaps change the Sanded Hallow wood to be more unique like Neon or Granite (Sweetstone Texture).

**Comment by HooferDevelops** [comment]
Good point. The only thing is, I made it ice material to allow users to create a friction-less material. At most I could change the color slightly, if you have any ideas, that would be appreciated!

**Comment by HooferDevelops** [comment]
New solution: Change material to Granite whilst keeping the slipperiness properties from the ice.
