### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by 4rdency** [typical-developers/oaklands-feedback#871]
### Roblox Username

AbsurdlyGoofyCookies

### What version did this issue occur in?

1.65.3

### Describe the issue in detail.

I've purchased 2 Storage Drawers separately. One worked perfectly fine and still is, but the other was bugged once I placed it.

I'm unable to interact with it in any way (aside from moving, rotating, etc.) I cannot input any items, output items, lock the input, edit the text, or inspect the object. The only UI I see when hovering over it with my mouse is "Storage Drawer" and, underneath the name, an empty bar that ends with 0%. It doesn't even show that I'm the owner.

I'm not too sure if what I'm experiencing is an actual bug or some kind of an intended feature, since I'm relatively new. Thank you for your time, and have a good rest of your day!!

### Provide some images / videos of the issue in action.

![image](https://github.com/user-attachments/assets/9f796a3f-e52a-419b-979b-e1c7225971a8)
![image](https://github.com/user-attachments/assets/945024e5-ce8d-4109-95da-674d6524bdc0)
![image](https://github.com/user-attachments/assets/34434ff3-8f04-445f-83d8-3530b1a858d2)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by UltrasBlade** [comment]
the storage drawer is a schematic, you have to fill it with a material to use it

**Comment by 4rdency** [comment]
I greatly appreciate the reply. I wasn't aware that you had to fill it with material first in order to use it. Thank you so much, UltrasBlade!! 😁
