### ISSUE TITLE
[IMPROVEMENTS]: Make inventory system local

### ISSUE THREAD

**Issue by Chresss** [typical-developers/oaklands-feedback#89]
### Roblox Username

Chresivoigt

### What do you think can have quality-of-life improvements?

Inventory system

### How do you think things can be improved?

This is one of the mechanics that REALLY suffers from lag. I think changing this to run locally; (un)equipping tools and enabling their respective abilities, would greatly increase the flow of the game, even in lag. Additionally, I think less people would complain about lag

**Comment by LuckFire** [comment]
I don't think this would improve performance on the large scale it would need to be done on. It's such a minor thing compared to other areas that could be optimized for probably quadruple the amount of performance (tree generation being one of those huge examples).

**Comment by KinderDeveloper** [comment]
> I don't think this would improve performance on the large scale it would need to be done on. It's such a minor thing compared to other areas that could be optimized for probably quadruple the amount of performance (tree generation being one of those huge examples).

I don't think he's really suggesting this as a server performance fix, he's referencing the fact that most games on Roblox have client-sided tool equip which means you can equip your tools no matter how laggy the server-side is.

The default Roblox toolbar is a great example of this, no matter the lag you can always select a tool. Simply QoL

**Comment by HooferDevelops** [comment]
> > > I don't think this would improve performance on the large scale it would need to be done on. It's such a minor thing compared to other areas that could be optimized for probably quadruple the amount of performance (tree generation being one of those huge examples).
> > 
> > 
> > I don't think he's really suggesting this as a server performance fix, he's referencing the fact that most games on Roblox have client-sided tool equip which means you can equip your tools no matter how laggy the server-side is.
> > The default Roblox toolbar is a great example of this, no matter the lag you can always select a tool. Simply QoL
> 
> I see.. thought if that's the case, I'm pretty certain @HooferDevelops has a reason for doing tool equipping on the server side (iirc he was the one that did all the inventory stuff).

I initially did it for security, but I don't like it anymore. I want to redo it at some point.
