### ISSUE TITLE
[BUG]: Items have a chance to disappear when grabbing

### ISSUE THREAD

**Issue by BNAC123** [typical-developers/oaklands-feedback#9]
### Roblox Username

eliwint123

### What version did this issue occur in?

1.39.5

### Describe the issue in detail.

I grabbed my adurite key and it disappeared 

### Provide some images / videos of the issue in action.

I don’t have any as I did not expect my adurite key to disappear 

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by LuckFire** [comment]
this appears to happen to items sometimes regardless and not just the adurite key
updated title to reflect this information

**Comment by BNAC123** [comment]
Is there any way to get it back?

**Comment by Katapillah** [comment]
I've experienced this with Wood/Ore ..it seems to be ghosted at times. Like you go to move something that you have already moved but it's image is still in the original location, so when you go to move that ghost ...it will vanish. (or seemingly 'teleport' to where you had previously moved it to)

**Comment by Katapillah** [comment]
^ Correlation with https://github.com/typical-developers/oaklands-feedback/issues/22
