### ISSUE TITLE
[IMPROVEMENTS]: Autounloaders

### ISSUE THREAD

**Issue by mrnoobwebon** [typical-developers/oaklands-feedback#910]
### Roblox Username

mrnoobwbn

### What do you think can have quality-of-life improvements?

Connect wires to the vehicle spawners

### How do you think things can be improved?

when you connect a wire from a pressure plate, you can connect it directly to the vehicle spawn button

**Comment by 1Peekaboo1** [comment]
....Interactor exists dude

**Comment by mrnoobwebon** [comment]
I completely forgot
