### ISSUE TITLE
[BUG]: Misspelling in the cheese tip

### ISSUE THREAD

**Issue by ModernToaster** [typical-developers/oaklands-feedback#912]
### Roblox Username

ModernToasters

### What version did this issue occur in?

1.66.2 [Alpha]

### Describe the issue in detail.

The tip revolving around neon cheese, “[TIP]: I hope you’re not lactose intolerant because theres a 1 in 2000 chance cheese can be neon!” has a grammar error, the ‘your’ would be ‘you’re’ 
Bonus would be an apostrophe in ‘theres’ to make it there’s 
I apologize dearly for the grammar policing nonetheless ;-;

### Provide some images / videos of the issue in action.

![IMG_2427](https://github.com/user-attachments/assets/74705ff8-cd2f-435b-befc-8f6a893a0fcf)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
can't believe I missed this while proofreading
