### ISSUE TITLE
[BUG]: Glass door dulication 

### ISSUE THREAD

**Issue by moumoulles** [typical-developers/oaklands-feedback#920]
### Roblox Username

moumoulles10

### What version did this issue occur in?

1.66.3

### Describe the issue in detail.

glass door are not suposed to be duplicate ? i think.

### Provide some images / videos of the issue in action.

https://outplayed.tv/roblox/Vy7gV3

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by WaffleMaker784** [comment]
you bought 8 glass doors, including the one that was already placed. 
![ezgif-1-bb7ffac40c](https://github.com/user-attachments/assets/4ea9e753-058c-4823-b775-1e85244a2ce2)

really went the full distance just to show you 😔

please close the issue
