### ISSUE TITLE
Gradient for main menu abruptly ends on mobile holepunch displays

### ISSUE THREAD

**Issue by gaymeowing** [typical-developers/oaklands-feedback#953]
### Roblox Username

kalrnlo

### What version did this issue occur in?

latest

### Describe the issue in detail.

The gradient should be in a separate ScreenGui with a different ScreenInset property

### Provide some images / videos of the issue in action.

![Screenshot_20240913-112251](https://github.com/user-attachments/assets/8963fb5e-3dd7-4a64-8943-2985811eabe3)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by AkkozaDevelops** [comment]
This will be fixed in the next update!
