### ISSUE TITLE
Jump button and thumbstick visible on main menu

### ISSUE THREAD

**Issue by gaymeowing** [typical-developers/oaklands-feedback#954]
### Roblox Username

kalrnlo

### What version did this issue occur in?

latest

### Describe the issue in detail.

The players character should have its jumppower and walkspeed set to 0 to hide these buttons

### Provide some images / videos of the issue in action.

![Screenshot_20240913-112251](https://github.com/user-attachments/assets/fc96ad39-e2f4-4eea-bd4d-2ee2622563e0)

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by gaymeowing** [comment]
omg i didnt realise this exists
https://create.roblox.com/docs/reference/engine/classes/GuiService#TouchControlsEnabled

**Comment by AkkozaDevelops** [comment]
> omg i didnt realise this exists https://create.roblox.com/docs/reference/engine/classes/GuiService#TouchControlsEnabled

I also never knew this existed, I will add an implementation for this; thank you!
