### ISSUE TITLE
Respect the roblox Reduced Motion setting

### ISSUE THREAD

**Issue by gaymeowing** [typical-developers/oaklands-feedback#964]
### Roblox Username

kalrnlo

### What version did this issue occur in?

latest

### Describe the issue in detail.

Currently disabling the reduced motion setting in roblox doesn't disable the in-game screenshake or the shop icon rotating.
The game should if the user hasn't manually changed the screen shake setting or shop icon rotating setting, have them set either to true or false based on if [ReducedMotionEnabled](https://create.roblox.com/docs/reference/engine/classes/GuiService#ReducedMotionEnabled) is true. They should also be automatically changed if the user hasn't changed those settings themselves in-game, and the ReducedMotionEnabled property of GuiService changes

### Provide some images / videos of the issue in action.

n/a

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.
- [X] I understand that I cannot be reimbursed here for in-game content I have lost.

**Comment by HooferDevelops** [comment]
I added this to a bunch of spots when you suggested this in the Discord, thanks!
