### ISSUE TITLE
Multiselect in build mode

### ISSUE THREAD

**Issue by gaymeowing** [typical-developers/oaklands-feedback#966]
### Roblox Username

kalrnlo

### What do you think can have quality-of-life improvements?

build mode

### How do you think things can be improved?

Currently there is no way to select multiple items within buildmode without tediously clicking on every item u want to select. What I suggest is adding a lasso tool or a multislect tool, where you drag a box across the screen and it'll select every item that is in that box.
If a lasso tool is added it'd be the same except u gotta make the shape via dragging out its edges, and it'd work the same in regards with selecting everything thats in that shape

**Comment by 1Peekaboo1** [comment]
hold F and drag

it's not told anywhere so maybe a better suggestion would to actually tell the user that it's possible
