### ISSUE TITLE
[BUG]: Unable to drag recently mined ore with Grabby Grabber

### ISSUE THREAD

**Issue by Railfan475** [typical-developers/oaklands-feedback#97]
### Roblox Username

railfan475

### What version did this issue occur in?

1.41.0

### Describe the issue in detail.

sometimes whenever I mine an ore, I am unable to pick it up by hand or with the grabby grabber.

### Provide some images / videos of the issue in action.

https://github.com/typical-developers/oaklands-feedback/assets/147887860/ddf69dbd-f1a4-4df9-8d47-001c3ff8f2ce

### Before Submitting

- [X] I have confirmed that nobody else reported this issue.
- [X] The details of this report are legitimate.

**Comment by Railfan475** [comment]
please excuse the lag, my PC is a potato

**Comment by HooferDevelops** [comment]
Does this still occur? Is there a way to reproduce it?

**Comment by Railfan475** [comment]
I think it was an issue on my end, I haven't experienced it since the
halloween event ended. Also, submitted that a while ago.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
